var gvjs_$W="ABCDEFGHIJKLMNOPQRSTUVWXYZ",gvjs_aX="allValuesSuffix",gvjs_bX="annotationsContainer",gvjs_cX="annotationsFilterContainer",gvjs_dX="background-color",gvjs_eX="chartContainer",gvjs_fX="containerTable",gvjs_gX="dateFormat",gvjs_hX="displayAnnotations",gvjs_iX="displayDateBarSeparator",gvjs_jX="displayLegendDots",gvjs_kX="displayLegendValues",gvjs_lX="displayRangeSelector",gvjs_mX="displayZoomButtons",gvjs_nX="numberFormats",gvjs_oX="outerChartContainer",gvjs_pX="zoomButtons.";
gvjs_en.prototype.zK=gvjs_B(24,function(a){this.fK=a});gvjs_qn.prototype.zK=gvjs_B(23,function(a){this.Mm.zK(a)});function gvjs_Eka(a){return void 0!==a.lastElementChild?a.lastElementChild:gvjs_Tc(a.lastChild,!1)}function gvjs_qX(a,b,c){var d=a.Y(c);if(d!==gvjs_Pa&&d!==gvjs_Qa)throw Error(gvjs_Se+c+" must be of type date or datetime, but is "+(d+"."));return a.getValue(b,c)}
var gvjs_Fka={annotationsWidth:25,annotationsFilter:"off",scaleValues:null,dateFormat:"MMMM dd, yyyy",displayRangeSelector:!0,displayAnnotations:!0,displayAnnotationsFilter:!1,displayZoomButtons:!0,zoomButtons:{"1-second":{label:"1s",offset:[0,0,1]},"5-seconds":{label:"5s",offset:[0,0,5]},"10-seconds":{label:"10s",offset:[0,0,10]},"15-seconds":{label:"15s",offset:[0,0,15]},"1-minute":{label:"1min",offset:[0,1,0]},"5-minutes":{label:"5min",offset:[0,5,0]},"10-minutes":{label:"10min",offset:[0,10,0]},
"15-minutes":{label:"15min",offset:[0,15,0]},"1-hour":{label:"1h",offset:[1,0,0]},"6-hours":{label:"6h",offset:[6,0,0]},"1-day":{label:"1d",offset:[1,0,0,0,0]},"5-days":{label:"5d",offset:[5,0,0,0,0]},"1-week":{label:"1w",offset:[7,0,0,0,0]},"1-month":{label:"1m",offset:[1,0,0,0,0,0]},"3-months":{label:"3m",offset:[3,0,0,0,0,0]},"6-months":{label:"6m",offset:[6,0,0,0,0,0]},"1-year":{label:"1y",offset:[1,0,0,0,0,0,0]},max:{label:gvjs_ht,range:{start:null,end:null}}},zoomButtonsOrder:["1-hour","1-day",
"5-days","1-week","1-month","3-months","6-months","1-year",gvjs_ht],displayLegendDots:!0,displayDateBarSeparator:!0,displayExactValues:!1,fill:0,lclt:0,labelColors:null,allowHtml:!1},gvjs_Gka={annotations:{textStyle:{fontSize:10,auraColor:gvjs_b},boxStyle:{stroke:"#888888",strokeWidth:.5,rx:2,ry:2,gradient:{color1:"#eeeeee",color2:"#dddddd",x1:gvjs_eo,y1:gvjs_eo,x2:gvjs_eo,y2:gvjs_ho,useObjectBoundingBoxUnits:!0}}},backgroundColor:gvjs_ca,chartArea:{width:gvjs_ho,backgroundColor:gvjs_ca},height:200,
width:gvjs_ho,hAxis:{baselineColor:gvjs_b,slantedText:!1,maxAlternation:1,gridlines:{count:-1},textStyle:{fontSize:9}},vAxis:{baselineColor:"#ababab",gridlines:{count:-1,color:"#ECECF7"},textPosition:gvjs_Gs,inTextPosition:"high",viewWindowMode:gvjs_mt},legend:{position:gvjs_b,alignment:gvjs_W},colors:gvjs_PF,targetAxisIndex:1,focusTarget:gvjs_oq,tooltip:{trigger:gvjs_b},candlestick:{hollowIsRising:!0},forceIFrame:!1,animation:{duration:0}},gvjs_Hka={filterColumnIndex:0,ui:{chartType:gvjs_Le,chartOptions:{chartArea:{width:gvjs_ho,
height:gvjs_ho,backgroundColor:{fill:gvjs_ca,stroke:"#ababab",strokeWidth:.5}},height:40,width:gvjs_ho,backgroundColor:gvjs_ca,areaOpacity:.1,lineWidth:1,forceIFrame:!1,hAxis:{baselineColor:gvjs_b,slantedText:!1,maxAlternation:1,gridlines:{},textPosition:gvjs_Gs,textStyle:{fontSize:9}},vAxis:{baselineColor:gvjs_b,scaleType:gvjs_xt}},sideScreenColor:{fill:"#f2f2f2",fillOpacity:.75},zoomAroundSelection:!0,chartView:{columns:[0,1]}}},gvjs_Ika={width:gvjs_ho,height:gvjs_ho,allowHtml:!0,sortAscending:!1,
sortColumn:0};function gvjs_rX(a){gvjs_dz.call(this,a);this.gb=null;this.ZG=!0;this.qa=null;this.oi=0;this.$L=this.KU=this.zu=this.Vi=this.gx=this.Yr=this.Eh=this.V=this.EF=this.lm=this.Ic=this.K=this.m=this.su=null;this.cI={};this.$q=this.oN=this.nE=this.lf=null;this.aa=new gvjs_jz;this.Rd=new gvjs_ZJ(this);this.SY=!1;this.G=gvjs_Fk()}gvjs_l(gvjs_rX,gvjs_dz);gvjs_=gvjs_rX.prototype;
gvjs_.kf=function(){this.aa.removeAll();gvjs_H(this.Rd);this.Rd=new gvjs_ZJ(this);gvjs_H(this.aa);this.aa=new gvjs_jz;this.SY=!1;this.Vi&&this.Vi.clear();this.Eh&&this.Eh.clear();this.V&&this.V.clear();this.container&&this.G.Ac(this.container)};gvjs_.kv=function(){return this.V.sf()};gvjs_.getSelection=function(){var a=this;return this.kv().getSelection().map(function(b){b=gvjs_sX(a,b.row,b.column);return{row:b.row,column:b.column}})};
gvjs_.setSelection=function(a){var b=this,c=this.kv();null==a||0===a.length?c.setSelection([]):(a=a.map(function(d){d=gvjs_tX(b,d.row,d.column);return{row:d.row,column:d.column}}),c.setSelection(a))};gvjs_.N9=function(){return this.Eh.getState().range};gvjs_.setVisibleChartRange=function(a,b,c){this.Eh.setState({range:{start:a,end:b}});gvjs_uX(this,this.Eh);gvjs_vX(this,null==c?!0:c)};gvjs_.O$=function(a){gvjs_wX(this,a,!0)};gvjs_.bfa=function(a){gvjs_wX(this,a,!1)};
function gvjs_wX(a,b,c){gvjs_h(b)||(b=[b]);b=gvjs_cb(b);for(var d=b.next();!d.done;d=b.next())a.cI[d.value]=c;a.Pt()}gvjs_.Pt=function(){this.draw(this.qa,this.su,this.K)};
gvjs_.gg=function(a,b,c,d){this.su=c||{};this.K=d||{};this.vL(b);this.oZ(b);gvjs_Jka(this);a=this.Ri=new gvjs_N(this.qa);a.np(this.lf);b=a.$B([{column:this.oi,test:function(e){return null!=e}}]);a.vp(b);b=a.bt(this.oi);a.vp(b);b=gvjs_qX(this.Ri,0,this.oi);c=gvjs_qX(this.Ri,this.Ri.ca()-1,this.oi);this.qN={min:b,max:c};this.aO();gvjs_Kka(this);gvjs_xX(this);gvjs_Lka(this);gvjs_Mka(this);gvjs_Nka(this);gvjs_Oka(this);gvjs_Pka(this);gvjs_Qka(this);this.V.ah(a);this.Eh.ah(a);gvjs_uX(this,this.Eh);gvjs_vX(this,
!1)};gvjs_.oZ=function(a){this.qa=a;this.gp()};gvjs_.vL=function(a){if(!a)throw Error(gvjs_Lo);var b=a.$();if(2>b)throw Error(gvjs_Ko);if(a.Y(0)!=gvjs_Pa&&a.Y(0)!=gvjs_Qa)throw Error("First column must contain date, or date and time.");for(var c,d,e=!1,f=0,g=1;g<b&&!e;g++)c=a.Y(g),c==gvjs_c?f=1:0==f?(e=!0,d=g):1==f?c==gvjs_d?f=2:(e=!0,d=g):2==f&&(c==gvjs_d?f=0:(e=!0,d=g));if(e)throw Error("Each values column may be followed by one or two annotation columns. column number "+d+gvjs_Hn+c);};
function gvjs_Kka(a){var b=a.gb;b&&b.DR&&gvjs_J(b.DR,gvjs_mr,gvjs_b);var c=a.getHeight(a.m),d=a.Sa(a.m);if(b){gvjs_Oy(b.DR,d,c);gvjs_J(b.DR,gvjs_mr,"");var e=gvjs_Zy(b.ZF);a.Oa=c-(e.top+e.bottom);a.da=d-(e.left+e.right);gvjs_Oy(b.ZF,a.da,a.Oa)}else{b=a.gb={};var f=a.G;f.Ac(a.container);gvjs_xB(a.container,["google-visualization-atl","container"]);var g=a.container.id+"_AnnotationChart_",h=function(l,m,n){var p=f.createElement(gvjs_Ra);l&&(p.id=g+l);p.className=m;n.appendChild(p);return p},k=b.DR=
h("","",a.container);gvjs_J(k,gvjs_Xg,gvjs__g);gvjs_Oy(k,d,c);k=h("","",k);gvjs_J(k,gvjs_Xg,gvjs_T);gvjs_Ey(k,0,0);gvjs_Oy(k,gvjs_ho,gvjs_ho);k=b.ZF=h("borderDiv","border",k);k=b.$Ba=h(gvjs_fX,gvjs_fX,k);e=gvjs_Zy(b.ZF);a.Oa=c-(e.top+e.bottom);a.da=d-(e.left+e.right);gvjs_Oy(b.ZF,a.da,a.Oa);a=b.VBa=h("chartTd","td chartTdContainer",k);c=b.LU=h("annotationsTd","td annotationsTdContainer",k);d=b.RCa=h(gvjs_oX,gvjs_oX,a);k=b.Wka=h("chartControlsContainer","chartControls",d);b.oF=h("zoomControlContainer",
"zoomControls",k);b.ssa=h("legendContainer",gvjs_Ys,k);b.Uka=h(gvjs_eX,gvjs_eX,d);b.e1=h("rangeControlContainer","rangeControl",a);b.FF=h(gvjs_cX,gvjs_cX,c);b.JU=b.JU=h(gvjs_bX,gvjs_bX,c)}}
function gvjs_Nka(a){var b=1+gvjs_ce(a.Ic,["series.0.pointSize",gvjs_3t],6),c=gvjs__y(a.gb.Wka).height,d=gvjs_s(a.m,gvjs_lX)?gvjs_t(a.lm,"ui.chartOptions.height"):0;c=a.Oa-(c+d);var e=Math.max(b,gvjs_t(a.Ic,gvjs_zq,0)),f=Math.max(b,2+2*gvjs_t(a.Ic,"hAxis.textStyle.fontSize"));f=Math.max(f,gvjs_t(a.Ic,gvjs_vq,0));gvjs_Ew(a.Ic,1,{height:c,chartArea:{top:e,bottom:f,height:c-(e+f)}});gvjs_Ew(a.lm,1,{ui:{chartOptions:{chartArea:{height:d}}}});d=0;a.ZG?(d=a.EF.ea(gvjs_8a,gvjs_of),gvjs_Ny(a.gb.LU,d),d=gvjs_Py(a.gb.LU).width,
d=Math.max(0,d)):gvjs_Ny(a.gb.LU,0);d=a.da-d;c=Math.max(b,gvjs_t(a.Ic,gvjs_xq,0));b=Math.max(b,gvjs_t(a.Ic,gvjs_yq,0));e=d-(c+b);gvjs_Ew(a.Ic,1,{width:d,chartArea:{left:c,right:b,width:e}});gvjs_Ew(a.lm,1,{ui:{chartOptions:{width:d,chartArea:{left:c+1,right:b+2,width:e-3}}}})}
function gvjs_Oka(a){a.V||(a.V=new gvjs_O({chartType:gvjs_Ue,container:a.gb.Uka}));a.Eh||(a.Eh=new gvjs_P({controlType:"ChartRangeFilter",container:a.gb.e1}),gvjs_Qk(a.Eh,gvjs_x,gvjs_k(function(){gvjs_Mk(this.Eh,gvjs_4g,gvjs_k(this.oqa,this))},a)));if(a.ZG){var b=gvjs_s(a.m,"displayAnnotationsFilter"),c=gvjs_k(function(){var d=this.ZG&&b?gvjs_Py(this.gb.FF).height:0;this.gb.JU.style.height=gvjs_Dy(this.Oa-d+gvjs_Y,!0)},a);a.GF||(a.GF=new gvjs_P({controlType:"StringFilter",container:a.gb.FF,options:{filterColumnLabel:"Text",
matchType:"any",useFormattedValue:!0,ui:{label:"Filter",labelSeparator:": "}}}));gvjs_J(a.gb.FF,gvjs_mr,b?"":gvjs_b);a.Vi||(a.Vi=new gvjs_O({chartType:gvjs_df,container:a.gb.JU}),gvjs_Qk(a.Vi,gvjs_x,gvjs_k(function(){gvjs_Mk(this.Vi,gvjs_z,gvjs_k(this.xqa,this))},a)));a.Yr?c():(a.Yr=new gvjs_qn(a.gb.FF),a.Yr.zK(a.Tt),a.Yr.bind(a.GF,a.Vi),gvjs_Qk(a.Yr,gvjs_x,c))}else gvjs_Ch(a.gb.FF,gvjs_ac),a.Vi&&(a.Vi.clear(),a.Vi=null),a.GF&&(a.GF.clear(),a.GF=null),a.Yr&&(a.Yr.clear(),a.Yr=null);a.SY||(a.SY=!0,
gvjs_Mk(a.V,gvjs_x,gvjs_k(a.l_,a)),gvjs_Qk(a.V,gvjs_x,gvjs_k(function(){var d=this.kv();gvjs_Mk(d,gvjs_z,gvjs_k(this.Tpa,this));gvjs_Mk(d,gvjs_Mt,gvjs_k(this.Vpa,this));gvjs_Mk(d,gvjs_Lt,gvjs_k(this.Upa,this))},a)))}gvjs_.l_=function(){this.Rd.dispatchEvent(gvjs_x)};gvjs_.oqa=function(){var a=this.Eh.getState();gvjs_vX(this,!1);this.Rd.dispatchEvent(gvjs_eu,a.range)};
function gvjs_vX(a,b){var c=a.Eh.getState();a.V.Z("hAxis.viewWindow",{min:c.range.start,max:c.range.end});c=a.V.getOption(gvjs_Bp);b&&0===c&&a.V.Z(gvjs_Bp,150);gvjs_uX(a,a.V);a.V.Z(gvjs_Bp,c)}
function gvjs_Jka(a){a.lf=[{label:"Datetime",type:a.qa.Y(a.oi),calc:gvjs_k(function(g,h){return{v:g.getValue(h,this.oi),p:{dataRow:h}}},a)}];a.nE=[];for(var b=0,c=a.oi+1,d=a.qa.$();c<d;){var e=c,f={label:a.qa.Fa(c)+"  ",sourceColumn:c,properties:{dataColumn:e,viewColumn:a.lf.length}};a.cI[b]&&(f.type=gvjs_c,f.calc=function(){return null});a.lf.push(f);a.nE.push(f);c++;c<d&&a.qa.Y(c)===gvjs_d&&(c++,c<d&&a.qa.Y(c)===gvjs_d&&c++,a.cI[b]||a.lf.push({calc:function(g){return gvjs_k(function(h,k){return(h=
gvjs_yX(this,k,g))?h.key:null},this)}.call(a,e),type:gvjs_d,role:gvjs_Dp,properties:{dataColumn:e}}));b++}for(c=b=0;c<a.nE.length;c++)if(!a.cI[c]){b=c;break}gvjs_Ew(a.lm,1,{ui:{chartView:{columns:[0,a.nE[b].properties.viewColumn]}}});gvjs_Ew(a.lm,1,{ui:{chartOptions:{colors:[a.Jb[b%a.Jb.length]]}}})}
gvjs_.aO=function(){function a(){return("      "+b(f++)).substr(-e)}function b(n){return 26<=n?b(Math.floor(n/26)-1)+gvjs_$W[n%26]:gvjs_$W[n]}var c=this.qa.$(),d=this.qa.ca();this.zu=[];this.KU={};for(var e=Math.ceil(Math.log(d)/Math.log(26)),f=0,g=0;g<d;g++)for(var h=this.oi+1;h<c;){var k=h;h++;if(h<c&&this.qa.Y(h)===gvjs_d){var l=h,m=null;h++;h<c&&this.qa.Y(h)===gvjs_d&&(m=h,h++);(k=gvjs_Rka(this,this.zu.length,g,k,l,m,a))&&gvjs_Ska(this,k)}}this.ZG=gvjs_s(this.m,gvjs_hX)&&0<this.zu.length};
function gvjs_Rka(a,b,c,d,e,f,g){e=e&&a.qa.getValue(c,e);f=f&&a.qa.getValue(c,f);return e||f?(g=g(),a=a.qa.getValue(c,a.oi),{idx:b,key:g,title:e,text:f,date:a,vW:c,Ds:d}):null}
function gvjs_Tka(a){a.gx=new gvjs_L;a.gx.pe(gvjs_d,"Key");a.gx.pe(gvjs_d,"Text");a.$L=[];for(var b=[],c=0;c<a.zu.length;c++){var d=a.zu[c],e='<button type="button" class="key">'+gvjs_ph(d.key)+"</button>",f=d.date;a.oN&&(f=gvjs_ph(a.oN.ac(d.date)));var g=d.title||"";d=d.text||"";gvjs_s(a.m,gvjs_zp)||(g=gvjs_ph(g),d=gvjs_ph(d));b.push([e,'<span class="title">'+g+'</span> <span class="description">'+d+'</span> <span class="date">'+f+"</span> "])}a.gx.Lp(b);var h=a.gx.ca();b.forEach(function(k,l){a.gx.Tea(l,
"idx",h-l-1);a.$L[h-l-1]=l})}function gvjs_Pka(a){if(a.ZG){gvjs_Tka(a);var b=gvjs_Gw(a.EF);b.width=gvjs_ho;b.height=gvjs_ho;a.Vi.setOptions(b);a.Yr.draw(a.gx)}}
gvjs_.gp=function(){this.m=new gvjs__d([this.su,gvjs_Fka]);this.Ic=new gvjs__d([gvjs_Hw(this.m,gvjs_tf),gvjs_Gka]);this.lm=new gvjs__d([gvjs_Hw(this.m,gvjs_du),gvjs_Hka]);this.EF=new gvjs__d([gvjs_Hw(this.m,gvjs_6g),gvjs_Ika]);var a=this.m.ob(gvjs_Xp);a&&(gvjs_J(this.gb.ZF,gvjs_dX,a),gvjs_Ew(this.Ic,1,{backgroundColor:a}),gvjs_Ew(this.lm,1,{ui:{chartOptions:{backgroundColor:a}}}));gvjs_Ew(this.Ic,1,{colors:this.m.ea(gvjs_Qq)});this.Jb=this.Ic.ea(gvjs_Qq);gvjs_Ew(this.lm,1,{ui:{chartOptions:{colors:[this.Jb[0]]}}});
typeof this.m.ea(gvjs_Gr)===gvjs_c&&gvjs_Ew(this.Ic,1,{areaOpacity:gvjs_t(this.m,gvjs_Gr)/100,seriesType:gvjs_Qp});a=gvjs_s(this.m,gvjs_Ms,!1);gvjs_Ew(this.Ic,1,{interpolateNulls:a});gvjs_Ew(this.lm,1,{ui:{chartOptions:{interpolateNulls:a}}});gvjs_Ew(this.Ic,1,{vAxis:{maxValue:this.m.ea(gvjs_ht),minValue:this.m.ea(gvjs_qt)}});if(a=this.m.ea("scaleColumns"))if(0===a.length)gvjs_Ew(this.Ic,1,{vAxis:{textPosition:gvjs_b}});else{for(var b=1===a.length,c={},d=0;d<a.length;d++)c[a[d]]=b?{targetAxisIndex:1}:
{targetAxisIndex:d};gvjs_Ew(this.Ic,1,{series:c})}else gvjs_Ew(this.Ic,1,{vAxis:{targetAxisIndex:1}});this.m.ea(gvjs_wu)&&(this.m.ea(gvjs_wu)===gvjs_Pr||"allfixed"===this.m.ea(gvjs_wu))&&gvjs_Ew(this.Ic,1,{vAxis:{baseline:0}});this.qa.Y(this.oi)===gvjs_Qa?gvjs_Ew(this.m,1,{minDisplaySeconds:60,dateFormat:"HH:mm MMMM dd, yyyy",minTimelineGranularity:0}):gvjs_Ew(this.m,1,{minDisplaySeconds:86400,dateFormat:"MMMM dd, yyyy",minTimelineGranularity:86400});a=this.m.ea(gvjs_gX);a=typeof a===gvjs_d?{pattern:gvjs_r(this.m,
gvjs_gX)}:gvjs_Hw(this.m,gvjs_gX);this.oN=new gvjs_je(a);a=this.m.ea(gvjs_nX);if(typeof a===gvjs_d)a={pattern:gvjs_r(this.m,gvjs_nX)},this.$q=new gvjs_ne(a);else if(gvjs_i(a)){var e=[];this.$q=e;gvjs_o(gvjs_Hw(this.m,gvjs_nX),function(f,g){f={pattern:f};g=parseInt(g,10);e[g]=new gvjs_ne(f)})}else gvjs_s(this.m,"displayExactValues")?this.$q=null:(a={pattern:"#.##"},this.$q=new gvjs_ne(a));a=gvjs_r(this.m,"scaleFormat","#.########")+gvjs_r(this.m,gvjs_aX,"");gvjs_Ew(this.Ic,1,{vAxis:{format:a}});a=
this.m.Ca("thickness");gvjs_Ew(this.Ic,1,{lineWidth:null!=a?Math.max(1,a):1});a=this.m.ea("annotationsWidth");typeof a===gvjs_c?gvjs_Ew(this.EF,1,{width:a+"%"}):a&&gvjs_Ew(this.EF,1,{width:a});this.Vka="newRow"===gvjs_r(this.m,"legendPosition","sameRow")?"twoRows":"oneRow";gvjs_Ew(this.lm,1,{ui:{chartOptions:{width:this.Ic.ea(gvjs_8a)}}});gvjs_Ew(this.lm,1,{ui:{chartOptions:{chartArea:{width:this.Ic.ea(gvjs_Aq)}}}});this.m.ea("async",!1)&&(gvjs_Ew(this.Ic,1,{async:!0}),gvjs_Ew(this.lm,1,{ui:{chartOptions:{async:!0}}}))};
function gvjs_Qka(a){var b=a.Eh.getState()||{};b.range=b.range||{};var c=a.m.ea("zoomEndTime");null!=c&&(b.range.end=c);c=a.m.ea("zoomStartTime");null!=c&&(b.range.start=c);a.Eh.setState(b);gvjs_s(a.m,gvjs_lX)?a.gb.e1.style.display="":a.gb.e1.style.display=gvjs_b;b=gvjs_Gw(a.Ic);a.V.setOptions(b);b=gvjs_Gw(a.lm);a.Eh.setOptions(b)}
function gvjs_Lka(a){if(gvjs_s(a.m,"displayAggregationButtons")){var b=[{id:"daily",label:"Daily",modCalc:function(l){if(null!=l)return new Date(l.getFullYear(),l.getMonth(),l.getDate(),0)}},{id:"weekly",label:"Weekly",modCalc:function(l){if(null!=l)return new Date(l.getFullYear(),l.getMonth(),l.getDate()-l.getDay())}},{id:"monthly",label:"Monthly",modCalc:function(l){if(null!=l)return new Date(l.getFullYear(),l.getMonth(),1)}},{id:"year",label:"Yearly",modCalc:function(l){if(null!=l)return new Date(l.getFullYear(),
0,1)}}],c=a.gb.oF.id;var d="Aggragate: ";for(var e=0;e<b.length;e++){var f=b[e],g=c+"_"+f.id;d+=' <button type="button" id="'+g+'" href="#">'+gvjs_ph(f.label)+"</button>"}d+="<br />";e=function(l){for(var m=0;m<l.length;m++)if(null!==l[m])return l[m]};var h=[];f=a.qa.$();for(g=a.oi+1;g<f;)h.push({column:g,type:gvjs_c,label:a.qa.Fa(g),aggregation:gvjs_zn}),g++,g<f&&(h.push({column:g,type:gvjs_d,label:a.qa.Fa(g),aggregation:e}),g++,g<f&&(h.push({column:g,type:gvjs_d,label:a.qa.Fa(g),aggregation:e}),
g++));var k=a.qa.Fa(a.oi);for(e=0;e<b.length;e++)f=b[e],d=gvjs_k(function(l){return gvjs_k(function(){gvjs_An(this.qa,[{column:this.oi,type:gvjs_Pa,label:k,modifier:l}],h)},this)},a),g=c+"_"+f.id,a.aa.D(a.G.j(g),gvjs_Jq,d(f.modCalc))}}
function gvjs_Mka(a){var b=a.gb.oF.id,c=gvjs_s(a.m,gvjs_mX),d=gvjs_4d(a.m,gvjs_7d,[],"zoomButtonsOrder",void 0,void 0),e=a.G;e.Ac(a.gb.oF);if(c)for(e.append(a.gb.oF,"Zoom: "),c=gvjs_cb(d),d=c.next();!d.done;d=c.next()){d=d.value;if(!a.m.nb(gvjs_pX+d))break;var f=gvjs_r(a.m,gvjs_pX+d+".className","zoomButton"),g=gvjs_r(a.m,gvjs_pX+d+".label",d);f=gvjs_ux(gvjs_iq,{type:gvjs_iq,id:b+"_"+d,"class":f,href:"#"},g);var h=gvjs_lw(e.hd,f);e.append(a.gb.oF,h);h=gvjs_Eka(a.gb.oF);var k=gvjs_k(gvjs_Uka(a,d),
a);gvjs_Qk(a,gvjs_x,gvjs_k(function(){this.aa.D(h,gvjs_Jq,k)},a))}}
function gvjs_Uka(a,b){var c=a.m.ea(gvjs_pX+b+".offset");if(c)var d=gvjs_IE(c);var e=a.m.nb(gvjs_pX+b+".range");return gvjs_k(function(){var f=this.Eh.getState();var g=f.range.end;null==g&&(g=this.qN.max);if(c&&null!=g){g=gvjs_DE(g,d);var h=this.qN.min;g=g.getTime()>h.getTime()?g:h;h={start:g}}else e&&(h=e);void 0!==h.start&&(f.range.start=h.start);void 0!==h.end&&(f.range.end=h.end);this.Eh.setState(f);gvjs_uX(this,this.Eh);gvjs_vX(this,!0)},a)}
gvjs_.Upa=function(a){a=gvjs_sX(this,a.row,a.column);this.Rd.dispatchEvent(gvjs_Lt,{row:a.row,column:a.column});var b;a=this.getSelection();0<a.length&&(b=a[0].row);gvjs_xX(this,b||void 0)};gvjs_.Vpa=function(a){var b=gvjs_sX(this,a.row,a.column);this.Rd.dispatchEvent(gvjs_Mt,{row:b.row,column:b.column});a=this.V.Wa().getProperty(a.row,this.oi,"dataRow");gvjs_xX(this,a)};
function gvjs_xX(a,b){for(var c=gvjs_ac,d=0;d<a.nE.length;d++)if(!a.cI[d]){var e=a.nE[d],f=e.properties.dataColumn,g=a.Jb[d%a.Jb.length];g&&g.color&&(g=g.color);var h=gvjs_s(a.m,gvjs_jX)?gvjs_ux(gvjs_Ra,{"class":"legend-dot",style:gvjs_ui({"background-color":g})}):gvjs_ac;c=gvjs_dw(c,gvjs_ux(gvjs_Zu,{style:gvjs_ui({color:g})},gvjs_dw(h,e.label)));null!=b&&gvjs_s(a.m,gvjs_kX,!0)&&(f=a.qa.getValue(b,f),null!==f&&(e=f,g=null,a.$q&&(g=gvjs_h(a.$q)?a.$q[d]:a.$q),g&&(e=g.ac(f)),(f=a.m.ob(gvjs_aX))&&(e+=
f),c=gvjs_dw(c,": ",e)));c=gvjs_dw(c,gvjs_yx("&nbsp;&nbsp;"))}if(null!=b){var k=a.qa.getValue(b,a.oi);k=a.oN.ac(k)}"oneRow"===a.Vka?(b=a.m.ea(gvjs_iX),b=!0===b?"|&nbsp;":!1===b?"&nbsp; &nbsp;":b.toString(),c=k?gvjs_dw(c,gvjs_yx(b),k):c):c=gvjs_dw(k?k:"",gvjs_yx("&nbsp;&nbsp;"),gvjs_ux("br"),c);gvjs_Ch(a.gb.ssa,c)}function gvjs_sX(a,b,c){var d=a.V.Wa();return{row:null!=b?d.getProperty(b,a.oi,"dataRow"):null,column:null!=c?d.ig(c,"dataColumn"):null}}
function gvjs_tX(a,b,c){return{row:null==b?null:a.Ri.rY(b),column:null==c?null:a.Ri.K9(c)}}gvjs_.Tpa=function(){this.Rd.dispatchEvent(gvjs_z);if(this.Vi&&!this.E$){var a=this.Vi.sf();if(a){var b;if((b=this.kv().getSelection())&&b.length){b=b[0];var c=b.column;b=!c||1>c?null:b}else b=null;b?(b=gvjs_sX(this,b.row,b.column),(b=gvjs_yX(this,b.row,b.column))?(c=this.Vi.Wa(),b=c.ca()-c.rY(this.$L[b.idx])-1,a.setSelection([{row:b}])):a.setSelection([])):a.setSelection([])}}};
function gvjs_yX(a,b,c){b=[String(b),String(c)].join();return a.zu[a.KU[b]]}function gvjs_Ska(a,b){var c=b.vW+","+b.Ds,d=b.idx;a.zu.push(b);a.KU[c]=d}
gvjs_.xqa=function(){var a=this.kv(),b=this.Vi.sf().getSelection()[0];if(b){this.E$=!0;var c=this.Vi.Wa();b=c.ca()-c.Wl(b.row)-1;var d=this.zu[this.$L[b]];b=gvjs_k(function(){var e=this.V.bd().hAxis.viewWindow,f=e&&e.min&&e.min.getTime()||-Infinity;e=e&&e.max&&e.max.getTime()||Infinity;var g=d.date.getTime(),h=gvjs_tX(this,d.vW,d.Ds);return g>=f&&g<=e?(a.setSelection([{row:h.row,column:h.column+1}]),this.E$=!1,!0):!1},this);b()||(c=gvjs_x,gvjs_ce(this.Ic,gvjs_Bp)&&(c=gvjs_Cp),gvjs_Qk(a,c,b),gvjs_Vka(this,
d.vW))}else a.setSelection([])};function gvjs_Vka(a,b){var c=a.qN.min.getTime(),d=a.qN.max.getTime(),e=a.V.bd().hAxis.viewWindow,f=e&&e.min&&e.min.getTime()||c;e=e&&e.max&&e.max.getTime()||d;b=a.qa.getValue(b,a.oi).getTime();f=e-f;b=Math.max(c,b-Math.round(f/2));d=Math.min(d,b+f);b=Math.max(c,d-f);a.setVisibleChartRange(new Date(b),new Date(d),!0)}function gvjs_uX(a,b){a.Tt?b.cE():b.draw()};gvjs_g(gvjs_Nf,gvjs_rX,void 0);gvjs_rX.prototype.clearChart=gvjs_rX.prototype.Qb;gvjs_rX.prototype.draw=gvjs_rX.prototype.draw;gvjs_rX.prototype.getContainer=gvjs_rX.prototype.getContainer;gvjs_rX.prototype.getSelection=gvjs_rX.prototype.getSelection;gvjs_rX.prototype.getVisibleChartRange=gvjs_rX.prototype.N9;gvjs_rX.prototype.setVisibleChartRange=gvjs_rX.prototype.setVisibleChartRange;gvjs_rX.prototype.showDataColumns=gvjs_rX.prototype.bfa;gvjs_rX.prototype.hideDataColumns=gvjs_rX.prototype.O$;
