var gvjs_uO="Invalid state: should be an array of values.",gvjs_vO="No valid DataTable received from draw()",gvjs_wO="Start and end points must be 2D",gvjs_xO="goog-combobox-active",gvjs_yO="goog-flat-button",gvjs_zO="goog-link-button",gvjs_AO="aside",gvjs_BO="belowStacked",gvjs_CO="blockIncrement",gvjs_DO="google-visualization-controls-rangefilter",gvjs_EO="month",gvjs_FO="placeholder",gvjs_GO="uichange",gvjs_HO="useFormattedValue",gvjs_IO="yy/MM/dd hh:mma";
gvjs_uC.prototype.pq=gvjs_B(54,function(a){this.zA=a});gvjs_HD.prototype.pq=gvjs_B(53,function(a){this.zA=a});gvjs_G.prototype.zg=gvjs_B(17,function(){return this.lh});function gvjs_JO(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];gvjs_vb(d)?gvjs_JO.apply(null,d):gvjs_H(d)}}function gvjs_KO(a){return new gvjs_C(a.offsetLeft,a.offsetTop)}function gvjs_LO(a){gvjs_G.call(this);this.ha=a;this.aa=new gvjs_jz(this)}gvjs_l(gvjs_LO,gvjs_G);gvjs_=gvjs_LO.prototype;
gvjs_.O=function(){this.clear();gvjs_LO.o.O.call(this)};gvjs_.clear=function(){this.aa.removeAll();gvjs_H(this.aa);gvjs_Nc(this.ha)};gvjs_.getContainer=function(){return this.ha};gvjs_.addEventListener=function(a,b,c,d,e){e?gvjs_kz(this.aa,a,b,c,d,e):this.aa.D(a,b,c,d)};gvjs_.draw=function(){};gvjs_.getState=function(){return{}};function gvjs_MO(a){gvjs_dz.call(this,a);this.c8=[]}gvjs_l(gvjs_MO,gvjs_dz);gvjs_=gvjs_MO.prototype;gvjs_.O=function(){this.clear();gvjs_MO.o.O.call(this)};gvjs_.clear=function(){this.kf()};
gvjs_.kf=function(){this.jL&&(gvjs_Sk(this.jL),gvjs_H(this.jL),this.jL=null);gvjs_H(this.Tc);this.Tc=null;gvjs_Nc(this.container)};gvjs_.qa=null;gvjs_.su=null;gvjs_.m=null;gvjs_.Tc=null;gvjs_.jL=null;gvjs_.t4=null;gvjs_.K=null;gvjs_.Iv=null;gvjs_.Wa=function(){return this.qa};gvjs_.bd=function(){return this.m};gvjs_.Kf=function(){return{}};gvjs_.Yl=function(a,b){return gvjs_Hw(b,"ui",{})};gvjs_.at=function(){return""};gvjs_.Mea=function(a){this.c8=a};gvjs_.sO=function(){return this.c8};gvjs_.gr=function(){};
gvjs_.getState=function(){return this.K?gvjs_Li(gvjs_Ji(this.K)):null};gvjs_.draw=function(a,b,c){gvjs_bz(a);this.qa=a;this.su=b||{};this.t4=c||{};gvjs_Xw(this.zo,this.HB,this)};
gvjs_.HB=function(){if(this.qa){this.K=this.t4||{};if(!gvjs_i(this.K))throw Error("Control state must be an object.");this.Iv=this.Iv||this.K;this.m=new gvjs__d([this.su,this.Kf()||{}]);this.gr(this.qa,this.m,this.K);if(!this.Tc){var a=gvjs_r(this.m,"ui.type",this.at());this.Tt&&(a=gvjs_Pm(a));this.Tc=(a=gvjs_Kk(a))?new a(this.container):null;if(!this.Tc)throw Error("Invalid Ui instance.");this.jL=gvjs_Mk(this.Tc,gvjs_GO,gvjs_k(this.lya,this))}this.Tc.draw(this.K,this.Yl(this.qa,this.m));this.K=this.Tc.getState();
gvjs_K(this,gvjs_x,null)}};gvjs_.lya=function(a){this.K=this.Tc.getState();gvjs_K(this,gvjs_4g,a)};gvjs_.St=function(){gvjs_Xw(this.zo,this.rva,this)};gvjs_.rva=function(){this.Iv&&(this.t4=this.Iv,this.HB())};
function gvjs_Fia(a){if(a.altKey&&!a.ctrlKey||a.metaKey||112<=a.keyCode&&123>=a.keyCode)return!1;if(gvjs_xz(a.keyCode))return!0;switch(a.keyCode){case 18:case 20:case 93:case 17:case 40:case 35:case 27:case 36:case 45:case 37:case 224:case 91:case 144:case 12:case 34:case 33:case 19:case 255:case 44:case 39:case 145:case 16:case 38:case 252:case 224:case 92:return!1;case 0:return!gvjs_mc;default:return 166>a.keyCode||183<a.keyCode}}function gvjs_NO(){gvjs_dj.call(this)}gvjs_l(gvjs_NO,gvjs_dj);
gvjs_=gvjs_NO.prototype;gvjs_.be=0;gvjs_.bp=0;gvjs_.An=100;gvjs_.Nl=0;gvjs_.uj=1;gvjs_.bl=!1;gvjs_.kz=!1;gvjs_.Va=function(a){a=gvjs_OO(this,a);this.be!=a&&(this.be=a+this.Nl>this.An?this.An-this.Nl:a<this.bp?this.bp:a,this.bl||this.kz||this.dispatchEvent(gvjs_rq))};gvjs_.getValue=function(){return gvjs_OO(this,this.be)};gvjs_.xS=function(a){a=gvjs_OO(this,a);this.Nl!=a&&(this.Nl=0>a?0:this.be+a>this.An?this.An-this.be:a,this.bl||this.kz||this.dispatchEvent(gvjs_rq))};
gvjs_.Ul=function(){var a=this.Nl;return null==this.uj?a:Math.round(a/this.uj)*this.uj};gvjs_.vw=function(a){if(this.bp!=a){var b=this.bl;this.bl=!0;this.bp=a;a+this.Nl>this.An&&(this.Nl=this.An-this.bp);a>this.be&&this.Va(a);a>this.An&&(this.Nl=0,this.eu(a),this.Va(a));(this.bl=b)||this.kz||this.dispatchEvent(gvjs_rq)}};gvjs_.uf=function(){return gvjs_OO(this,this.bp)};
gvjs_.eu=function(a){a=gvjs_OO(this,a);if(this.An!=a){var b=this.bl;this.bl=!0;this.An=a;a<this.be+this.Nl&&this.Va(a-this.Nl);a<this.bp&&(this.Nl=0,this.vw(a),this.Va(this.An));a<this.bp+this.Nl&&(this.Nl=this.An-this.bp);(this.bl=b)||this.kz||this.dispatchEvent(gvjs_rq)}};gvjs_.tf=function(){return gvjs_OO(this,this.An)};gvjs_.KH=function(){return this.uj};
gvjs_.JS=function(a){this.uj!=a&&(this.uj=a,a=this.bl,this.bl=!0,this.eu(this.tf()),this.xS(this.Ul()),this.Va(this.getValue()),(this.bl=a)||this.kz||this.dispatchEvent(gvjs_rq))};function gvjs_OO(a,b){return null==a.uj?b:a.bp+Math.round((b-a.bp)/a.uj)*a.uj}function gvjs_PO(){gvjs_GD.call(this);this.ir=[]}gvjs_l(gvjs_PO,gvjs_GD);gvjs_PO.prototype.add=function(a){gvjs_Hb(this.ir,a)||(this.ir.push(a),gvjs_I(a,gvjs_Nr,this.xca,!1,this))};
gvjs_PO.prototype.remove=function(a){gvjs_Yh(this.ir,a)&&gvjs_8i(a,gvjs_Nr,this.xca,!1,this)};gvjs_PO.prototype.O=function(){gvjs_m(this.ir,function(a){a.na()});this.ir.length=0;gvjs_PO.o.O.call(this)};function gvjs_QO(){gvjs_PO.call(this);this.tX=0}gvjs_l(gvjs_QO,gvjs_PO);
gvjs_QO.prototype.play=function(a){if(0==this.ir.length)return!1;if(a||0==this.K)this.tX=0,this.xJ();else if(this.Uo())return!1;this.Qh("play");-1==this.K&&this.Qh("resume");var b=-1==this.K&&!a;this.startTime=gvjs_zb();this.endTime=null;this.K=1;gvjs_m(this.ir,function(c){b&&-1!=c.K||c.play(a)});return!0};gvjs_QO.prototype.pause=function(){this.Uo()&&(gvjs_m(this.ir,function(a){a.Uo()&&a.pause()}),this.K=-1,this.Qh("pause"))};
gvjs_QO.prototype.stop=function(a){gvjs_m(this.ir,function(b){0==b.K||b.stop(a)});this.K=0;this.endTime=gvjs_zb();this.Qh(gvjs_4u);this.sz()};gvjs_QO.prototype.xca=function(){this.tX++;this.tX==this.ir.length&&(this.endTime=gvjs_zb(),this.K=0,this.Qh(gvjs_Nr),this.sz())};function gvjs_RO(a,b,c,d,e){gvjs_HD.call(this,b,c,d,e);this.element=a}gvjs_l(gvjs_RO,gvjs_HD);gvjs_=gvjs_RO.prototype;gvjs_.yA=gvjs_tb;gvjs_.uh=function(){void 0===this.mr&&(this.mr=gvjs_Sy(this.element));return this.mr};
gvjs_.n0=function(){this.yA();gvjs_RO.o.n0.call(this)};gvjs_.sz=function(){this.yA();gvjs_RO.o.sz.call(this)};gvjs_.xJ=function(){this.yA();gvjs_RO.o.xJ.call(this)};function gvjs_SO(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error(gvjs_wO);gvjs_RO.call(this,a,b,c,d,e)}gvjs_l(gvjs_SO,gvjs_RO);gvjs_SO.prototype.yA=function(){var a=this.zA&&this.uh()?gvjs_y:gvjs_Eg;this.element.style[a]=Math.round(this.coords[0])+gvjs_Y;this.element.style.top=Math.round(this.coords[1])+gvjs_Y};
function gvjs_TO(a,b,c,d,e){gvjs_RO.call(this,a,[b],[c],d,e)}gvjs_l(gvjs_TO,gvjs_RO);gvjs_TO.prototype.yA=function(){this.element.style.width=Math.round(this.coords[0])+gvjs_Y};function gvjs_UO(a,b,c,d,e){gvjs_RO.call(this,a,[b],[c],d,e)}gvjs_l(gvjs_UO,gvjs_RO);gvjs_UO.prototype.yA=function(){this.element.style.height=Math.round(this.coords[0])+gvjs_Y};
function gvjs_VO(a,b){gvjs_KB.call(this,a);this.w5=null;this.Xe=new gvjs_NO;this.isa=b||gvjs_bi;this.Jna=!0;gvjs_I(this.Xe,gvjs_rq,this.t$,!1,this)}gvjs_l(gvjs_VO,gvjs_KB);gvjs_=gvjs_VO.prototype;gvjs_.rb=gvjs_X;gvjs_.BP=!1;gvjs_.X_=!1;gvjs_.Km=10;gvjs_.CQ=0;gvjs_.xaa=!0;gvjs_.Wba=0;gvjs_.via=1E3;gvjs_.vg=!0;gvjs_.Ol=!1;gvjs_.J=function(){gvjs_VO.o.J.call(this);var a=this.xa().J(gvjs_v,this.ra(this.rb));this.Gf(a)};
gvjs_.Gf=function(a){gvjs_VO.o.Gf.call(this,a);gvjs_wB(a,this.ra(this.rb));a=this.j();var b=this.xa().J(gvjs_v,"google-visualization-controls-slider-handle");gvjs_oz(b,gvjs_iq);this.KB=b;a.appendChild(this.KB);this.Nd=gvjs_WO(this);a.appendChild(this.Nd);this.cj=gvjs_WO(this);a.appendChild(this.cj);a=this.j();gvjs_oz(a,"slider");gvjs_XO(this)};
gvjs_.Mb=function(){gvjs_VO.o.Mb.call(this);this.Fm=new gvjs_uC(this.Nd);this.qq=new gvjs_uC(this.cj);this.Fm.pq(this.Ol);this.qq.pq(this.Ol);this.Fm.Ox=this.qq.Ox=gvjs_tb;this.Rf=new gvjs_CB(this.j());gvjs_YO(this,!0);this.j().tabIndex=0;gvjs_ZO(this)};
function gvjs_YO(a,b){b?(a.jc().D(a.Fm,gvjs_3p,a.SO).D(a.qq,gvjs_3p,a.SO).D(a.Fm,[gvjs_Z,gvjs_W],a.yv).D(a.qq,[gvjs_Z,gvjs_W],a.yv).D(a.Rf,gvjs_Rs,a.tn).D(a.j(),gvjs_Jq,a.VO).D(a.j(),gvjs_Kg,a.VO),a.xaa&&gvjs__O(a,!0)):(a.jc().zb(a.Fm,gvjs_3p,a.SO).zb(a.qq,gvjs_3p,a.SO).zb(a.Fm,[gvjs_Z,gvjs_W],a.yv).zb(a.qq,[gvjs_Z,gvjs_W],a.yv).zb(a.Rf,gvjs_Rs,a.tn).zb(a.j(),gvjs_Jq,a.VO).zb(a.j(),gvjs_Kg,a.VO),a.xaa&&gvjs__O(a,!1))}gvjs_.Re=function(){gvjs_VO.o.Re.call(this);gvjs_JO(this.Fm,this.qq,this.Rf,this.Bn)};
gvjs_.SO=function(a){var b=a.WW==this.Fm?this.Nd:this.cj;if(this.rb==gvjs__){var c=this.j().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.tf()-this.uf())+this.uf()}else c=this.j().clientWidth-b.offsetWidth,c=a.left/c*(this.tf()-this.uf())+this.uf();c=a.WW==this.Fm?Math.min(Math.max(c,this.uf()),this.getValue()+this.Ul()):Math.min(Math.max(c,this.getValue()),this.tf());gvjs_0O(this,b,c)};
gvjs_.yv=function(a){var b=a.type==gvjs_Z;gvjs_AB(this.j(),"goog-slider-dragging",b);gvjs_AB(a.target.oC,"goog-slider-thumb-dragging",b);a=a.WW==this.Fm;b?(this.dispatchEvent("e"),this.dispatchEvent(a?"a":"c")):(this.dispatchEvent("f"),this.dispatchEvent(a?"b":"d"))};
gvjs_.tn=function(a){var b=!0;switch(a.keyCode){case 36:gvjs_1O(this,this.uf());break;case 35:gvjs_1O(this,this.tf());break;case 33:gvjs_2O(this,this.Km);break;case 34:gvjs_2O(this,-this.Km);break;case 37:var c=this.Ol&&this.uh()?1:-1;gvjs_2O(this,a.shiftKey?c*this.Km:c*this.vA);break;case 40:gvjs_2O(this,a.shiftKey?-this.Km:-this.vA);break;case 39:c=this.Ol&&this.uh()?-1:1;gvjs_2O(this,a.shiftKey?c*this.Km:c*this.vA);break;case 38:gvjs_2O(this,a.shiftKey?this.Km:this.vA);break;default:b=!1}b&&a.preventDefault()};
gvjs_.VO=function(a){this.Jna&&this.j().focus&&this.j().focus();var b=a.target;gvjs_Xc(this.Nd,b)||gvjs_Xc(this.cj,b)||(b=a.type==gvjs_Jq,b&&gvjs_zb()<this.Wba+this.via||(b||(this.Wba=gvjs_zb()),this.X_?gvjs_1O(this,gvjs_3O(this,a)):(this.p3(a),this.Vn=gvjs_4O(this,gvjs_3O(this,a)),this.daa=this.rb==gvjs__?this.Zy<this.Vn.offsetTop:this.Zy>gvjs_5O(this,this.Vn)+this.Vn.offsetWidth,a=gvjs_Fc(this.j()),this.jc().D(a,gvjs_Qg,this.n3,!0).D(this.j(),gvjs_Ng,this.p3),this.Hv||(this.Hv=new gvjs_az(200),
this.jc().D(this.Hv,gvjs_nv,this.z$)),this.z$(),this.Hv.start())))};gvjs_.p$=function(a){gvjs_2O(this,(0<a.detail?-1:1)*this.vA);a.preventDefault()};
gvjs_.z$=function(){var a;if(this.rb==gvjs__){var b=this.Zy,c=this.Vn.offsetTop;this.daa?b<c&&(a=gvjs_6O(this,this.Vn)+this.Km):b>c+this.Vn.offsetHeight&&(a=gvjs_6O(this,this.Vn)-this.Km)}else b=this.Zy,c=gvjs_5O(this,this.Vn),this.daa?b>c+this.Vn.offsetWidth&&(a=gvjs_6O(this,this.Vn)+this.Km):b<c&&(a=gvjs_6O(this,this.Vn)-this.Km);void 0!==a&&gvjs_0O(this,this.Vn,a)};gvjs_.n3=function(){this.Hv&&this.Hv.stop();var a=gvjs_Fc(this.j());this.jc().zb(a,gvjs_Qg,this.n3,!0).zb(this.j(),gvjs_Ng,this.p3)};
function gvjs_7O(a,b){b=gvjs_My(b,a.j());return a.rb==gvjs__?b.y:a.Ol&&a.uh()?a.j().clientWidth-b.x:b.x}gvjs_.p3=function(a){this.Zy=gvjs_7O(this,a)};function gvjs_3O(a,b){var c=a.uf(),d=a.tf();if(a.rb==gvjs__){var e=a.Nd.offsetHeight,f=a.j().clientHeight-e;a=gvjs_7O(a,b)-e/2;return(d-c)*(f-a)/f+c}e=a.Nd.offsetWidth;f=a.j().clientWidth-e;a=gvjs_7O(a,b)-e/2;return(d-c)*a/f+c}
function gvjs_6O(a,b){if(b==a.Nd)return a.Xe.getValue();if(b==a.cj)return a.Xe.getValue()+a.Xe.Ul();throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function gvjs_2O(a,b){Math.abs(b)<a.KH()&&(b=gvjs_Jx(b)*a.KH());var c=gvjs_6O(a,a.Nd)+b;b=gvjs_6O(a,a.cj)+b;c=gvjs_Cc(c,a.uf(),a.tf()-a.CQ);b=gvjs_Cc(b,a.uf()+a.CQ,a.tf());gvjs_8O(a,c,b-c)}
function gvjs_0O(a,b,c){var d=gvjs_OO(a.Xe,c);c=b==a.Nd?d:a.Xe.getValue();b=b==a.cj?d:a.Xe.getValue()+a.Xe.Ul();c>=a.uf()&&b>=c+a.CQ&&a.tf()>=b&&gvjs_8O(a,c,b-c)}function gvjs_8O(a,b,c){a.uf()<=b&&b<=a.tf()-c&&a.CQ<=c&&c<=a.tf()-b&&(b!=a.getValue()||c!=a.Ul())&&(a.Xe.kz=!0,a.Xe.xS(0),a.Xe.Va(b),a.Xe.xS(c),a.Xe.kz=!1,a.t$(null))}gvjs_.uf=function(){return this.Xe.uf()};gvjs_.vw=function(a){this.Xe.vw(a)};gvjs_.tf=function(){return this.Xe.tf()};gvjs_.eu=function(a){this.Xe.eu(a)};
function gvjs_4O(a,b){return b<=a.Xe.getValue()+a.Xe.Ul()/2?a.Nd:a.cj}gvjs_.t$=function(){gvjs_ZO(this);gvjs_XO(this);this.dispatchEvent(gvjs_rq)};
function gvjs_ZO(a){if(a.Nd&&!a.BP){var b=gvjs_9O(a,gvjs_6O(a,a.Nd)),c=gvjs_9O(a,gvjs_6O(a,a.cj));if(a.rb==gvjs__)a.Nd.style.top=b.y+gvjs_Y,a.cj.style.top=c.y+gvjs_Y,a.Eg&&(b=gvjs_$O(c.y,b.y,a.Nd.offsetHeight),a.Eg.style.top=b.offset+gvjs_Y,a.Eg.style.height=b.size+gvjs_Y);else{var d=a.Ol&&a.uh()?gvjs_y:gvjs_Eg;a.Nd.style[d]=b.x+gvjs_Y;a.cj.style[d]=c.x+gvjs_Y;a.Eg&&(b=gvjs_$O(b.x,c.x,a.Nd.offsetWidth),a.Eg.style[d]=b.offset+gvjs_Y,a.Eg.style.width=b.size+gvjs_Y)}}}
function gvjs_$O(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}function gvjs_9O(a,b){var c=new gvjs_C;if(a.Nd){var d=a.uf(),e=a.tf();b=b==d&&d==e?0:(b-d)/(e-d);a.rb==gvjs__?(d=a.Nd.offsetHeight,d=a.j().clientHeight-d,b=Math.round(b*d),c.x=a.X_?0:gvjs_5O(a,a.Nd),c.y=d-b):(d=a.j().clientWidth-a.Nd.offsetWidth,c.x=Math.round(b*d),c.y=a.X_?0:a.Nd.offsetTop)}return c}
function gvjs_1O(a,b){b=gvjs_Cc(b,a.uf(),a.tf());a.BP&&(a.JG.stop(!0),a.JG.na());var c=new gvjs_QO,d=gvjs_4O(a,b),e=a.getValue(),f=a.Ul(),g=gvjs_6O(a,d),h=gvjs_9O(a,g);var k=a.KH();Math.abs(b-g)<k&&(b=gvjs_Cc(g+(b>g?k:-k),a.uf(),a.tf()));gvjs_0O(a,d,b);g=gvjs_9O(a,gvjs_6O(a,d));k=a.rb==gvjs__?[gvjs_5O(a,d),g.y]:[g.x,d.offsetTop];h=new gvjs_SO(d,[h.x,h.y],k,100);h.pq(a.Ol);c.add(h);a.Eg&&gvjs_Gia(a,d,e,f,g,c);a.w5&&(b=a.w5.bCa(e,b,100),gvjs_m(b,function(l){c.add(l)}));a.JG=c;a.jc().D(c,gvjs_W,a.ina);
a.BP=!0;c.play(!1)}
function gvjs_Gia(a,b,c,d,e,f){var g=gvjs_9O(a,c),h=gvjs_9O(a,c+d);c=g;d=h;b==a.Nd?c=e:d=e;a.rb==gvjs__?(b=gvjs_$O(h.y,g.y,a.Nd.offsetHeight),g=gvjs_$O(d.y,c.y,a.Nd.offsetHeight),e=new gvjs_SO(a.Eg,[gvjs_5O(a,a.Eg),b.offset],[gvjs_5O(a,a.Eg),g.offset],100),b=new gvjs_UO(a.Eg,b.size,g.size,100),e.pq(a.Ol),b.pq(a.Ol),f.add(e),f.add(b)):(b=gvjs_$O(g.x,h.x,a.Nd.offsetWidth),g=gvjs_$O(c.x,d.x,a.Nd.offsetWidth),e=new gvjs_SO(a.Eg,[b.offset,a.Eg.offsetTop],[g.offset,a.Eg.offsetTop],100),b=new gvjs_TO(a.Eg,
b.size,g.size,100),e.pq(a.Ol),b.pq(a.Ol),f.add(e),f.add(b))}gvjs_.ina=function(){this.BP=!1;this.dispatchEvent("g")};gvjs_.setOrientation=function(a){if(this.rb!=a){var b=this.ra(this.rb),c=this.ra(a);this.rb=a;this.j()&&(a=this.j(),gvjs_vB(a,b)&&(gvjs_yB(a,b),gvjs_wB(a,c)),b=this.Ol&&this.uh()?gvjs_y:gvjs_Eg,this.Nd.style[b]=this.Nd.style.top="",this.cj.style[b]=this.cj.style.top="",this.Eg&&(this.Eg.style[b]=this.Eg.style.top="",this.Eg.style.width=this.Eg.style.height=""),gvjs_ZO(this))}};
gvjs_.vi=function(){return this.rb};gvjs_.O=function(){gvjs_VO.o.O.call(this);this.Hv&&this.Hv.na();delete this.Hv;this.JG&&this.JG.na();delete this.JG;delete this.Nd;delete this.cj;this.Eg&&delete this.Eg;this.Xe.na();delete this.Xe;this.Rf&&(this.Rf.na(),delete this.Rf);this.Bn&&(this.Bn.na(),delete this.Bn);this.Fm&&(this.Fm.na(),delete this.Fm);this.qq&&(this.qq.na(),delete this.qq)};gvjs_.vA=1;gvjs_.KH=function(){return this.Xe.KH()};gvjs_.JS=function(a){this.Xe.JS(a)};gvjs_.getValue=function(){return this.Xe.getValue()};
gvjs_.Va=function(a){gvjs_0O(this,this.Nd,a)};gvjs_.Ul=function(){return this.Xe.Ul()};gvjs_.xS=function(a){gvjs_0O(this,this.cj,this.Xe.getValue()+a)};gvjs_.setVisible=function(a){gvjs_4(this.j(),a);a&&gvjs_ZO(this)};function gvjs_XO(a){var b=a.j();b&&(gvjs_pz(b,"valuemin",a.uf()),gvjs_pz(b,"valuemax",a.tf()),gvjs_pz(b,"valuenow",a.getValue()),gvjs_pz(b,"valuetext",a.isa(a.getValue())||""))}
function gvjs__O(a,b){b?(a.Bn||(a.Bn=new gvjs_xD(a.j())),a.jc().D(a.Bn,gvjs_yt,a.p$,{passive:!1})):a.jc().zb(a.Bn,gvjs_yt,a.p$,{passive:!1})}gvjs_.Fb=function(a){this.vg!=a&&this.dispatchEvent(a?gvjs_tr:gvjs_lr)&&(this.vg=a,gvjs_YO(this,a),a||this.n3(),gvjs_AB(this.j(),"goog-slider-disabled",!a))};gvjs_.isEnabled=function(){return this.vg};function gvjs_5O(a,b){return a.Ol?gvjs_Hz(b):b.offsetLeft}var gvjs_Hia={ML:gvjs__,IL:gvjs_X};function gvjs_aP(a,b){this.zya=a;this.lf=b}
gvjs_aP.prototype.getUrl=function(){return this.zya};gvjs_aP.prototype.Td=function(a){return this.lf[a].id};gvjs_aP.prototype.Y=function(a){return this.lf[a].type};gvjs_aP.prototype.$=function(){return this.lf.length};function gvjs_Iia(a,b){var c=new gvjs_Xl(a);c.kl("limit 1");c.send(function(d){if(d.bk())b(null);else{var e=[];d=d.Wa();for(var f=0;f<d.$();f++)e.push({id:d.Td(f),type:d.Y(f)});b(new gvjs_aP(a,e))}})};function gvjs_bP(a,b){this.Th=[];this.V=a;this.Sda=b||null;this.Qaa=(this.Sda||this.V.Wa()).Y(0)==gvjs_Qa?"second":gvjs_Pa}var gvjs_cP=["year",gvjs_EO,"day","hour","minute","second"],gvjs_dP=[function(a){return a.getFullYear()},function(a){return a.getMonth()+1},function(a){return a.getDate()},function(a){return a.getHours()},function(a){return a.getMinutes()},function(a){return a.getSeconds()}],gvjs_Jia=[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ca,gvjs_xa,gvjs_va,gvjs_ja];
function gvjs_Kia(a,b){function c(e){b(new gvjs_bP(a,e))}if(a.Wa())c(null);else{var d=a.Ae;if(d)gvjs_Iia(d,c);else throw Error("Wrapper should hold dataTable or dataSourceUrl");}}function gvjs_Lia(a,b){var c=gvjs_xn||gvjs_xn;b=b||function(f){return f};for(var d=[],e=1;e<a.$();e++)d.push({column:e,aggregation:c,type:a.Y(e),label:a.Fa(e),id:a.Td(e)});return gvjs_An(a,[{column:0,modifier:b,type:gvjs_c,label:a.Fa(0),id:a.Td(0)}],d)}
gvjs_bP.prototype.IF=function(){var a=this.V.Kr();a=new gvjs_O(a);var b=a.Wa();if(null!=b){for(var c=this.Th,d=0;d<b.ca();d++){a:{var e=this.Th;for(var f=b.getValue(d,0),g=0;g<e.length;g++){var h=e[g];gvjs_cP[g]==gvjs_EO&&h++;if(gvjs_dP[g](f)!=h){e=!1;break a}}e=!0}e||(b.Jz(d),d--)}b=gvjs_Lia(b,gvjs_dP[c.length]);a.ah(b)}else{b=this.Sda;b.Y(0)==gvjs_Pa&&(this.Qaa="day");c="select "+gvjs_eP(this)+"("+b.Td(0)+")";gvjs_eP(this)==gvjs_EO&&(c+=" + 1");for(d=1;d<b.$();d++)c+=", sum("+b.Td(d)+")";b=[c,gvjs_Mia(this,
b),"group by "+gvjs_eP(this)+"("+b.Td(0)+")",gvjs_Nia(this,b)].join(" ");a.kl(b)}return a};gvjs_bP.prototype.NN=function(a){var b=gvjs_eP(this);if(b==this.Qaa)return!1;b==gvjs_EO&&a--;this.Th.push(a);return!0};gvjs_bP.prototype.rollup=function(){return 0<this.Th.length?(this.Th.pop(),!0):!1};function gvjs_eP(a){return gvjs_cP[a.Th.length]}
function gvjs_Oia(a){var b=[];0<a.Th.length&&b.push(String(a.Th[0]));if(1<a.Th.length){var c=a.Th[1];c=gvjs_Jia[c];b.push(String(c))}2<a.Th.length&&b.push(String(a.Th[2]));3<a.Th.length&&(c=a.Th[3],a=a.Th[4]||"00",a=String(a),1==a.length&&(a="0"+a),b.push(c+":"+a));return b.join(" ")}function gvjs_Mia(a,b){if(0==a.Th.length)return"";for(var c=[],d=0;d<a.Th.length;d++)c.push(gvjs_cP[d]+"("+b.Td(0)+") = "+a.Th[d]);return"where "+c.join(gvjs_Dn)}
function gvjs_Nia(a,b){b="order by "+gvjs_eP(a)+"("+b.Td(0)+")";gvjs_eP(a)==gvjs_EO&&(b+=" + 1");return b};function gvjs_fP(a){this.ha=a}gvjs_=gvjs_fP.prototype;gvjs_.Vm=null;gvjs_.V=null;gvjs_.draw=function(a){var b=this;gvjs_Kia(a,function(c){b.Vm=c;b.xA()})};gvjs_.rollup=function(){null!=this.Vm&&null!=this.V&&this.Vm.rollup()&&this.xA()};gvjs_.NN=function(a){(a=this.Vm.NN(a))&&this.xA();return a};gvjs_.yqa=function(){var a=this.V.sf().getSelection()[0].row;a=this.V.FO().Wa().getValue(a,0);this.NN(a)};
gvjs_.xA=function(){this.V&&gvjs_Tk(this.V);var a=this.V=this.Vm.IF(),b=this.V,c=b.getOption(gvjs_ns)||{};c.title=gvjs_eP(this.Vm);b.Z(gvjs_ns,c);b.Z(gvjs_pv,gvjs_Oia(this.Vm));a.Z(gvjs_xg,!0);b=gvjs_k(this.yqa,this);gvjs_Mk(a,gvjs_z,b);a.draw(this.ha)};function gvjs_gP(a){gvjs_MO.call(this,a)}gvjs_l(gvjs_gP,gvjs_MO);gvjs_gP.prototype.IF=function(){return this.apply()};gvjs_gP.prototype.apply=function(){if(!this.Wa())throw Error(gvjs_vO);return this.P5(this.Wa(),this.bd(),this.getState())};gvjs_gP.prototype.P5=function(a){return a};function gvjs_hP(a){gvjs_MO.call(this,a)}gvjs_l(gvjs_hP,gvjs_gP);gvjs_hP.prototype.Vm=null;gvjs_hP.prototype.P5=function(a,b,c){a=c.targetValue;"drilldown"==c.action?typeof a===gvjs_c&&this.Vm.NN(a):this.Vm.rollup();c=this.Vm.IF().Wa();if(null==c)throw"Operator could not be applied to null data table.";return c};gvjs_hP.prototype.at=function(){return"DrilldownOperatorUi"};gvjs_hP.prototype.gr=function(a){this.clear();this.Vm=new gvjs_bP(new gvjs_O({Kb:a}))};
function gvjs_iP(a){gvjs_LO.call(this,a)}gvjs_l(gvjs_iP,gvjs_LO);gvjs_iP.prototype.Of=null;gvjs_iP.prototype.getState=function(){if(!this.Of)return{};var a=this.Of?this.Of.value:"{}";try{a=gvjs_Ud(a)}catch(b){}return a=gvjs_i(a)?a:{}};gvjs_iP.prototype.draw=function(a){this.Of=this.hW(a);this.getContainer().appendChild(this.Of)};
gvjs_iP.prototype.hW=function(a){var b=this,c=gvjs_E(gvjs_oa);c.setAttribute(gvjs_zg,gvjs_th(this.getContainer())+"-input");a&&(c.value=gvjs_Vd(a));this.addEventListener(c,gvjs_8p,function(){gvjs_K(b,gvjs_GO,null)},!1);return c};function gvjs_jP(a){gvjs_MO.call(this,a);this.MS=[]}gvjs_l(gvjs_jP,gvjs_MO);gvjs_jP.prototype.gr=function(){this.clear();this.MS=this.bd().ea("setters")||[]};gvjs_jP.prototype.apply=function(){return this.PU(this.Wa(),this.bd(),this.getState())};gvjs_jP.prototype.PU=function(a,b,c){gvjs_m(this.sO(),function(d){gvjs_m(this.MS,function(e){d.setProperty(e.output,c[e.input])},this)},this);return a};function gvjs_kP(a){gvjs_jP.call(this,a)}gvjs_l(gvjs_kP,gvjs_jP);gvjs_=gvjs_kP.prototype;gvjs_.Xa=null;gvjs_.Bb=null;gvjs_.Yl=function(a,b){a=gvjs_kP.o.Yl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label="");return a};gvjs_.gr=function(a,b,c){this.Xa=gvjs_t(b,gvjs_Ig);this.Bb=gvjs_t(b,gvjs_Hg);this.MS=[{input:"lowValue",mg:gvjs_r(b,"lowKey")},{input:"highValue",mg:gvjs_r(b,"highKey")}];this.wL(c)};
gvjs_.wL=function(a){if(a.lowThumbAtMinimum)a.lowValue=this.Xa;else{var b=gvjs_gc(String(a.lowValue));isNaN(b)&&(b=Number.NEGATIVE_INFINITY);a.lowValue=gvjs_Cc(b,this.Xa,this.Bb)}a.highThumbAtMaximum?a.highValue=this.Bb:(b=gvjs_gc(String(a.highValue)),isNaN(b)&&(b=Number.POSITIVE_INFINITY),a.highValue=gvjs_Cc(b,this.Xa,this.Bb))};function gvjs_lP(a){gvjs_MO.call(this,a)}gvjs_l(gvjs_lP,gvjs_MO);gvjs_lP.prototype.VA=function(){return this.apply()};gvjs_lP.prototype.apply=function(){if(!this.Wa())throw Error(gvjs_vO);return this.HF(this.Wa(),this.bd(),this.getState())};gvjs_lP.prototype.HF=function(a){return new gvjs_N(a)};function gvjs_mP(a){gvjs_MO.call(this,a);this.De=-1}gvjs_l(gvjs_mP,gvjs_lP);gvjs_=gvjs_mP.prototype;gvjs_.sq=null;gvjs_.Xa=null;gvjs_.Bb=null;gvjs_.ES=function(a){this.Xa=a};gvjs_.DS=function(a){this.Bb=a};function gvjs_nP(a,b){if(b.lowThumbAtMinimum)b.lowValue=a.Xa;else{var c=a.y4(b.lowValue);isNaN(c)&&(c=Number.NEGATIVE_INFINITY);b.lowValue=gvjs_Cc(c,a.Xa,a.Bb)}b.highThumbAtMaximum?b.highValue=a.Bb:(c=a.y4(b.highValue),isNaN(c)&&(c=Number.POSITIVE_INFINITY),b.highValue=gvjs_Cc(c,a.Xa,a.Bb))}
gvjs_.HF=function(a,b,c){a=new gvjs_N(a);b={column:this.De,test:this.dY(b,c.lowValue.valueOf(),c.highValue.valueOf())};a.vp(a.$B([b]));return a};gvjs_.dY=function(a,b,c){return function(d){return b<=d&&c>=d}};function gvjs_oP(a){gvjs_VO.call(this,a)}gvjs_l(gvjs_oP,gvjs_VO);gvjs_oP.prototype.KB=null;gvjs_oP.prototype.ra=function(a){return a==gvjs__?"google-visualization-controls-slider-vertical":"google-visualization-controls-slider-horizontal"};gvjs_oP.prototype.Mb=function(){gvjs_oP.o.Mb.call(this);this.jc().D(this,gvjs_rq,gvjs_k(this.uga,this));this.uga()};
gvjs_oP.prototype.uga=function(){var a=gvjs_KO(this.Nd),b=gvjs_KO(this.cj);this.vi()==gvjs__?(this.KB.style.height=gvjs_Dy(Math.abs(b.y-a.y),!0),this.KB.style.top=Math.min(b.y,a.y)+gvjs_Y):(gvjs_Ny(this.KB,Math.abs(b.x-a.x)),this.KB.style.left=Math.min(b.x,a.x)+gvjs_Y)};function gvjs_WO(a){a=a.xa().J(gvjs_v,"google-visualization-controls-slider-thumb");gvjs_oz(a,gvjs_iq);return a};function gvjs_pP(a){gvjs_LO.call(this,a);this.Pp=this.Am=0}gvjs_l(gvjs_pP,gvjs_LO);gvjs_=gvjs_pP.prototype;gvjs_.O=function(){gvjs_H(this.Am);gvjs_H(this.Lc);gvjs_pP.o.O.call(this)};gvjs_.Vv=null;gvjs_.Ev=null;gvjs_.Lc=null;gvjs_.getState=function(){if(!this.Lc)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var a=this.Lc.getValue(),b=this.Lc.Ul();return{lowValue:a+this.Pp,highValue:a+b+this.Pp,lowThumbAtMinimum:a===this.Lc.uf(),highThumbAtMaximum:a+b===this.Lc.tf()}};
function gvjs_qP(){return gvjs_E(gvjs_af,{"class":"google-visualization-controls-rangefilter-thumblabel"},"-")}gvjs_.gxa=function(){this.o4();this.Am&&gvjs__k(this.Am);this.Am=gvjs_Zk(function(){this.Am=0;gvjs_K(this,gvjs_GO,null)},200,this)};
function gvjs_rP(a,b,c,d,e){var f=gvjs_s(d,"showRangeValues");e=gvjs_r(d,gvjs_Pt,e.orientation,gvjs_Hia);var g=new gvjs_KB;b.Ha(g,!0);gvjs_wB(g.j(),gvjs_R);f&&(e===gvjs_X?(a.Vv=gvjs_qP(),g.ib().appendChild(a.Vv)):(a.Ev=gvjs_qP(),g.ib().appendChild(a.Ev)));b=new gvjs_oP;gvjs_H(a.Lc);a.Lc=b;a.Vea(d);b=a.jY(d,gvjs_Ig);var h=a.jY(d,gvjs_Hg);if(null==b||null==h)throw Error("minValue and maxValue must be specified");c=a.sda(b,h,c);b=c.minValue;h=c.maxValue;c=c.state;a.Pp=b;h-=a.Pp;c.lowValue-=a.Pp;c.highValue-=
a.Pp;a.Lc.vw(0);a.Lc.eu(h);a.Lc.setOrientation(e);b=c.lowThumbAtMinimum?a.Lc.uf():c.lowValue;gvjs_8O(a.Lc,b,c.highThumbAtMaximum?a.Lc.tf():c.highValue-b);g.Ha(a.Lc,!0);f&&(e==gvjs_X?(a.Ev=gvjs_qP(),g.ib().appendChild(a.Ev)):(a.Vv=gvjs_qP(),g.ib().appendChild(a.Vv)),a.V0&&a.V0(d),a.o4());a.addEventListener(a.Lc,gvjs_rq,a.gxa,!1,a)};function gvjs_sP(a){gvjs_dj.call(this);this.Sc=null;this.H=a;a=gvjs_q||gvjs_lc||gvjs_nc&&!gvjs_yc("531")&&a.tagName==gvjs_9o;this.aa=new gvjs_jz(this);this.aa.D(this.H,a?[gvjs_Ss,"paste","cut","drop",gvjs_Ks]:gvjs_Ks,this)}gvjs_l(gvjs_sP,gvjs_dj);
gvjs_sP.prototype.handleEvent=function(a){if(a.type==gvjs_Ks)gvjs_q&&gvjs_yc(10)&&0==a.keyCode&&0==a.charCode||(gvjs_tP(this),this.dispatchEvent(gvjs_uP(a)));else if(a.type!=gvjs_Ss||gvjs_Fia(a)){var b=a.type==gvjs_Ss?this.H.value:null;gvjs_q&&229==a.keyCode&&(b=null);var c=gvjs_uP(a);gvjs_tP(this);this.Sc=gvjs_Zk(function(){this.Sc=null;this.H.value!=b&&this.dispatchEvent(c)},0,this)}};function gvjs_tP(a){null!=a.Sc&&(gvjs__k(a.Sc),a.Sc=null)}
function gvjs_uP(a){a=new gvjs_Ui(a.si);a.type=gvjs_Ks;return a}gvjs_sP.prototype.O=function(){gvjs_sP.o.O.call(this);this.aa.na();gvjs_tP(this);delete this.H};function gvjs_vP(a,b,c){gvjs_Si.call(this,a,b);this.item=c}gvjs_l(gvjs_vP,gvjs_Si);function gvjs_wP(a,b){gvjs_KB.call(this,b);this.Tb=a||""}var gvjs_xP;gvjs_l(gvjs_wP,gvjs_KB);gvjs_=gvjs_wP.prototype;gvjs_.rq=null;gvjs_.ksa=10;function gvjs_yP(){null==gvjs_xP&&(gvjs_xP=gvjs_FO in gvjs_Ei(gvjs_oa));return gvjs_xP}gvjs_.tC=!1;gvjs_.J=function(){this.H=this.xa().J(gvjs_oa,{type:gvjs_A})};
gvjs_.Gf=function(a){gvjs_wP.o.Gf.call(this,a);this.Tb||(this.Tb=a.getAttribute(gvjs_Cg)||"");gvjs_7v(gvjs_Fc(a))==a&&(this.tC=!0,a=this.j(),gvjs_yB(a,this.JI));gvjs_yP()&&(this.j().placeholder=this.Tb);a=this.j();gvjs_pz(a,gvjs_Cg,this.Tb)};
gvjs_.Mb=function(){gvjs_wP.o.Mb.call(this);var a=new gvjs_jz(this);a.D(this.j(),gvjs_Qr,this.k$);a.D(this.j(),gvjs_8p,this.TO);if(gvjs_yP())this.aa=a;else{gvjs_mc&&a.D(this.j(),[gvjs_Bg,gvjs_Ss,gvjs_Ts],this.Epa);var b=gvjs_Fc(this.j());a.D(gvjs_kw(b),"load",this.Lqa);this.aa=a;gvjs_zP(this)}this.os();this.j().lj=this};gvjs_.Re=function(){gvjs_wP.o.Re.call(this);this.aa&&(this.aa.na(),this.aa=null);this.j().lj=null};
function gvjs_zP(a){!a.Qna&&a.aa&&a.j().form&&(a.aa.D(a.j().form,"submit",a.Fpa),a.Qna=!0)}gvjs_.O=function(){gvjs_wP.o.O.call(this);this.aa&&(this.aa.na(),this.aa=null)};gvjs_.JI="label-input-label";gvjs_.k$=function(){this.tC=!0;var a=this.j();gvjs_yB(a,this.JI);if(!gvjs_yP()&&!gvjs_AP(this)&&!this.lra){var b=this;a=function(){b.j()&&(b.j().value="")};gvjs_q?gvjs_Zk(a,10):a()}};gvjs_.TO=function(){gvjs_yP()||(this.aa.zb(this.j(),gvjs_Jq,this.k$),this.rq=null);this.tC=!1;this.os()};
gvjs_.Epa=function(a){27==a.keyCode&&(a.type==gvjs_Ss?this.rq=this.j().value:a.type==gvjs_Bg?this.j().value=this.rq:a.type==gvjs_Ts&&(this.rq=null),a.preventDefault())};gvjs_.Fpa=function(){gvjs_AP(this)||(this.j().value="",gvjs_Zk(this.Qoa,10,this))};gvjs_.Qoa=function(){gvjs_AP(this)||(this.j().value=this.Tb)};gvjs_.Lqa=function(){this.os()};gvjs_.hasFocus=function(){return this.tC};function gvjs_AP(a){return!!a.j()&&""!=a.j().value&&a.j().value!=a.Tb}
gvjs_.clear=function(){this.j().value="";null!=this.rq&&(this.rq="")};gvjs_.reset=function(){gvjs_AP(this)&&(this.clear(),this.os())};gvjs_.Va=function(a){null!=this.rq&&(this.rq=a);this.j().value=a;this.os()};gvjs_.getValue=function(){return null!=this.rq?this.rq:gvjs_AP(this)?this.j().value:""};gvjs_.Rn=function(a){var b=this.j();gvjs_yP()?(b&&(b.placeholder=a),this.Tb=a):gvjs_AP(this)||(b&&(b.value=""),this.Tb=a,this.eea());b&&gvjs_pz(b,gvjs_Cg,this.Tb)};gvjs_.Dd=function(){return this.Tb};
gvjs_.os=function(){var a=this.j();gvjs_yP()?this.j().placeholder!=this.Tb&&(this.j().placeholder=this.Tb):gvjs_zP(this);gvjs_pz(a,gvjs_Cg,this.Tb);gvjs_AP(this)?(a=this.j(),gvjs_yB(a,this.JI)):(this.lra||this.tC||(a=this.j(),gvjs_wB(a,this.JI)),gvjs_yP()||gvjs_Zk(this.eea,this.ksa,this))};gvjs_.Fb=function(a){this.j().disabled=!a;var b=this.j();gvjs_AB(b,this.JI+gvjs_8n,!a)};gvjs_.isEnabled=function(){return!this.j().disabled};
gvjs_.eea=function(){!this.j()||gvjs_AP(this)||this.tC||(this.j().value=this.Tb)};function gvjs_BP(a,b,c){gvjs_KB.call(this,a);this.lj=c||new gvjs_wP;this.vg=!0;a=this.ka=b||new gvjs__C(this.xa());a.setVisible(!1);a.BF=!1;a.C5=!0}gvjs_l(gvjs_BP,gvjs_KB);gvjs_=gvjs_BP.prototype;gvjs_.Dc=null;gvjs_.TC=null;gvjs_.lj=null;gvjs_.ka=null;gvjs_.GA=-1;gvjs_.Of=null;gvjs_.u_=gvjs_Kb;gvjs_.jB=null;gvjs_.JW="";gvjs_.Ena="";gvjs_.iq=null;gvjs_.zga=!1;
gvjs_.J=function(){this.Of=this.xa().J(gvjs_oa,{name:this.Ena,type:gvjs_A,autocomplete:"off"});this.jB=this.xa().J(gvjs_af,"goog-combobox-button");this.H=this.xa().J(gvjs_af,"goog-combobox",this.Of,this.jB);this.zga&&(gvjs_Zc(this.jB,"\u25bc"),gvjs_Ty(this.jB,!0));this.Of.setAttribute(gvjs_Cg,this.JW);this.lj.cb(this.Of);this.ka.pp(!1);this.ka.Ab||this.Ha(this.ka,!0)};
gvjs_.Fb=function(a){this.vg=a;this.lj.Fb(a);gvjs_AB(this.j(),"goog-combobox-disabled",!a)};gvjs_.isEnabled=function(){return this.vg};gvjs_.Mb=function(){gvjs_BP.o.Mb.call(this);var a=this.jc();a.D(this.j(),gvjs_Kg,this.Vta);a.D(this.xa().ic(),gvjs_Kg,this.Wta);a.D(this.Of,gvjs_8p,this.cua);this.Rf=new gvjs_CB(this.Of);a.D(this.Rf,gvjs_Rs,this.gj);this.Dc=new gvjs_sP(this.Of);a.D(this.Dc,gvjs_Ks,this.dua);a.D(this.ka,gvjs_xp,this.fua)};
gvjs_.Re=function(){this.Rf.na();delete this.Rf;this.Dc.na();this.Dc=null;gvjs_BP.o.Re.call(this)};gvjs_.Nh=function(){return!1};gvjs_.O=function(){gvjs_BP.o.O.call(this);this.LM();this.lj.na();this.ka.na();this.jB=this.Of=this.ka=this.lj=null};gvjs_.DB=function(){this.LM();gvjs_CP(this);this.ka.bh(-1)};gvjs_.Fj=function(a){this.ka.Ha(a,!0);this.GA=-1};gvjs_.xu=function(a,b){this.ka.$w(a,b,!0);this.GA=-1};gvjs_.removeItem=function(a){if(a=this.ka.removeChild(a,!0))a.na(),this.GA=-1};gvjs_.rd=function(a){return this.ka.df(a)};
gvjs_.rh=function(){return this.ka.Ee()};gvjs_.Ud=function(){return this.ka};gvjs_.Va=function(a){this.lj.getValue()!=a&&(this.lj.Va(a),this.UO())};gvjs_.getValue=function(){return this.lj.getValue()};function gvjs_DP(a,b){var c=a.ka.isVisible(),d;if(-1==a.GA){for(var e=d=0,f=a.ka.Ee();e<f;e++)a.ka.df(e).isVisible()&&d++;a.GA=d}d=a.GA;c&&0==d?gvjs_CP(a):!c&&0<d&&(b&&(a.wK(""),a.BS(gvjs_Nb(a.lj.getValue().toLowerCase()))),gvjs_Zk(a.LM,1,a),a.ka.setVisible(!0),gvjs_wB(a.j(),gvjs_xO));a.pR()}
gvjs_.pR=function(){this.ka&&this.ka.isVisible()&&(new gvjs_bD(this.j(),9,!0)).Wf(this.ka.j(),8)};function gvjs_CP(a){a.ka.setVisible(!1);gvjs_yB(a.j(),gvjs_xO)}gvjs_.LM=function(){this.iq&&(gvjs__k(this.iq),this.iq=null)};gvjs_.Vta=function(a){this.vg&&(a.target==this.j()||a.target==this.Of||gvjs_Xc(this.jB,a.target))&&(this.ka.isVisible()?this.DB():(gvjs_DP(this,!0),gvjs_kc&&this.Of.focus(),this.Of.select(),this.ka.Xq=!0,a.preventDefault()));a.stopPropagation()};
gvjs_.Wta=function(a){gvjs_Xc(this.ka.j(),a.target)||this.DB()};gvjs_.fua=function(a){var b=a.target;this.dispatchEvent(new gvjs_vP(gvjs_xp,this,b))&&(b=b.dj(),this.lj.getValue()!=b&&(this.lj.Va(b),this.dispatchEvent(gvjs_rq)),this.DB());a.stopPropagation()};gvjs_.cua=function(){this.LM();this.iq=gvjs_Zk(this.DB,250,this)};
gvjs_.gj=function(a){var b=this.ka.isVisible();if(b&&this.ka.gj(a))return!0;var c=!1;switch(a.keyCode){case 27:b&&(this.DB(),c=!0);break;case 9:b&&(b=gvjs_hC(this.ka))&&(b.bi(a),c=!0);break;case 38:case 40:b||(gvjs_DP(this,!0),c=!0)}c&&a.preventDefault();return c};gvjs_.dua=function(){this.UO()};gvjs_.UO=function(){var a=gvjs_Nb(this.lj.getValue().toLowerCase());this.wK(a);gvjs_7v(this.xa().ic())==this.Of&&gvjs_DP(this,!1);var b=gvjs_hC(this.ka);""!=a&&b&&b.isVisible()||this.BS(a);this.TC=a;this.dispatchEvent(gvjs_rq)};
gvjs_.wK=function(a){for(var b=!1,c=0,d=!this.u_(a,this.TC),e=0,f=this.ka.Ee();e<f;e++){var g=this.ka.df(e);if(g instanceof gvjs_WC){if(!g.isVisible()&&!d)continue;var h=g.dj();h=typeof g.Zra==gvjs_a&&g.Faa||h&&this.u_(h.toLowerCase(),a);typeof g.yS==gvjs_a&&g.yS(a);g.setVisible(!!h);b=h||b}else b=g.isVisible()||b;g.isVisible()&&c++}this.GA=c};
gvjs_.BS=function(a){if(""!=a)for(var b=0,c=this.ka.Ee();b<c;b++){var d=this.ka.df(b),e=d.dj();if(e&&this.u_(e.toLowerCase(),a)){this.ka.bh(b);d.yS&&d.yS(a);return}}this.ka.bh(-1)};function gvjs_EP(a,b,c,d){gvjs_WC.call(this,a,b,c,d)}gvjs_l(gvjs_EP,gvjs_WC);gvjs_YB("goog-combobox-item",function(){return new gvjs_EP(null)});gvjs_EP.prototype.Faa=!1;gvjs_EP.prototype.Zra=function(){return this.Faa};
gvjs_EP.prototype.yS=function(a){if(this.isEnabled()){var b=this.dj(),c=b.toLowerCase().indexOf(a);if(0<=c){var d=this.xa();this.setContent([d.createTextNode(b.substr(0,c)),d.J("B",null,b.substr(c,a.length)),d.createTextNode(b.substr(c+a.length))])}}};function gvjs_FP(){}gvjs_l(gvjs_FP,gvjs_XB);gvjs_Qh(gvjs_FP);gvjs_=gvjs_FP.prototype;gvjs_.J=function(a){var b=this.Sl(a);b=a.xa().J(gvjs_v,gvjs_mp+b.join(" "),a.getContent());this.nl(b,a.sn());return b};gvjs_.Uk=function(){return gvjs_iq};gvjs_.Nh=function(a){return a.tagName==gvjs_v};gvjs_.cb=function(a,b){gvjs_wB(b,gvjs_R);return gvjs_FP.o.cb.call(this,a,b)};gvjs_.getValue=function(){return""};gvjs_.ra=function(){return gvjs_yO};gvjs_YB(gvjs_yO,function(){return new gvjs_aC(null,gvjs_FP.kc())});function gvjs_GP(){}gvjs_l(gvjs_GP,gvjs_FP);gvjs_Qh(gvjs_GP);gvjs_GP.prototype.ra=function(){return gvjs_zO};gvjs_YB(gvjs_zO,function(){return new gvjs_aC(null,gvjs_GP.kc())});function gvjs_HP(a,b,c){gvjs_WC.call(this,a,b,c);this.p2(!0)}gvjs_l(gvjs_HP,gvjs_WC);gvjs_HP.prototype.bi=function(){return this.dispatchEvent(gvjs_xp)};gvjs_YB(gvjs_rp,function(){return new gvjs_HP(null)});function gvjs_IP(a,b){var c=b.ea("filterColumnIndex");if(null!=c)return b=parseInt(c,10),a.Td(b),b;if(b=gvjs_r(b,"filterColumnLabel")){a:{c=a.$();for(var d=0;d<c;d++)if(a.Fa(d)==b)break a;throw Error("Invalid column label:"+b);}return d}throw Error("Either filterColumnIndex or filterColumnLabel must be specified.");};function gvjs_JP(a){gvjs_MO.call(this,a);this.De=-1}gvjs_l(gvjs_JP,gvjs_lP);gvjs_=gvjs_JP.prototype;gvjs_.sq=null;gvjs_.uc=null;gvjs_.Kf=function(){return{useFormattedValue:!1,values:null}};gvjs_.Yl=function(a,b){a=gvjs_JP.o.Yl.call(this,a,b);null==a.label&&(a.label=this.sq);a.values=this.uc;return a};
gvjs_.gr=function(a,b,c){this.clear();this.De=gvjs_IP(a,b);this.sq=a.Fa(this.De);var d=b.ea("values");if(gvjs_h(d)&&d.length)this.uc=d;else{b=gvjs_s(b,gvjs_HO);d=new gvjs_D;for(var e=[],f=0;f<a.ca();f++){var g=b?a.Na(f,this.De):a.getValue(f,this.De);null==g||d.contains(g)||(d.add(g),e.push(g))}this.uc=e}this.wL(c)};
gvjs_.wL=function(a){var b=a.selectedValues;if(b){if(!gvjs_h(b))throw Error(gvjs_uO);var c=new gvjs_D;gvjs_m(this.uc,function(d){null!=d&&c.add(String(d))});a.selectedValues=gvjs_Db(b,function(d){return c.contains(String(d))})}};
gvjs_.HF=function(a,b,c){var d=new gvjs_D;c=c.selectedValues;if(gvjs_h(c))for(var e=0;e<c.length;e++)null!=c[e]&&d.add(String(c[e]));if(0==d.tb())return new gvjs_N(a);c=gvjs_s(b,gvjs_HO);b=[];for(e=0;e<a.ca();e++){if(c)var f=a.Na(e,this.De);else f=a.getValue(e,this.De),null!=f&&(f=String(f));d.contains(f)&&b.push(e)}a=new gvjs_N(a);a.vp(b);return a};function gvjs_KP(a,b,c,d){gvjs_KB.call(this,d);this.Tb=a;this.Yra=b==gvjs__;this.Xva=c||""}gvjs_l(gvjs_KP,gvjs_KB);gvjs_=gvjs_KP.prototype;gvjs_.Kaa=null;gvjs_.xG=null;function gvjs_LP(a){if(!a.label)return null;var b=a.labelStacking==gvjs__?gvjs__:gvjs_X,c;a.labelSeparator&&(c=String(a.labelSeparator));return new gvjs_KP(String(a.label),b,c)}
gvjs_.J=function(){var a=this.G.J(gvjs_v);this.H=a;this.Kaa=gvjs_E("LABEL","google-visualization-controls-label",this.Tb+this.Xva);a.appendChild(this.Kaa);this.xG=gvjs_E(gvjs_v);this.Yra||gvjs_wB(this.xG,gvjs_R);a.appendChild(this.xG)};gvjs_.Nh=function(){return!1};gvjs_.ib=function(){return this.xG};gvjs_.addElement=function(a){this.xG.appendChild(a)};function gvjs_MP(a,b){this.be=a;this.Hba=b}gvjs_MP.prototype.Dd=function(){return this.Hba.Dd(this)};gvjs_MP.prototype.getId=function(){return this.Hba.getId(this)};gvjs_MP.prototype.get=function(){return this.be};function gvjs_Pia(a,b){return a.Dd().localeCompare(b.Dd())}function gvjs_NP(){}gvjs_NP.prototype.Dd=function(a){return String(a.get())};gvjs_NP.prototype.getId=function(a){return String(a.get())};function gvjs_OP(a){gvjs_LO.call(this,a);this.uc=[];this.Fg=new gvjs_hy}gvjs_l(gvjs_OP,gvjs_LO);gvjs_OP.prototype.m=null;gvjs_OP.prototype.XG=null;var gvjs_PP={eza:gvjs_AO,jza:gvjs_6p,lza:"belowWrapping",kza:gvjs_BO};gvjs_OP.prototype.O=function(){gvjs_H(this.XG);gvjs_OP.o.O.call(this)};gvjs_OP.prototype.getState=function(){for(var a={selectedValues:[]},b=this.Fg.Ja(),c=0;c<b.length;c++)a.selectedValues.push(b[c].get());return a};
gvjs_OP.prototype.draw=function(a,b){b=gvjs_p(b||{});b.caption||(b.caption="Choose a value...");b.valuesMediator=b.valuesMediator||new gvjs_NP;b.cssClass=b.cssClass?String(b.cssClass):"google-visualization-controls-categoryfilter";"allowMultiple"in b||(b.allowMultiple=!0);"allowNone"in b||(b.allowNone=!0);"allowTyping"in b||(b.allowTyping=!0);"sortValues"in b||(b.sortValues=!0);var c=!1,d;for(d in gvjs_PP)if(b.selectedValuesLayout==gvjs_PP[d]){c=!0;break}c||(b.selectedValuesLayout=gvjs_AO);this.m=
b;gvjs_Qia(this,a);(a=gvjs_LP(this.m))||(a=new gvjs_KB);a.W(this.getContainer());gvjs_wB(a.j(),this.m.cssClass);gvjs_H(this.XG);this.XG=this.m.allowTyping?this.m.allowMultiple?new gvjs_QP(this):new gvjs_RP(this):this.m.allowMultiple?new gvjs_SP(this):new gvjs_TP(this);this.XG.W(a);this.Fg.isEmpty()||this.XG.fE()};
function gvjs_Qia(a,b){b=b||{};var c=a.m.valuesMediator,d=new gvjs_D;if(null!=b.selectedValues){if(!gvjs_h(b.selectedValues))throw Error(gvjs_uO);a.m.allowMultiple?gvjs_m(b.selectedValues,function(g){d.add((new gvjs_MP(g,c)).getId())}):b.selectedValues.length&&d.add((new gvjs_MP(b.selectedValues[0],c)).getId())}b=gvjs_h(a.m.values)?a.m.values:[];for(var e=0;e<b.length;e++){var f=new gvjs_MP(b[e],c);a.uc.push(f);d.contains(f.getId())&&a.Fg.set(f.getId(),f)}a.m.sortValues&&gvjs_2h(a.uc,gvjs_Pia);!gvjs_UP(a)&&
0<a.uc.length&&0==a.Fg.tb()&&a.Fg.set(a.uc[0].getId(),a.uc[0])}gvjs_OP.prototype.ru=function(){gvjs_K(this,gvjs_GO,null)};function gvjs_VP(a){return a.Fg.tb()==a.uc.length}function gvjs_UP(a){return!!a.m.allowNone}function gvjs_WP(a){gvjs_G.call(this);this.dc=a;this.Ie=null}gvjs_l(gvjs_WP,gvjs_G);gvjs_=gvjs_WP.prototype;gvjs_.O=function(){gvjs_H(this.Ie);gvjs_WP.o.O.call(this)};
gvjs_.W=function(a){gvjs_H(this.Ie);this.Ie=new gvjs_iD(this.dc.m.caption);this.mW();a.Ha(this.Ie,!0);this.dc.addEventListener(this.Ie,gvjs_xp,this.Po,!1,this);this.Ie.Fb(0<this.dc.uc.length)};gvjs_.mW=function(){for(var a=this.dc.uc,b=0;b<a.length;b++)this.Ie.Fj(new gvjs_HP(a[b].Dd(),a[b]))};gvjs_.fE=function(){};gvjs_.Po=function(){this.dc.ru()};function gvjs_TP(a){gvjs_WP.call(this,a)}gvjs_l(gvjs_TP,gvjs_WP);
gvjs_TP.prototype.mW=function(){var a=this.dc;gvjs_UP(a)&&this.Ie.Fj(new gvjs_HP(a.m.caption));gvjs_TP.o.mW.call(this)};gvjs_TP.prototype.fE=function(){for(var a=this.dc.Fg.Ja()[0],b=0,c=this.Ie.rh();b<c;b++)if(this.Ie.rd(b).ai==a){this.Ie.tk(b);break}};gvjs_TP.prototype.Po=function(a){this.dc.Fg.clear();var b=this.Ie.Ge().ai;b&&this.dc.Fg.set(b.getId(),b);gvjs_TP.o.Po.call(this,a)};function gvjs_SP(a){gvjs_WP.call(this,a);this.rk=null}gvjs_l(gvjs_SP,gvjs_WP);gvjs_=gvjs_SP.prototype;
gvjs_.O=function(){gvjs_H(this.rk);gvjs_SP.o.O.call(this)};gvjs_.W=function(a){gvjs_SP.o.W.call(this,a);var b=this.dc.m.selectedValuesLayout;b==gvjs_AO&&this.Ie.Wr(gvjs_R);gvjs_H(this.rk);this.rk=new gvjs_XP(b,gvjs_Py(this.Ie.j()).width,gvjs_UP(this.dc)?0:1);a.Ha(this.rk,!0);this.dc.addEventListener(this.rk,gvjs_xp,this.YH,!1,this)};
gvjs_.fE=function(){for(var a=this.dc.Fg,b=0,c=this.Ie.rh();b<c;b++)a.ye(this.Ie.rd(b).ai.getId())&&this.Ie.rd(b).setVisible(!1);gvjs_YP(this.rk,a.Ja());this.Ie.ll(null);this.Ie.Fb(!gvjs_VP(this.dc))};gvjs_.Po=function(a){var b=this.Ie.Ge().ai;this.Ie.Ge().setVisible(!1);this.Ie.ll(null);this.dc.Fg.set(b.getId(),b);this.Ie.Fb(!gvjs_VP(this.dc));gvjs_YP(this.rk,this.dc.Fg.Ja());gvjs_SP.o.Po.call(this,a)};
gvjs_.YH=function(a){(a=a.item)&&this.dc.Fg.remove(a.getId());this.Ie.Fb(!0);for(var b=0,c=this.Ie.rh();b<c;b++)if(this.Ie.rd(b).ai==a){this.Ie.rd(b).setVisible(!0);break}this.dc.ru()};function gvjs_ZP(a){gvjs_G.call(this);this.dc=a;this.de=null}gvjs_l(gvjs_ZP,gvjs_G);gvjs_=gvjs_ZP.prototype;gvjs_.O=function(){gvjs_H(this.de);gvjs_ZP.o.O.call(this)};
gvjs_.W=function(a){var b=this.dc.uc;gvjs_H(this.de);this.de=new gvjs_BP;this.de.zga=!0;var c=this.de;c.JW=this.dc.m.caption;c.lj&&c.lj.Rn(c.JW);for(c=0;c<b.length;c++)this.de.Fj(new gvjs_EP(b[c].Dd(),b[c]));a.Ha(this.de,!0);this.de.Fb(0<b.length);this.dc.addEventListener(this.de,gvjs_xp,this.Po,!1,this);a=gvjs_Eh(gvjs_Fk(),gvjs_Ks,null,this.de.j())[0];this.dc.addEventListener(a,gvjs_8p,this.AY,!1,this)};gvjs_.fE=function(){};gvjs_.Po=function(){this.dc.ru()};gvjs_.AY=function(){};
function gvjs_RP(a){gvjs_ZP.call(this,a)}gvjs_l(gvjs_RP,gvjs_ZP);gvjs_RP.prototype.fE=function(){this.de.Va(this.dc.Fg.Ja()[0].Dd())};gvjs_RP.prototype.Po=function(a){this.dc.Fg.clear();var b=a.item.getValue();b&&this.dc.Fg.set(b.getId(),b);gvjs_RP.o.Po.call(this,a)};gvjs_RP.prototype.AY=function(){var a=this.dc.Fg;if(!this.de.getValue()&&gvjs_UP(this.dc)){var b=!a.isEmpty();a.clear();b&&this.dc.ru()}else a.isEmpty()?this.de.Va(""):this.de.Va(a.Ja()[0].Dd())};
function gvjs_QP(a){gvjs_ZP.call(this,a);this.rk=null}gvjs_l(gvjs_QP,gvjs_ZP);gvjs_=gvjs_QP.prototype;gvjs_.O=function(){gvjs_H(this.rk);gvjs_QP.o.O.call(this)};gvjs_.W=function(a){gvjs_QP.o.W.call(this,a);var b=this.dc.m.selectedValuesLayout;b==gvjs_AO&&gvjs_wB(this.de.j(),gvjs_R);gvjs_H(this.rk);this.rk=new gvjs_XP(b,gvjs_Py(this.de.j()).width,gvjs_UP(this.dc)?0:1);a.Ha(this.rk,!0);this.dc.addEventListener(this.rk,gvjs_xp,this.YH,!1,this)};
gvjs_.fE=function(){for(var a=this.dc.Fg,b=0,c=this.de.rh();b<c;b++)a.ye(this.de.rd(b).ai.getId())&&this.de.rd(b).Fb(!1);gvjs_YP(this.rk,a.Ja());this.de.Va("");this.de.Fb(!gvjs_VP(this.dc))};gvjs_.Po=function(a){var b=a.item.getValue();a.item.Fb(!1);a.preventDefault();this.de.DB();this.de.Va("");this.dc.Fg.set(b.getId(),b);this.de.Fb(!gvjs_VP(this.dc));gvjs_YP(this.rk,this.dc.Fg.Ja());gvjs_QP.o.Po.call(this,a)};
gvjs_.YH=function(a){a=a.item;this.dc.Fg.remove(a.getId());this.de.Fb(!0);for(var b=0,c=this.de.rh();b<c;b++)if(this.de.rd(b).ai==a){this.de.rd(b).Fb(!0);break}this.dc.ru()};gvjs_.AY=function(){this.de.Va("")};function gvjs_XP(a,b,c,d){gvjs_KB.call(this,d);this.jE=a;this.Sq=b;this.P_=c;this.pz=0;this.gT=[]}gvjs_l(gvjs_XP,gvjs_KB);gvjs_XP.prototype.J=function(){var a=this.G.J("UL");this.H=a;this.Gf(a)};gvjs_XP.prototype.Nh=function(a){return"UL"==a.tagName};
gvjs_XP.prototype.Gf=function(a){gvjs_wB(a,"google-visualization-controls-categoryfilter-selected");this.jE==gvjs_AO?gvjs_wB(a,gvjs_R):("belowWrapping"==this.jE||this.jE==gvjs_BO)&&gvjs_J(a,gvjs_it,this.Sq+gvjs_Y)};
function gvjs_YP(a,b){a.Ac(!0);a.gT=[];a.pz=b.length;for(var c=0;c<a.pz;c++){var d=a,e=b[c];var f=new gvjs_eC(gvjs_X,new gvjs__P(d.jE));f.pp(!1);var g=new gvjs_aC("\u00d7",new gvjs_GP);gvjs_I(g,gvjs_xp,gvjs_yb(d.YH,e,f),!1,d);f.Ha(g,!0);g.j().setAttribute(gvjs_hv,0);g.Fb(d.pz>d.P_);d=new gvjs_1B(e.Dd());d.Wr(gvjs_R);f.Ha(d,!0);a.gT.push(f);a.Ha(f,!0)}}
gvjs_XP.prototype.YH=function(a,b,c){this.pz<=this.P_||(this.removeChild(c.target.getParent(),!0),gvjs_Yh(this.gT,b),this.pz--,this.pz<=this.P_&&0<this.pz&&gvjs_m(this.gT,function(d){d.df(0).Fb(!1)}),this.dispatchEvent(new gvjs_vP(gvjs_xp,this,a)),c.stopPropagation())};function gvjs__P(a){this.dM=void 0;this.jE=a}gvjs_l(gvjs__P,gvjs_bC);gvjs__P.prototype.J=function(a){var b=this.jE==gvjs_BO?"":gvjs_R;return a.xa().J("LI",this.Sl(a).join(" ")+" "+b)};gvjs__P.prototype.Nh=function(a){return"LI"==a.tagName};function gvjs_0P(a){gvjs_JP.call(this,a)}gvjs_l(gvjs_0P,gvjs_JP);gvjs_0P.prototype.at=function(){return"SelectorUi"};function gvjs_1P(a){gvjs_MO.call(this,a);this.De=null}gvjs_l(gvjs_1P,gvjs_lP);gvjs_1P.prototype.at=function(){return"ChartRangeFilterUi"};gvjs_1P.prototype.gr=function(a,b,c){this.clear();this.De=gvjs_IP(a,b);b=a.Y(this.De);if(b==gvjs_d||b==gvjs_La)throw Error("The filter cannot operate on a column of type "+b+". Column type must be one of: number, date, datetime or timeofday. Column role must be domain, and correlate to a continuous axis.");c.__data__=a};
gvjs_1P.prototype.HF=function(a,b,c){a=new gvjs_N(a);b=c.range;if(gvjs_ub(b)!=gvjs_Ya)return a;c=b.start;b=b.end;if(null==c&&null==b)return a;a.vp(a.$B([{column:this.De,minValue:c,maxValue:b}]));return a};function gvjs_2P(a){gvjs_LO.call(this,a)}gvjs_l(gvjs_2P,gvjs_LO);gvjs_=gvjs_2P.prototype;gvjs_.RD=null;gvjs_.SJ=null;gvjs_.Iv=null;gvjs_.O=function(){this.RD&&this.RD.Qb();gvjs_2P.o.O.call(this)};
gvjs_.getState=function(){function a(){return null===b.Iv?{}:{range:b.Iv.range}}var b=this;if(!this.RD)return a();var c=this.RD.AO();return null==c.start||null==c.end?a():{range:c}};gvjs_.draw=function(a,b){this.Iv=a;this.SJ||(this.SJ=new gvjs_O({chartType:"RangeSelector",dataTable:a.__data__,options:b,state:a,view:b.chartView}),gvjs_Mk(this.SJ,gvjs_x,gvjs_k(this.iua,this)));this.SJ.draw(this.getContainer())};gvjs_.iua=function(){this.RD=this.SJ.sf();gvjs_Mk(this.RD,gvjs_eu,gvjs_k(this.hua,this))};
gvjs_.hua=function(a){gvjs_K(this,gvjs_GO,{startChanged:a.startChanged,endChanged:a.endChanged,inProgress:a.inProgress})};function gvjs_3P(a){gvjs_jP.call(this,a);this.Sp=-1;this.WV=null}gvjs_l(gvjs_3P,gvjs_jP);gvjs_=gvjs_3P.prototype;gvjs_.DV=null;gvjs_.lf=null;gvjs_.Kf=function(){return{columns:null}};gvjs_.Yl=function(a,b){a=gvjs_3P.o.Yl.call(this,a,b);a.values=this.lf;b=a.label;null==b&&(b=this.sO(),1<=b.length&&(b=b[0].Wa(),null!=this.Sp&&(b=b.Fa(this.Sp),a.label=b)));return a};
gvjs_.gr=function(a,b,c){this.clear();this.Sp=b.Ca("chartColumnIndex");this.DV=b.ob("chartColumnId");if(null==this.Sp){if(null==this.DV)throw Error("Either chartColumnIndex or chartColumnId must be specified.");for(var d=a.$(),e=0;e<d;e++)a.Td(e)===this.DV&&(this.Sp=e);if(null==this.Sp||0>this.Sp)throw Error("Invalid column id");}if(null==this.Sp||0>this.Sp)throw Error("Invalid column index");d=b.ea("columns");if(gvjs_h(d)&&d.length)this.lf=d;else{d={string:{string:!0},discrete:{string:!0},number:{number:!0},
dateortime:{date:!0,datetime:!0,timeofday:!0},continuous:{number:!0,date:!0,datetime:!0,timeofday:!0}};b=(b=gvjs_r(b,"columnType"))&&d[b];this.WV={};d=[];e=a.$();for(var f=0;f<e;f++){var g=a.Fa(f),h=a.Td(f),k=a.Y(f);if(!b||b[k])this.WV[g]={index:f,id:h,label:g},d.push(g)}this.lf=d}this.MS=[{input:"dataColumnIndex",mg:"view.columns."+this.Sp}];this.wL(c)};
gvjs_.wL=function(a){a=a.selectedValues;if(null!=a&&(!gvjs_h(a)||1<a.length))throw Error("Invalid selectedValues: should be an array of length zero or one.");};gvjs_.PU=function(a,b,c){var d=c.selectedValues;return gvjs_h(d)&&1===d.length?(c.dataColumnIndex=this.WV[d[0]].index,gvjs_3P.o.PU.call(this,a,b,c)):a};function gvjs_4P(a){gvjs_3P.call(this,a)}gvjs_l(gvjs_4P,gvjs_3P);gvjs_4P.prototype.at=function(){return"SelectorUi"};var gvjs_Ria={day:864E5,hour:36E5,minute:6E4,second:1E3,millisecond:1};function gvjs_5P(a){var b=gvjs_6P(a);var c=a.split(" ");if(2===c.length){if(c=Number(c[0]),typeof c!==gvjs_c||isNaN(c))throw Error('Invalid number for increment: "'+a+'".');}else c=1;b=gvjs_Ria[b];if(!b)throw Error('Invalid number for increment "'+a+'".');return c*b}function gvjs_6P(a){var b=a.length-1;a="s"===a.charAt(b)?a.substring(0,b):a;a=a.split(" ");return 2===a.length?a[1]:a[0]}
function gvjs_7P(a,b,c){a=Number(a);b=(a-c)%gvjs_5P(b);return a=new Date(a-b)}function gvjs_8P(a,b,c){a=Number(a);c=a-c;b=gvjs_5P(b);c%=b;return a=0===c?new Date(a):new Date(a+b-c)};function gvjs_9P(a){gvjs_pP.call(this,a);this.uj=this.Nb=null}gvjs_l(gvjs_9P,gvjs_pP);gvjs_=gvjs_9P.prototype;gvjs_.o4=function(){var a=this.Lc.getValue()+this.Pp,b=a+this.Lc.Ul();this.Vv&&gvjs_Zc(this.Vv,this.Nb.ac(new Date(a)));this.Ev&&gvjs_Zc(this.Ev,this.Nb.ac(new Date(b)))};gvjs_.V0=function(a){var b=a.nb(gvjs_2r);(a=String(a.ea("step")))&&!b.pattern&&(b.pattern=gvjs_Sia[gvjs_6P(a)]);this.Nb=new gvjs_je(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs__d([b,gvjs_$P]);(b=gvjs_LP(b))||(b=new gvjs_KB);b.W(this.getContainer());var d=gvjs_r(c,"cssClass");d&&gvjs_wB(b.j(),d);gvjs_rP(this,b,a,c,gvjs_$P)};gvjs_.Vea=function(a){this.uj=String(a.ea("step",gvjs_$P.step));var b=gvjs_5P(this.uj);this.Lc.JS(b);b=gvjs_5P(String(a.ea("unitIncrement",gvjs_$P.unitIncrement)));this.Lc.vA=b;a=gvjs_5P(String(a.ea(gvjs_CO,gvjs_$P.blockIncrement)));this.Lc.Km=a};gvjs_.jY=function(a,b){return a.Ca(b)};
gvjs_.sda=function(a,b,c){var d=String(this.uj);a=new Date(a);var e=gvjs_6P(d);a=gvjs_7P(a,e,Number(new Date(1970,0,1))).valueOf();b=gvjs_8P(new Date(b),d,a).valueOf();c.lowValue=gvjs_7P(new Date(c.lowValue),d,a).valueOf();c.highValue=gvjs_8P(new Date(c.highValue),d,a).valueOf();return{minValue:a,maxValue:b,state:c}};gvjs_.getState=function(){var a=gvjs_9P.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
var gvjs_Sia={year:"yyyy",month:"yyyy-MM",day:"yyyy-MM-dd",hour:gvjs_IO,minute:gvjs_IO,second:"yy/MM/dd hh:mm:ssa",millisecond:"yy/MM/dd hh:mm:ss:SSSSa"},gvjs_$P={showRangeValues:!0,minValue:null,maxValue:null,cssClass:gvjs_DO,step:"day",unitIncrement:"day",blockIncrement:"day",orientation:gvjs_X};function gvjs_aQ(a){gvjs_mP.call(this,a)}gvjs_l(gvjs_aQ,gvjs_mP);gvjs_=gvjs_aQ.prototype;gvjs_.at=function(){return"DateRangeFilterUi"};gvjs_.Yl=function(a,b){a=gvjs_aQ.o.Yl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label=this.sq);return a};gvjs_.mZ=function(a,b){this.ES(gvjs_t(b,gvjs_Ig,gvjs_bQ(this,a,gvjs_qt)));this.DS(gvjs_t(b,gvjs_Hg,gvjs_bQ(this,a,gvjs_ht)))};
gvjs_.gr=function(a,b,c){this.clear();this.De=gvjs_IP(a,b);this.sq=a.Fa(this.De);var d=a.Y(this.De);if(d!=gvjs_Pa&&d!=gvjs_Qa)throw Error(gvjs_Se+this.De+" is not a date");this.mZ(a,b);gvjs_nP(this,c)};function gvjs_bQ(a,b,c){a=b.mn(a.De)[c];return Number(a)}gvjs_.y4=function(a){return Number(a)};gvjs_.getState=function(){var a=gvjs_aQ.o.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
gvjs_.dY=function(a,b,c){(a=gvjs_Hw(a,"ui",{}).step)||(a="day");return function(d){d=Number(d);return b<=d&&c>=d}};function gvjs_cQ(a){gvjs_LO.call(this,a);this.K={}}gvjs_l(gvjs_cQ,gvjs_LO);gvjs_cQ.prototype.draw=function(a){this.K=a};gvjs_cQ.prototype.getState=function(){return this.K};function gvjs_dQ(a){gvjs_mP.call(this,a)}gvjs_l(gvjs_dQ,gvjs_mP);gvjs_=gvjs_dQ.prototype;gvjs_.at=function(){return"NumberRangeUi"};gvjs_.Yl=function(a,b){a=gvjs_dQ.o.Yl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Bb;null==a.label&&(a.label=this.sq);return a};gvjs_.mZ=function(a,b){this.ES(gvjs_t(b,gvjs_Ig,a.mn(this.De).min));this.DS(gvjs_t(b,gvjs_Hg,a.mn(this.De).max))};
gvjs_.gr=function(a,b,c){this.clear();this.De=gvjs_IP(a,b);this.sq=a.Fa(this.De);if(a.Y(this.De)!==gvjs_c)throw Error(gvjs_Se+this.De+" is not numeric");this.mZ(a,b);gvjs_nP(this,c)};gvjs_.y4=function(a){return gvjs_gc(String(a))};gvjs_.dY=function(a,b,c){(a=gvjs_Hw(a,"ui",{}).step)||(a=1);return function(d){return b<=d&&c>=d}};function gvjs_eQ(a){gvjs_pP.call(this,a);this.uj=this.Nb=null;this.In=0}gvjs_l(gvjs_eQ,gvjs_pP);gvjs_=gvjs_eQ.prototype;gvjs_.o4=function(){var a=this.Lc.getValue()+this.Pp,b=a+this.Lc.Ul();a/=this.In;b/=this.In;this.Vv&&gvjs_Zc(this.Vv,this.Nb.ac(a));this.Ev&&gvjs_Zc(this.Ev,this.Nb.ac(b))};gvjs_.V0=function(a){var b=a.nb(gvjs_2r);(a=Number(a.Ca("step")))&&null==b.fractionDigits&&(b.fractionDigits=a);this.Nb=new gvjs_ne(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs__d([b,gvjs_fQ]);(b=gvjs_LP(b))||(b=new gvjs_KB);b.W(this.getContainer());var d=gvjs_r(c,"cssClass");d&&gvjs_wB(b.j(),d);gvjs_rP(this,b,a,c,gvjs_fQ)};
gvjs_.Vea=function(a){var b=gvjs_fQ.step,c=a.Ca(gvjs_ov);null!=c&&(c=Math.max(2,c),b=(this.Lc.tf()-this.Lc.uf())/c);b=Number(gvjs_t(a,"step",b));c=gvjs_t(a,"unitIncrement",gvjs_fQ.unitIncrement);a=gvjs_t(a,gvjs_CO,gvjs_fQ.blockIncrement);this.In=Math.pow(10,gvjs_qE(b));b=Math.round(b*this.In);c=Math.round(c*this.In);a=Math.round(a*this.In);this.Lc.JS(b);this.Lc.vA=c;this.Lc.Km=a;this.uj=b};gvjs_.jY=function(a,b){return a.Ca(b)};
gvjs_.sda=function(a,b,c){var d=this.uj;a=Math.floor(a*this.In);a-=(a-0)%d;b=gvjs_gQ(Math.ceil(b*this.In),d,a);var e=c.lowValue*this.In;c.lowValue=e-(e-a)%d;c.highValue=gvjs_gQ(c.highValue*this.In,d,a);return{minValue:a,maxValue:b,state:c}};
gvjs_.getState=function(){var a=this.Lc;if(!a)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var b=a.getValue(),c=a.Ul();return{lowValue:(b+this.Pp)/this.In,highValue:(b+c+this.Pp)/this.In,lowThumbAtMinimum:b===a.uf(),highThumbAtMaximum:b+c===a.tf()}};function gvjs_gQ(a,b,c){c=(a-c)%b;return 0===c?a:a+b-c}var gvjs_fQ={showRangeValues:!0,minValue:null,maxValue:null,ticks:null,cssClass:gvjs_DO,format:{},step:1,unitIncrement:1,blockIncrement:10,orientation:gvjs_X};function gvjs_hQ(a){gvjs_jP.call(this,a)}gvjs_l(gvjs_hQ,gvjs_kP);gvjs_hQ.prototype.at=function(){return"NumberRangeUi"};function gvjs_iQ(a){gvjs_MO.call(this,a);this.De=-1}gvjs_l(gvjs_iQ,gvjs_lP);gvjs_=gvjs_iQ.prototype;gvjs_.sq=null;gvjs_.Kf=function(){return{matchType:gvjs__a,caseSensitive:!1,useFormattedValue:!1}};gvjs_.Yl=function(a,b){a=gvjs_iQ.o.Yl.call(this,a,b);null==a.label&&(a.label=this.sq);return a};gvjs_.gr=function(a,b){this.clear();this.De=gvjs_IP(a,b);this.sq=a.Fa(this.De)};
gvjs_.HF=function(a,b,c){var d=gvjs_s(b,"caseSensitive"),e=gvjs_r(b,"matchType");gvjs_s(b,"prefixMatch");var f=gvjs_s(b,gvjs_HO),g=this.De;b=[];c=c.value.toString();if(!c)return new gvjs_N(a);d||(c=c.toLowerCase());for(var h=0;h<a.ca();h++){var k=f?a.Na(h,g):""+a.getValue(h,g);d||(k=k.toLowerCase());switch(e){case "exact":k==c&&b.push(h);break;case "any":-1!=k.indexOf(c)&&b.push(h);break;default:0==k.indexOf(c)&&b.push(h)}}a=new gvjs_N(a);a.vp(b);return a};
function gvjs_jQ(a){gvjs_iQ.call(this,a)}gvjs_l(gvjs_jQ,gvjs_iQ);gvjs_jQ.prototype.at=function(){return"StringFilterUi"};function gvjs_kQ(a){gvjs_LO.call(this,a);this.Am=0}gvjs_l(gvjs_kQ,gvjs_LO);gvjs_=gvjs_kQ.prototype;gvjs_.Of=null;gvjs_.getState=function(){return{value:this.Of?this.Of.value:null}};
gvjs_.draw=function(a,b){b=b||{};var c=gvjs_LP(b);c||(c=new gvjs_KB);c.W(this.getContainer());var d=b.cssClass?String(b.cssClass):"google-visualization-controls-stringfilter";gvjs_wB(c.j(),d);this.Of=this.hW(a,b);c.ib().appendChild(this.Of)};
gvjs_.hW=function(a,b){var c=gvjs_E(gvjs_oa);c.setAttribute(gvjs_zg,gvjs_th(this.getContainer())+"-input");gvjs_bh in a&&a.value&&(c.value=String(a.value));gvjs_FO in b&&c.setAttribute(gvjs_FO,b.placeholder);"realtimeTrigger"in b&&!b.realtimeTrigger?(this.addEventListener(c,gvjs_Ss,this.jaa,!1,this),this.addEventListener(c,gvjs_rq,this.ru,!1,this)):this.addEventListener(c,gvjs_Ts,this.jaa);return c};
gvjs_.jaa=function(a){this.Am&&gvjs__k(this.Am);13==a.keyCode?(this.ru(),a.preventDefault()):this.Am=gvjs_Zk(function(){this.Am=0;this.ru()},200,this)};gvjs_.ru=function(){gvjs_K(this,gvjs_GO,null)};gvjs_g("google.visualization.Choreographer",gvjs_en,void 0);gvjs_en.prototype.bind=gvjs_en.prototype.bind;gvjs_en.prototype.clear=gvjs_en.prototype.clear;gvjs_en.prototype.dispose=gvjs_en.prototype.na;gvjs_en.prototype.isDisposed=gvjs_en.prototype.zg;gvjs_en.prototype.draw=gvjs_en.prototype.draw;gvjs_g(gvjs_Zf,gvjs_qn,void 0);gvjs_qn.prototype.bind=gvjs_qn.prototype.bind;gvjs_qn.prototype.getSelection=gvjs_qn.prototype.getSelection;gvjs_qn.prototype.clear=gvjs_qn.prototype.clear;
gvjs_qn.prototype.dispose=gvjs_qn.prototype.na;gvjs_qn.prototype.isDisposed=gvjs_qn.prototype.zg;gvjs_qn.prototype.draw=gvjs_qn.prototype.draw;gvjs_g("google.visualization.Control",gvjs_MO,void 0);gvjs_MO.prototype.draw=gvjs_MO.prototype.draw;gvjs_MO.prototype.getState=gvjs_MO.prototype.getState;gvjs_MO.prototype.resetControl=gvjs_MO.prototype.St;gvjs_MO.prototype.clear=gvjs_MO.prototype.clear;gvjs_MO.prototype.dispose=gvjs_MO.prototype.na;gvjs_MO.prototype.isDisposed=gvjs_MO.prototype.zg;
gvjs_g(gvjs_1f,gvjs_lP,void 0);gvjs_lP.prototype.applyFilter=gvjs_lP.prototype.VA;gvjs_g(gvjs_hg,gvjs_gP,void 0);gvjs_gP.prototype.applyOperator=gvjs_gP.prototype.IF;gvjs_g("google.visualization.ControlUi",gvjs_LO,void 0);gvjs_LO.prototype.draw=gvjs_LO.prototype.draw;gvjs_LO.prototype.getState=gvjs_LO.prototype.getState;gvjs_LO.prototype.clear=gvjs_LO.prototype.clear;gvjs_LO.prototype.dispose=gvjs_LO.prototype.na;gvjs_LO.prototype.isDisposed=gvjs_LO.prototype.zg;gvjs_g(gvjs_pg,gvjs_jQ,void 0);
gvjs_jQ.prototype.draw=gvjs_jQ.prototype.draw;gvjs_jQ.prototype.applyFilter=gvjs_jQ.prototype.VA;gvjs_jQ.prototype.getState=gvjs_jQ.prototype.getState;gvjs_jQ.prototype.resetControl=gvjs_jQ.prototype.St;gvjs_jQ.prototype.clear=gvjs_jQ.prototype.clear;gvjs_jQ.prototype.dispose=gvjs_jQ.prototype.na;gvjs_jQ.prototype.isDisposed=gvjs_jQ.prototype.zg;gvjs_g(gvjs_qg,gvjs_kQ,void 0);gvjs_kQ.prototype.draw=gvjs_kQ.prototype.draw;gvjs_kQ.prototype.getState=gvjs_kQ.prototype.getState;
gvjs_kQ.prototype.clear=gvjs_kQ.prototype.clear;gvjs_kQ.prototype.isDisposed=gvjs_kQ.prototype.zg;gvjs_g(gvjs_gg,gvjs_dQ,void 0);gvjs_dQ.prototype.draw=gvjs_dQ.prototype.draw;gvjs_dQ.prototype.applyFilter=gvjs_dQ.prototype.VA;gvjs_dQ.prototype.getState=gvjs_dQ.prototype.getState;gvjs_dQ.prototype.resetControl=gvjs_dQ.prototype.St;gvjs_dQ.prototype.clear=gvjs_dQ.prototype.clear;gvjs_dQ.prototype.dispose=gvjs_dQ.prototype.na;gvjs_dQ.prototype.isDisposed=gvjs_dQ.prototype.zg;gvjs_g(gvjs__f,gvjs_aQ,void 0);
gvjs_aQ.prototype.draw=gvjs_aQ.prototype.draw;gvjs_aQ.prototype.applyFilter=gvjs_aQ.prototype.VA;gvjs_aQ.prototype.getState=gvjs_aQ.prototype.getState;gvjs_aQ.prototype.resetControl=gvjs_aQ.prototype.St;gvjs_aQ.prototype.clear=gvjs_aQ.prototype.clear;gvjs_aQ.prototype.dispose=gvjs_aQ.prototype.na;gvjs_aQ.prototype.isDisposed=gvjs_aQ.prototype.zg;gvjs_g("google.visualization.NumberRangeUi",gvjs_eQ,void 0);gvjs_eQ.prototype.draw=gvjs_eQ.prototype.draw;gvjs_eQ.prototype.getState=gvjs_eQ.prototype.getState;
gvjs_eQ.prototype.clear=gvjs_eQ.prototype.clear;gvjs_eQ.prototype.dispose=gvjs_eQ.prototype.na;gvjs_eQ.prototype.isDisposed=gvjs_eQ.prototype.zg;gvjs_g("google.visualization.DateRangeFilterUi",gvjs_9P,void 0);gvjs_9P.prototype.draw=gvjs_9P.prototype.draw;gvjs_9P.prototype.getState=gvjs_9P.prototype.getState;gvjs_9P.prototype.clear=gvjs_9P.prototype.clear;gvjs_9P.prototype.dispose=gvjs_9P.prototype.na;gvjs_9P.prototype.isDisposed=gvjs_9P.prototype.zg;
gvjs_g("google.visualization.NumberRangeSetter",gvjs_hQ,void 0);gvjs_hQ.prototype.draw=gvjs_hQ.prototype.draw;gvjs_hQ.prototype.apply=gvjs_hQ.prototype.apply;gvjs_hQ.prototype.getState=gvjs_hQ.prototype.getState;gvjs_hQ.prototype.resetControl=gvjs_hQ.prototype.St;gvjs_hQ.prototype.clear=gvjs_hQ.prototype.clear;gvjs_hQ.prototype.dispose=gvjs_hQ.prototype.na;gvjs_hQ.prototype.isDisposed=gvjs_hQ.prototype.zg;gvjs_g("google.visualization.ColumnSelector",gvjs_4P,void 0);gvjs_4P.prototype.draw=gvjs_4P.prototype.draw;
gvjs_4P.prototype.apply=gvjs_4P.prototype.apply;gvjs_4P.prototype.getState=gvjs_4P.prototype.getState;gvjs_4P.prototype.resetControl=gvjs_4P.prototype.St;gvjs_4P.prototype.clear=gvjs_4P.prototype.clear;gvjs_4P.prototype.dispose=gvjs_4P.prototype.na;gvjs_4P.prototype.isDisposed=gvjs_4P.prototype.zg;gvjs_g(gvjs_Sf,gvjs_0P,void 0);gvjs_0P.prototype.draw=gvjs_0P.prototype.draw;gvjs_0P.prototype.applyFilter=gvjs_0P.prototype.VA;gvjs_0P.prototype.getState=gvjs_0P.prototype.getState;
gvjs_0P.prototype.resetControl=gvjs_0P.prototype.St;gvjs_0P.prototype.clear=gvjs_0P.prototype.clear;gvjs_0P.prototype.dispose=gvjs_0P.prototype.na;gvjs_0P.prototype.isDisposed=gvjs_0P.prototype.zg;gvjs_g("google.visualization.SelectorUi",gvjs_OP,void 0);gvjs_OP.prototype.draw=gvjs_OP.prototype.draw;gvjs_OP.prototype.getState=gvjs_OP.prototype.getState;gvjs_OP.prototype.clear=gvjs_OP.prototype.clear;gvjs_OP.prototype.dispose=gvjs_OP.prototype.na;gvjs_OP.prototype.isDisposed=gvjs_OP.prototype.zg;
gvjs_g(gvjs_Tf,gvjs_1P,void 0);gvjs_1P.prototype.draw=gvjs_1P.prototype.draw;gvjs_1P.prototype.applyFilter=gvjs_1P.prototype.VA;gvjs_1P.prototype.getState=gvjs_1P.prototype.getState;gvjs_1P.prototype.resetControl=gvjs_1P.prototype.St;gvjs_1P.prototype.clear=gvjs_1P.prototype.clear;gvjs_1P.prototype.dispose=gvjs_1P.prototype.na;gvjs_1P.prototype.isDisposed=gvjs_1P.prototype.zg;gvjs_g(gvjs_Uf,gvjs_2P,void 0);gvjs_2P.prototype.draw=gvjs_2P.prototype.draw;gvjs_2P.prototype.getState=gvjs_2P.prototype.getState;
gvjs_2P.prototype.clear=gvjs_2P.prototype.clear;gvjs_2P.prototype.dispose=gvjs_2P.prototype.na;gvjs_2P.prototype.isDisposed=gvjs_2P.prototype.zg;gvjs_g("google.visualization.HeadlessUi",gvjs_cQ,void 0);gvjs_cQ.prototype.draw=gvjs_cQ.prototype.draw;gvjs_cQ.prototype.getState=gvjs_cQ.prototype.getState;gvjs_cQ.prototype.clear=gvjs_cQ.prototype.clear;gvjs_cQ.prototype.dispose=gvjs_cQ.prototype.na;gvjs_cQ.prototype.isDisposed=gvjs_cQ.prototype.zg;gvjs_g(gvjs_0f,gvjs_hP,void 0);
gvjs_hP.prototype.draw=gvjs_hP.prototype.draw;gvjs_hP.prototype.applyOperator=gvjs_hP.prototype.IF;gvjs_hP.prototype.getState=gvjs_hP.prototype.getState;gvjs_hP.prototype.resetControl=gvjs_hP.prototype.St;gvjs_hP.prototype.clear=gvjs_hP.prototype.clear;gvjs_hP.prototype.dispose=gvjs_hP.prototype.na;gvjs_hP.prototype.isDisposed=gvjs_hP.prototype.zg;gvjs_g("google.visualization.DrilldownOperatorUi",gvjs_iP,void 0);gvjs_iP.prototype.draw=gvjs_iP.prototype.draw;gvjs_iP.prototype.getState=gvjs_iP.prototype.getState;
gvjs_iP.prototype.clear=gvjs_iP.prototype.clear;gvjs_iP.prototype.dispose=gvjs_iP.prototype.na;gvjs_iP.prototype.isDisposed=gvjs_iP.prototype.zg;gvjs_g("google.visualization.drawDrilldown",function(a,b,c){var d=new gvjs_fP(a);gvjs_I(c,gvjs_Jq,function(){d.rollup()});d.draw(b)},void 0);gvjs_g("google.visualization.RemoteDataSource",gvjs_aP,void 0);gvjs_aP.prototype.getUrl=gvjs_aP.prototype.getUrl;gvjs_aP.prototype.getColumnId=gvjs_aP.prototype.Td;gvjs_aP.prototype.getColumnType=gvjs_aP.prototype.Y;
gvjs_aP.prototype.getNumberOfColumns=gvjs_aP.prototype.$;
