var gvjs_lQ="#990000",gvjs_mQ="annotationText",gvjs_nQ="certainty",gvjs_oQ="chartType",gvjs_pQ="col-resize";function gvjs_qQ(a,b){var c=new gvjs_L,d=b.ca(),e=b.$(),f=a.Y(0)!=gvjs_c;f&&c.pe(a.Y(0),a.Fa(0));for(var g=f?1:0,h=g;h<e;++h)c.pe({type:a.Y(h),label:a.Fa(h),role:gvjs_It}),c.pe({type:b.Y(h),label:b.Fa(h),role:gvjs_8q});c.Lp(d);for(var k=0;k<d;++k){f&&(h=b.getValue(k,0),c.mc(k,0,h));var l=g;for(h=g;h<e;++h){var m=a.getValue(k,h);c.mc(k,l,m);l+=1;m=b.getValue(k,h);c.mc(k,l,m);l+=1}}return c}
gvjs_zK.prototype.aq=gvjs_B(63,function(a,b){if(this.ih===gvjs_Xt)return gvjs_qQ(a,b);throw Error("Cannot compute diff for this chart type.");});gvjs_AK.prototype.aq=gvjs_B(62,function(a,b){return gvjs_qQ(a,b)});gvjs_eA.prototype.Wz=gvjs_B(42,function(){});gvjs_pA.prototype.Wz=gvjs_B(41,function(a,b){a.setAttribute("y",b)});gvjs_tA.prototype.Wz=gvjs_B(40,function(a,b){a.style.top=this.Zb(b)});gvjs_eA.prototype.Sz=gvjs_B(39,function(){});
gvjs_pA.prototype.Sz=gvjs_B(38,function(a,b){a.setAttribute("x",b)});gvjs_tA.prototype.Sz=gvjs_B(37,function(a,b){a.style.left=this.Zb(b)});function gvjs_rQ(a,b){var c=gvjs_bx(a,b);if(0<=c)return b;c=-(c+1);if(0==c)return a[0];if(c==a.length)return gvjs_Vh(a);var d=a[c-1];a=a[c];return Math.abs(b-d)<=Math.abs(b-a)?d:a}function gvjs_sQ(a){var b=new gvjs_tD;b.ra=function(){return a};return b}function gvjs_tQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_Qp,gvjs_X)}gvjs_l(gvjs_tQ,gvjs_zK);
function gvjs_uQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_2u,gvjs_X)}gvjs_l(gvjs_uQ,gvjs_zK);function gvjs_vQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_b,gvjs_X,"sparkline")}gvjs_l(gvjs_vQ,gvjs_zK);function gvjs_wQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_w,gvjs_X)}gvjs_l(gvjs_wQ,gvjs_zK);function gvjs_xQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_2g)}gvjs_l(gvjs_xQ,gvjs_zK);gvjs_xQ.prototype.aq=function(a,b){return gvjs_qQ(a,b)};function gvjs_yQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_fq)}
gvjs_l(gvjs_yQ,gvjs_zK);function gvjs_zQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_0p,gvjs__)}gvjs_l(gvjs_zQ,gvjs_zK);gvjs_zQ.prototype.aq=function(a,b){return gvjs_qQ(a,b)};function gvjs_AQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_mq,gvjs_X)}gvjs_l(gvjs_AQ,gvjs_zK);function gvjs_BQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_a,gvjs_0p,gvjs_X)}gvjs_l(gvjs_BQ,gvjs_zK);gvjs_BQ.prototype.aq=function(a,b){return gvjs_qQ(a,b)};function gvjs_CQ(a){gvjs_zK.call(this,a);this.Xd(gvjs_ws,gvjs_0p,gvjs_X)}
gvjs_l(gvjs_CQ,gvjs_zK);var gvjs_Tia={$ha:gvjs_7e,nha:gvjs_Le,xha:gvjs_Ue,Sia:gvjs_bf},gvjs_Uia={fill:gvjs_0n,fillOpacity:.5},gvjs_Via={chartArea:{top:"0",height:gvjs_ho},enableInteractivity:!1,legend:{position:gvjs_b},hAxis:{textPosition:gvjs_Gs},vAxis:{textPosition:gvjs_b,gridlines:{color:gvjs_b}}},gvjs_Wia={chartArea:{left:"0",width:gvjs_ho},enableInteractivity:!1,legend:{position:gvjs_b},vAxis:{textPosition:gvjs_Gs},hAxis:{textPosition:gvjs_b,gridlines:{color:gvjs_b}}};
function gvjs_DQ(a){gvjs_dz.call(this,a);this.Gd={};this.ba=null;this.Ck={yu:!1};this.rH=this.TJ=this.aa=this.C=this.Jg=this.ga=this.xk=this.R=null;this.RJ=50;this.Nba=0;this.FQ=1;this.zV=this.Y2=this.iU=!1;this.nQ=this.zQ=this.JX=this.M2=null;this.Qf=!1;this.Ic=null;this.K={range:null,FN:null,th:null};this.Ij={gl:{min:0,max:0},value:{min:0,max:0}};this.XU=null;this.bW=!1;this.Au=null}gvjs_l(gvjs_DQ,gvjs_dz);gvjs_=gvjs_DQ.prototype;
gvjs_.draw=function(a,b,c){this.Qb();gvjs_bz(a);this.R=a;this.xk=gvjs_NE(a.Y(0));null==this.TJ&&(this.TJ=new gvjs_0J(gvjs_k(this.xya,this)));null==this.rH&&(this.rH=new gvjs_0J(gvjs_k(this.a4,this,!0)));b=new gvjs__d([b||{}]);this.gp(b);this.Ic=this.z9(b);c=c||{};if(!this.ba){switch(gvjs_r(b,gvjs_oQ,gvjs_Ue,gvjs_Tia)){case gvjs_Le:b=new gvjs_tQ(this.container);break;case gvjs_Ue:b=new gvjs_IK(this.container);break;case gvjs_bf:b=new gvjs_xQ(this.container);break;case gvjs_7e:b=new gvjs_wQ(this.container);
break;default:b=new gvjs_IK(this.container)}this.ba=b;gvjs_Qk(this.ba,gvjs_x,gvjs_k(this.Sta,this,c))}this.iU&&(this.zQ=this.R.getValue(0,0),this.nQ=this.R.getValue(Math.max(0,this.R.ca()-1),0),b={min:this.zQ,max:this.nQ},c.range&&gvjs_EQ(this,b,c.range),this.Ic.domainAxis=this.Ic.domainAxis||{},this.Ic.domainAxis.viewWindow=b);this.ba.draw(a,this.Ic)};
gvjs_.gp=function(a){this.RJ=gvjs_ce(a,"rangeChangeEventFiringRate",50);this.Nba=gvjs_ce(a,"minRangeSize",0);this.vX=gvjs_s(a,"fixedRangeSize",!1);this.iU=gvjs_s(a,"zoomAroundSelection",!1);this.Y2=gvjs_s(a,"snapToData",!1);this.zV=gvjs_s(a,"centerSelectionAroundData",!1);this.M2=gvjs_Ow(a,"sideScreenColor",new gvjs_1(gvjs_Uia));this.JX=new gvjs_1(gvjs_ow);this.Qf=gvjs_r(a,gvjs_Pt,gvjs_X,gvjs_HF)==gvjs__};gvjs_.z9=function(a){a=gvjs_Mi(a.nb("chartOptions"));a.theme=this.Qf?gvjs_Wia:gvjs_Via;return a};
function gvjs_Xia(a,b){var c=gvjs_mE(a.ca(),function(d){return a.getValue(d,0)});c=gvjs_Db(c,function(d){return null!=d});return gvjs_n(c,b)}gvjs_.Sta=function(a){gvjs_Tk(this.ba);this.Ck={yu:!0};gvjs_FQ(this,a);gvjs_H(this.C);this.C=this.ba.Ra.$a(1);gvjs_H(this.aa);this.aa=new gvjs_jz;gvjs_Yia(this)};gvjs_.zca=function(a){gvjs_Tk(this.ba);gvjs_FQ(this,a);gvjs_GQ(this,gvjs_aq)};
function gvjs_FQ(a,b){a.ga=a.ba.Rl();a.Jg=a.Qf?a.ga.Uc[0]:a.ga.Ed[0];a.Ij.gl={min:Math.min(a.Jg.Yf,a.Jg.nf),max:Math.max(a.Jg.Yf,a.Jg.nf)};var c=a.Ij,d=a.Jg.position.tl(a.Jg.Yf),e=a.Jg.position.tl(a.Jg.nf);c.value={min:Math.min(d,e),max:Math.max(d,e)};c=a.Nba;if(0>=c)a.FQ=1;else{d=a.Ij.gl.min;e=a.Jg.position.tl(d);if(gvjs_wb(e)){var f=new Date;f.setTime(e.getTime()+c)}else f=e+c;c=Math.ceil(Math.abs(a.Jg.position.rf(f)-d));c=Math.max(c,1);a.FQ=c<a.Ij.gl.max-a.Ij.gl.min?c:1}if(a.Y2||a.zV)c=a.Jg,d=
gvjs_Xia(a.R,c.position.rf),c=a.Qf?1==c.vo?d.reverse():d:1==c.vo?d:d.reverse(),a.XU=c;b&&(b=b.range,a.K.range=gvjs_HQ(a,gvjs_i(b)?b.start:null,gvjs_i(b)?b.end:null))}
function gvjs_Yia(a){var b=a.C,c=a.ga,d=b.Sm(c.width,c.height),e=b.Qa(!1);b.appendChild(d,e);d=c.N;b.sb(0,0,c.width,c.height,a.JX,e);c=b.sb(d.left,d.top,d.width,d.height,a.JX,e);var f=gvjs_IQ(a);f=b.sb(f.left,f.top,f.width,f.height,a.M2,e);a.Gd.rangeSelectorMinScreen=f;f=gvjs_JQ(a);f=b.sb(f.left,f.top,f.width,f.height,a.M2,e);a.Gd.rangeSelectorMaxScreen=f;f=gvjs_KQ(a,a.K.range.$h,d,b,e);a.Gd.rangeSelectorMinHandle=f;b=gvjs_KQ(a,a.K.range.Zh,d,b,e);a.Gd.rangeSelectorMaxHandle=b;var g=gvjs_Fc(a.container);
a.aa.D(g.body,gvjs_Ng,gvjs_k(a.vpa,a,a.Ck));a.aa.D(g.body,gvjs_Qg,gvjs_k(a.ZO,a,a.Ck));e=e.j();a.aa.D(e,gvjs_Ng,gvjs_k(a.zqa,a,a.Ck));a.aa.D(e,gvjs_Og,gvjs_k(a.VH,a,a.Ck,{type:gvjs_xu,To:!1}));a.bW=gvjs_2c(e,function(h){return h==g.body});a.bW||a.aa.D(e,gvjs_Qg,gvjs_k(a.ZO,a,a.Ck));a.vX||(gvjs_LQ(a,f,gvjs_qt,gvjs_qt),gvjs_LQ(a,b,gvjs_ht,gvjs_ht));a.aa.D(c,gvjs_Kg,gvjs_k(a.qC,a,a.Ck,{th:gvjs_aq}));a.aa.D(c,gvjs_Pg,gvjs_k(a.VH,a,a.Ck,{type:gvjs_xu,To:!0}));a.aa.D(c,gvjs_Og,gvjs_k(a.VH,a,a.Ck,{type:gvjs_xu,
To:!1}));gvjs_K(a,gvjs_x,null)}function gvjs_LQ(a,b,c,d){a.aa.D(b,gvjs_Kg,gvjs_k(a.qC,a,a.Ck,{th:d}));a.aa.D(b,gvjs_Pg,gvjs_k(a.VH,a,a.Ck,{type:c,To:!0}));a.aa.D(b,gvjs_Og,gvjs_k(a.VH,a,a.Ck,{type:c,To:!1}))}
function gvjs_KQ(a,b,c,d,e){var f=d.Qa(!1);d.appendChild(e,f);e=.5*gvjs_KK.width;var g=.5*gvjs_KK.height,h=a.Qf?c.left:Math.floor(b-e)+.5;b=a.Qf?Math.floor(b-g)+.5:c.top;d.tp(f.j(),h,b);a.Qf?(b=Math.round(g),b=gvjs_5z(a.Qf?[{x:0,y:b},{x:0+c.width,y:b}]:[{x:0,y:b},{x:0,y:b+c.height}]),d.Ia(b,gvjs_JK,f),a.vX||gvjs_MQ(a,.5*(c.width-gvjs_KK.height),0,gvjs_KK.height,gvjs_KK.width,d,f)):(b=Math.round(e),b=gvjs_5z(a.Qf?[{x:b,y:0},{x:b+c.width,y:0}]:[{x:b,y:0},{x:b,y:0+c.height}]),d.Ia(b,gvjs_JK,f),a.vX||
gvjs_MQ(a,0,.5*(c.height-gvjs_KK.height),gvjs_KK.width,gvjs_KK.height,d,f));return f.j()}function gvjs_MQ(a,b,c,d,e,f,g){d=b+d;e=c+e;var h=gvjs_5z([{x:b+3,y:c},{x:d-3,y:c},{x:d,y:c+3},{x:d,y:e-3},{x:d-3,y:e},{x:b+3,y:e},{x:b,y:e-3},{x:b,y:c+3}],!1);f.Ia(h,gvjs_JK,g);a.Qf?(a=gvjs_5z([{x:b+4,y:c+4},{x:d-4,y:c+4}]),b=gvjs_5z([{x:b+4,y:e-4},{x:d-4,y:e-4}])):(a=gvjs_5z([{x:b+4,y:c+4},{x:b+4,y:e-4}]),b=gvjs_5z([{x:d-4,y:c+4},{x:d-4,y:e-4}]));f.Ia(a,gvjs_JK,g);f.Ia(b,gvjs_JK,g)}
function gvjs_IQ(a){var b=a.ga.N,c=a.K.range.$h;return a.Qf?new gvjs_3(b.left,b.top,b.width,c-b.top):new gvjs_3(b.left,b.top,c-b.left,b.height)}function gvjs_JQ(a){var b=a.ga.N,c=a.K.range.Zh;return a.Qf?new gvjs_3(b.left,c,b.width,b.bottom-c):new gvjs_3(c,b.top,b.right-c,b.height)}
function gvjs_HQ(a,b,c){var d=a.Ij.gl.min,e=a.Ij.gl.max,f=1==a.Jg.vo&&!a.Qf;null!=b&&(b=a.Jg.position.rf(b),f?d=Math.max(b,d):e=Math.min(b,e));null!=c&&(a=a.Jg.position.rf(c),f?e=Math.min(a,e):d=Math.max(a,d));return{$h:d,Zh:e}}gvjs_.AO=function(){var a=this.K.range,b=this.Jg.position.tl(a.$h);a=this.Jg.position.tl(a.Zh);var c=1==this.Jg.vo&&!this.Qf;return{start:c?b:a,end:c?a:b}};
gvjs_.nwa=function(a,b){if(!this.Ck.yu)return!1;var c=this.K.range;if(null==c.$h||null==c.Zh)return!1;a=gvjs_HQ(this,a,b);a=gvjs_NQ(this,a.$h,a.Zh,gvjs_aq);this.K.th=null;return a};function gvjs_NQ(a,b,c,d){var e=a.K.range;if(e.$h==b&&e.Zh==c)return!1;a.K.range={$h:b,Zh:c};gvjs_GQ(a,d);return!0}
function gvjs_GQ(a,b){var c=a.Qf?gvjs_KK.height:gvjs_KK.width,d=a.Qf?gvjs_KK.width:gvjs_KK.height;if(b!=gvjs_ht){var e=gvjs_IQ(a),f=a.Gd.rangeSelectorMinScreen,g=a.Gd.rangeSelectorMinHandle;if(a.Qf){var h=Math.floor(e.top+e.height-.5*d)+.5;a.C.tp(g,0,h);a.C.Wz(f,e.top);a.C.jl(f,e.height)}else h=Math.floor(e.left+e.width-.5*c)+.5,a.C.tp(g,h,0),a.C.Sz(f,e.left),a.C.dh(f,e.width)}b!=gvjs_qt&&(b=gvjs_JQ(a),e=a.Gd.rangeSelectorMaxScreen,f=a.Gd.rangeSelectorMaxHandle,a.Qf?(h=Math.floor(b.top-.5*d)+.5,a.C.tp(f,
0,h),a.C.Wz(e,b.top),a.C.jl(e,b.height)):(h=Math.floor(b.left-.5*c)+.5,a.C.tp(f,h,0),a.C.Sz(e,b.left),a.C.dh(e,b.width)))}gvjs_.xya=function(){gvjs_GQ(this,this.K.th)};function gvjs_OQ(a){var b=a.Ij.gl.max-a.Ij.gl.min,c=a.Jg.vo,d=(a.K.range.$h-a.Ij.gl.min)/b;if(.1>d)return{direction:-1*c,ratio:d/.1};a=(a.Ij.gl.max-a.K.range.Zh)/b;return.1>a?{direction:1*c,ratio:a/.1}:null}
function gvjs_PQ(a){if(a.iU){var b=!1;a.K.th==gvjs_aq&&gvjs_OQ(a)&&(b=!0);b&&!a.Au?(a.Au=new gvjs_az(a.RJ),a.aa.D(a.Au,gvjs_nv,gvjs_k(a.Voa,a)),a.Au.start(),gvjs_Mk(a.ba,gvjs_x,gvjs_k(a.zca,a,null))):!b&&a.Au&&(gvjs_H(a.Au),a.Au=null)}}
gvjs_.Voa=function(){if(this.Au){var a=gvjs_OQ(this),b=this.RJ/gvjs_Dx(1E3,6E4,a.ratio),c=this.xk.toNumber(this.zQ),d=this.xk.toNumber(this.nQ),e=(d-c)*b;b=this.Ic.domainAxis.viewWindow;var f=b.max,g=this.xk.toNumber(b.min);f=this.xk.toNumber(f);0>a.direction?(a=Math.max(g-e,c),c=f-(g-a)):(c=Math.min(f+e,d),a=g+(c-f));d=this.xk.ly(a);e=this.xk.ly(c);if(g!=a||f!=c)b.min=d,b.max=e,this.ba.draw(this.R,this.Ic),this.a4(!0)}};
gvjs_.zqa=function(a,b){a.yu&&null!=this.K.th&&(this.bW||gvjs_QQ(this,b),b.target.style.cursor=gvjs_zt)};gvjs_.vpa=function(a,b){a.yu&&null!=this.K.th&&gvjs_QQ(this,b)};
function gvjs_QQ(a,b){var c=a.K;c.range&&null!=c.range.$h&&null!=c.range.Zh||(c.range={$h:a.Ij.gl.min,Zh:a.Ij.gl.max});b=gvjs_Ly(b);b=(a.Qf?b.y:b.x)-c.FN;var d=a.K.range,e=a.Ij.gl;switch(a.K.th){case gvjs_aq:var f=e.min-d.$h;var g=e.max-d.Zh;break;case gvjs_qt:f=e.min-d.$h;g=d.Zh-a.FQ-d.$h;break;case gvjs_ht:f=d.$h+a.FQ-d.Zh,g=e.max-d.Zh}f=gvjs_Cc(b,f,g);c.FN+=f;c.th!=gvjs_ht&&(c.range.$h+=f);c.th!=gvjs_qt&&(c.range.Zh+=f);gvjs_PQ(a);gvjs_1J(a.TJ,a.RJ);gvjs_1J(a.rH,a.RJ)}
gvjs_.qC=function(a,b,c){if(a.yu&&gvjs_Tw(c)){a=gvjs_Ly(c);var d=this.K;d.FN=this.Qf?a.y:a.x;d.th=b.th;gvjs_PQ(this);c.preventDefault();c.stopPropagation()}};
gvjs_.ZO=function(a){if(a.yu&&(a=this.K,null!==a.th)){if(this.Y2){var b=this.XU;var c=a.range.Zh;var d=gvjs_rQ(b,a.range.$h);c=gvjs_rQ(b,c);gvjs_NQ(this,d,c,a.th)}else if(this.zV){var e=new gvjs_F(a.range.$h,a.range.Zh);d=e.end-e.start;c=this.Ij.gl;var f=b=this.XU,g=gvjs_k(gvjs_Gi,null,e);b=gvjs_vh(f,g);g=gvjs_8w(f,g);if(null===b||null===g)b=gvjs_rQ(f,e.start),f=gvjs_rQ(f,e.end),g=b=f=Math.abs(e.start-b)<=Math.abs(e.end-f)?b:f;e=e.end-e.start;b=gvjs_Lx(b,g)-e/2;e=new gvjs_F(b,b+e);e.start=Math.max(e.start,
c.min);e.end=e.start+d;e.end=Math.min(e.end,c.max);e.start=e.end-d;gvjs_NQ(this,e.start,e.end,a.th)}else this.iU&&a.th!=gvjs_aq&&(c=this.Ic.domainAxis.viewWindow,d=this.AO(),c=gvjs_EQ(this,c,d))&&(gvjs_Mk(this.ba,gvjs_x,gvjs_k(this.zca,this,{range:d})),this.ba.draw(this.R,this.Ic));this.a4(!1);a.th=null;gvjs_PQ(this)}};
function gvjs_EQ(a,b,c){var d=b.max,e=a.xk.toNumber(b.min);d=a.xk.toNumber(d);var f=d-e;0===f&&(--e,d+=1,f=2);var g=c.start;c=c.end;if(null==g||null==c)return!1;var h=a.xk.toNumber(g),k=a.xk.toNumber(c);c=k-h;g=.1*f;var l=.6*f;if(c>=g&&c<=l)return!1;h=(h+k)/2;f/=(c<g?.9*l:1.1*g)/c;f=new gvjs_F(h-f/2,h+f/2);c<g?gvjs_RQ(f,new gvjs_F(e,d)):(c=a.xk.toNumber(a.zQ),g=a.xk.toNumber(a.nQ),gvjs_RQ(f,new gvjs_F(c,g)));c=a.xk.ly(f.start);a=a.xk.ly(f.end);e=e!=f.start||d!=f.end;b.min=c;b.max=a;return e}
function gvjs_RQ(a,b){a.start<b.start&&(a.end+=b.start-a.start,a.start=b.start);a.end>b.end&&(a.start-=a.end-b.end,a.end=b.end);a.start<b.start&&(a.start=b.start)}gvjs_.VH=function(a,b,c){a.yu&&!this.K.th&&(c.target.style.cursor=b.To?b.type==gvjs_xu?gvjs_zt:this.Qf?"row-resize":gvjs_pQ:gvjs_er)};
gvjs_.a4=function(a){var b=this.K.th,c=this.AO();if(null!=b&&null!=c){var d=this.Jg.vo;gvjs_K(this,gvjs_eu,{start:c.start,end:c.end,startChanged:b==(1==d?gvjs_qt:gvjs_ht)||b==gvjs_aq,endChanged:b==(1==d?gvjs_ht:gvjs_qt)||b==gvjs_aq,inProgress:a})}};gvjs_.Qb=function(){this.ba&&(gvjs_Tk(this.ba),gvjs_H(this.TJ),this.TJ=null,gvjs_H(this.rH),this.rH=null,this.Ck.yu=!1,gvjs_H(this.C),this.C=null,gvjs_H(this.aa),this.aa=null,this.ba.Qb(),this.ba=null,gvjs_$i(this),this.Gd={})};gvjs_g(gvjs_Yf,gvjs_zK,void 0);
gvjs_zK.prototype.draw=gvjs_zK.prototype.draw;gvjs_zK.prototype.clearChart=gvjs_zK.prototype.Qb;gvjs_zK.prototype.getImageURI=gvjs_zK.prototype.Tj;gvjs_zK.prototype.getSelection=gvjs_zK.prototype.getSelection;gvjs_zK.prototype.setSelection=gvjs_zK.prototype.setSelection;gvjs_zK.prototype.dump=gvjs_zK.prototype.dump;gvjs_zK.prototype.getChartLayoutInterface=gvjs_zK.prototype.wq;gvjs_zK.prototype.getContainer=gvjs_zK.prototype.getContainer;gvjs_zK.prototype.setAction=gvjs_zK.prototype.sj;
gvjs_zK.prototype.getAction=gvjs_zK.prototype.ph;gvjs_zK.prototype.removeAction=gvjs_zK.prototype.oj;gvjs_g(gvjs_Of,gvjs_tQ,void 0);gvjs_tQ.prototype.draw=gvjs_tQ.prototype.draw;gvjs_tQ.prototype.clearChart=gvjs_tQ.prototype.Qb;gvjs_tQ.prototype.getImageURI=gvjs_tQ.prototype.Tj;gvjs_tQ.prototype.getSelection=gvjs_tQ.prototype.getSelection;gvjs_tQ.prototype.setSelection=gvjs_tQ.prototype.setSelection;gvjs_tQ.prototype.setAction=gvjs_tQ.prototype.sj;gvjs_tQ.prototype.getAction=gvjs_tQ.prototype.ph;
gvjs_tQ.prototype.removeAction=gvjs_tQ.prototype.oj;gvjs_g(gvjs_Pf,gvjs_zQ,void 0);gvjs_zQ.prototype.computeDiff=gvjs_zQ.prototype.aq;gvjs_zQ.prototype.draw=gvjs_zQ.prototype.draw;gvjs_zQ.prototype.clearChart=gvjs_zQ.prototype.Qb;gvjs_zQ.prototype.getImageURI=gvjs_zQ.prototype.Tj;gvjs_zQ.prototype.getSelection=gvjs_zQ.prototype.getSelection;gvjs_zQ.prototype.setSelection=gvjs_zQ.prototype.setSelection;gvjs_zQ.prototype.setAction=gvjs_zQ.prototype.sj;gvjs_zQ.prototype.getAction=gvjs_zQ.prototype.ph;
gvjs_zQ.prototype.removeAction=gvjs_zQ.prototype.oj;gvjs_g(gvjs_Qf,gvjs_yQ,void 0);gvjs_yQ.prototype.draw=gvjs_yQ.prototype.draw;gvjs_yQ.prototype.clearChart=gvjs_yQ.prototype.Qb;gvjs_yQ.prototype.getImageURI=gvjs_yQ.prototype.Tj;gvjs_yQ.prototype.getSelection=gvjs_yQ.prototype.getSelection;gvjs_yQ.prototype.setSelection=gvjs_yQ.prototype.setSelection;gvjs_yQ.prototype.setAction=gvjs_yQ.prototype.sj;gvjs_yQ.prototype.getAction=gvjs_yQ.prototype.ph;gvjs_yQ.prototype.removeAction=gvjs_yQ.prototype.oj;
gvjs_g(gvjs_Rf,gvjs_AQ,void 0);gvjs_AQ.prototype.draw=gvjs_AQ.prototype.draw;gvjs_AQ.prototype.clearChart=gvjs_AQ.prototype.Qb;gvjs_AQ.prototype.getImageURI=gvjs_AQ.prototype.Tj;gvjs_AQ.prototype.getSelection=gvjs_AQ.prototype.getSelection;gvjs_AQ.prototype.setSelection=gvjs_AQ.prototype.setSelection;gvjs_AQ.prototype.setAction=gvjs_AQ.prototype.sj;gvjs_AQ.prototype.getAction=gvjs_AQ.prototype.ph;gvjs_AQ.prototype.removeAction=gvjs_AQ.prototype.oj;gvjs_g(gvjs_6f,gvjs_CQ,void 0);
gvjs_CQ.prototype.draw=gvjs_CQ.prototype.draw;gvjs_CQ.prototype.clearChart=gvjs_CQ.prototype.Qb;gvjs_CQ.prototype.getImageURI=gvjs_CQ.prototype.Tj;gvjs_CQ.prototype.getSelection=gvjs_CQ.prototype.getSelection;gvjs_CQ.prototype.setSelection=gvjs_CQ.prototype.setSelection;gvjs_CQ.prototype.setAction=gvjs_CQ.prototype.sj;gvjs_CQ.prototype.getAction=gvjs_CQ.prototype.ph;gvjs_CQ.prototype.removeAction=gvjs_CQ.prototype.oj;gvjs_g(gvjs_Wf,gvjs_BQ,void 0);gvjs_BQ.prototype.computeDiff=gvjs_BQ.prototype.aq;
gvjs_BQ.prototype.draw=gvjs_BQ.prototype.draw;gvjs_BQ.prototype.clearChart=gvjs_BQ.prototype.Qb;gvjs_BQ.prototype.getImageURI=gvjs_BQ.prototype.Tj;gvjs_BQ.prototype.getSelection=gvjs_BQ.prototype.getSelection;gvjs_BQ.prototype.setSelection=gvjs_BQ.prototype.setSelection;gvjs_BQ.prototype.setAction=gvjs_BQ.prototype.sj;gvjs_BQ.prototype.getAction=gvjs_BQ.prototype.ph;gvjs_BQ.prototype.removeAction=gvjs_BQ.prototype.oj;gvjs_g(gvjs_Xf,gvjs_IK,void 0);gvjs_IK.prototype.draw=gvjs_IK.prototype.draw;
gvjs_IK.prototype.clearChart=gvjs_IK.prototype.Qb;gvjs_IK.prototype.getImageURI=gvjs_IK.prototype.Tj;gvjs_IK.prototype.getSelection=gvjs_IK.prototype.getSelection;gvjs_IK.prototype.setSelection=gvjs_IK.prototype.setSelection;gvjs_IK.prototype.setAction=gvjs_IK.prototype.sj;gvjs_IK.prototype.getAction=gvjs_IK.prototype.ph;gvjs_IK.prototype.removeAction=gvjs_IK.prototype.oj;gvjs_g(gvjs_dg,gvjs_wQ,void 0);gvjs_wQ.prototype.draw=gvjs_wQ.prototype.draw;gvjs_wQ.prototype.clearChart=gvjs_wQ.prototype.Qb;
gvjs_wQ.prototype.getImageURI=gvjs_wQ.prototype.Tj;gvjs_wQ.prototype.getSelection=gvjs_wQ.prototype.getSelection;gvjs_wQ.prototype.setSelection=gvjs_wQ.prototype.setSelection;gvjs_wQ.prototype.setAction=gvjs_wQ.prototype.sj;gvjs_wQ.prototype.getAction=gvjs_wQ.prototype.ph;gvjs_wQ.prototype.removeAction=gvjs_wQ.prototype.oj;gvjs_g(gvjs_jg,gvjs_AK,void 0);gvjs_AK.prototype.computeDiff=gvjs_AK.prototype.aq;gvjs_AK.prototype.draw=gvjs_AK.prototype.draw;gvjs_AK.prototype.clearChart=gvjs_AK.prototype.Qb;
gvjs_AK.prototype.getImageURI=gvjs_AK.prototype.Tj;gvjs_AK.prototype.getSelection=gvjs_AK.prototype.getSelection;gvjs_AK.prototype.setSelection=gvjs_AK.prototype.setSelection;gvjs_AK.prototype.setAction=gvjs_AK.prototype.sj;gvjs_AK.prototype.getAction=gvjs_AK.prototype.ph;gvjs_AK.prototype.removeAction=gvjs_AK.prototype.oj;gvjs_g(gvjs_mg,gvjs_xQ,void 0);gvjs_xQ.prototype.computeDiff=gvjs_xQ.prototype.aq;gvjs_xQ.prototype.draw=gvjs_xQ.prototype.draw;gvjs_xQ.prototype.clearChart=gvjs_xQ.prototype.Qb;
gvjs_xQ.prototype.getImageURI=gvjs_xQ.prototype.Tj;gvjs_xQ.prototype.getSelection=gvjs_xQ.prototype.getSelection;gvjs_xQ.prototype.setSelection=gvjs_xQ.prototype.setSelection;gvjs_xQ.prototype.setAction=gvjs_xQ.prototype.sj;gvjs_xQ.prototype.getAction=gvjs_xQ.prototype.ph;gvjs_xQ.prototype.removeAction=gvjs_xQ.prototype.oj;gvjs_g(gvjs_ng,gvjs_vQ,void 0);gvjs_vQ.prototype.draw=gvjs_vQ.prototype.draw;gvjs_vQ.prototype.clearChart=gvjs_vQ.prototype.Qb;gvjs_vQ.prototype.getImageURI=gvjs_vQ.prototype.Tj;
gvjs_vQ.prototype.getSelection=gvjs_vQ.prototype.getSelection;gvjs_vQ.prototype.setSelection=gvjs_vQ.prototype.setSelection;gvjs_vQ.prototype.setAction=gvjs_vQ.prototype.sj;gvjs_vQ.prototype.getAction=gvjs_vQ.prototype.ph;gvjs_vQ.prototype.removeAction=gvjs_vQ.prototype.oj;gvjs_g(gvjs_og,gvjs_uQ,void 0);gvjs_uQ.prototype.draw=gvjs_uQ.prototype.draw;gvjs_uQ.prototype.clearChart=gvjs_uQ.prototype.Qb;gvjs_uQ.prototype.getImageURI=gvjs_uQ.prototype.Tj;gvjs_uQ.prototype.getSelection=gvjs_uQ.prototype.getSelection;
gvjs_uQ.prototype.setSelection=gvjs_uQ.prototype.setSelection;gvjs_uQ.prototype.setAction=gvjs_uQ.prototype.sj;gvjs_uQ.prototype.getAction=gvjs_uQ.prototype.ph;gvjs_uQ.prototype.removeAction=gvjs_uQ.prototype.oj;gvjs_g("google.visualization.RangeSelector",gvjs_DQ,void 0);gvjs_DQ.prototype.draw=gvjs_DQ.prototype.draw;gvjs_DQ.prototype.clearChart=gvjs_DQ.prototype.Qb;gvjs_DQ.prototype.getRange=gvjs_DQ.prototype.AO;gvjs_DQ.prototype.setRange=gvjs_DQ.prototype.nwa;gvjs_Ei(gvjs_v);function gvjs_SQ(a){return(new gvjs_nk).qd().sanitize(a)};
