/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gvjs_aa="#000000",gvjs_ba="#808080",gvjs_ca="#ffffff",gvjs_da=", ",gvjs_ea="0000000000000000",gvjs_fa="<br>",gvjs_ga="April",gvjs_ha="August",gvjs_ia="Can't combine significant digits and minimum fraction digits",gvjs_ja="December",gvjs_ka="Edge",gvjs_la="February",gvjs_ma="Friday",gvjs_na="IFRAME",gvjs_oa="INPUT",gvjs_pa="Inconsistent use of percent/permill characters",gvjs_qa="January",gvjs_ra="Map",gvjs_sa="March",gvjs_ta="May",gvjs_ua="Monday",gvjs_va="November",gvjs_wa="OBJECT",gvjs_xa="October",
gvjs_ya="SCRIPT",gvjs_za="SOURCE",gvjs_Aa="STYLE",gvjs_Ba="Saturday",gvjs_Ca="September",gvjs_Da="Sunday",gvjs_Ea="Thursday",gvjs_Fa="Too many percent/permill",gvjs_Ga="Tuesday",gvjs_Ha="Wednesday",gvjs_Ia="_bar_format_old_value",gvjs_Ja="array",gvjs_Ka="background-color:",gvjs_La="boolean",gvjs_Ma="class",gvjs_Na="className",gvjs_Oa="color:",gvjs_Pa="date",gvjs_Qa="datetime",gvjs_Ra="div",gvjs_Sa="false",gvjs_Ta="full",gvjs_a="function",gvjs_Ua="google.visualization.NumberFormat",gvjs_Va="height",
gvjs_Wa="medium",gvjs_b="none",gvjs_Xa="null",gvjs_c="number",gvjs_Ya="object",gvjs_Za="pattern",gvjs__a="prefix",gvjs_0a="role",gvjs_1a="short",gvjs_d="string",gvjs_2a="style",gvjs_3a="suffix",gvjs_4a="timeofday",gvjs_5a="transparent",gvjs_6a="true",gvjs_7a="type",gvjs_8a="width",gvjs_9a="{1} 'at' {0}",gvjs_$a="{1}, {0}",gvjs_,gvjs_ab=[];function gvjs_e(a){return function(){return gvjs_ab[a].apply(this,arguments)}}
function gvjs_bb(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function gvjs_cb(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:gvjs_bb(a)}}var gvjs_aaa=typeof Object.create==gvjs_a?Object.create:function(a){function b(){}b.prototype=a;return new b},gvjs_db;
if(typeof Object.setPrototypeOf==gvjs_a)gvjs_db=Object.setPrototypeOf;else{var gvjs_eb;a:{var gvjs_baa={a:!0},gvjs_fb={};try{gvjs_fb.__proto__=gvjs_baa;gvjs_eb=gvjs_fb.a;break a}catch(a){}gvjs_eb=!1}gvjs_db=gvjs_eb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var gvjs_gb=gvjs_db,gvjs_hb=typeof Object.defineProperties==gvjs_a?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function gvjs_caa(a){a=[gvjs_Ya==typeof window&&window,gvjs_Ya==typeof self&&self,gvjs_Ya==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var gvjs_ib=gvjs_caa(this);function gvjs_jb(){gvjs_jb=function(){};gvjs_ib.Symbol||(gvjs_ib.Symbol=gvjs_daa)}function gvjs_kb(a,b){this.fha=a;gvjs_hb(this,"description",{configurable:!0,writable:!0,value:b})}gvjs_kb.prototype.toString=function(){return this.fha};
var gvjs_daa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new gvjs_kb("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function gvjs_lb(){gvjs_jb();var a=gvjs_ib.Symbol.iterator;a||(a=gvjs_ib.Symbol.iterator=gvjs_ib.Symbol("Symbol.iterator"));typeof Array.prototype[a]!=gvjs_a&&gvjs_hb(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return gvjs_mb(gvjs_bb(this))}});gvjs_lb=function(){}}
function gvjs_mb(a){gvjs_lb();a={next:a};a[gvjs_ib.Symbol.iterator]=function(){return this};return a}function gvjs_nb(a,b){if(b){var c=gvjs_ib;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&gvjs_hb(c,a,{configurable:!0,writable:!0,value:b})}}gvjs_nb("globalThis",function(a){return a||gvjs_ib});
function gvjs_ob(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{yb:e,v:f}}return{yb:-1,v:void 0}}gvjs_nb("Array.prototype.findIndex",function(a){return a?a:function(b,c){return gvjs_ob(this,b,c).yb}});gvjs_nb("Array.prototype.find",function(a){return a?a:function(b,c){return gvjs_ob(this,b,c).v}});
function gvjs_pb(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
gvjs_nb("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=gvjs_pb(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});gvjs_nb("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=gvjs_pb(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
gvjs_nb("String.prototype.repeat",function(a){return a?a:function(b){var c=gvjs_pb(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
gvjs_nb("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if(typeof f==gvjs_a){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
gvjs_nb("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function gvjs_qb(a,b){gvjs_lb();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
gvjs_nb("Array.prototype.keys",function(a){return a?a:function(){return gvjs_qb(this,function(b){return b})}});
gvjs_nb("Promise",function(a){function b(g){this.K=0;this.pm=void 0;this.wD=[];var h=this.oW();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.Cu=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.e6=function(g){if(null==this.Cu){this.Cu=[];var h=this;this.f6(function(){h.una()})}this.Cu.push(g)};var e=gvjs_ib.setTimeout;c.prototype.f6=function(g){e(g,0)};c.prototype.una=function(){for(;this.Cu&&this.Cu.length;){var g=this.Cu;this.Cu=[];
for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.Xja(l)}}}this.Cu=null};c.prototype.Xja=function(g){this.f6(function(){throw g;})};b.prototype.oW=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.vva),reject:g(this.p1)}};b.prototype.vva=function(g){if(g===this)this.p1(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.wwa(g);else{a:switch(typeof g){case gvjs_Ya:var h=null!=g;break a;case gvjs_a:h=
!0;break a;default:h=!1}h?this.uva(g):this.s9(g)}};b.prototype.uva=function(g){var h=void 0;try{h=g.then}catch(k){this.p1(k);return}typeof h==gvjs_a?this.xwa(h,g):this.s9(g)};b.prototype.p1=function(g){this.Xea(2,g)};b.prototype.s9=function(g){this.Xea(1,g)};b.prototype.Xea=function(g,h){if(0!=this.K)throw Error("Cannot settle("+g+gvjs_da+h+"): Promise already settled in state"+this.K);this.K=g;this.pm=h;this.wna()};b.prototype.wna=function(){if(null!=this.wD){for(var g=0;g<this.wD.length;++g)f.e6(this.wD[g]);
this.wD=null}};var f=new c;b.prototype.wwa=function(g){var h=this.oW();g.yM(h.resolve,h.reject)};b.prototype.xwa=function(g,h){var k=this.oW();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(p,q){return typeof p==gvjs_a?function(r){try{l(p(r))}catch(t){m(t)}}:q}var l,m,n=new b(function(p,q){l=p;m=q});this.yM(k(g,l),k(h,m));return n};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.yM=function(g,h){function k(){switch(l.K){case 1:g(l.pm);
break;case 2:h(l.pm);break;default:throw Error("Unexpected state: "+l.K);}}var l=this;null==this.wD?f.e6(k):this.wD.push(k)};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=gvjs_cb(g),m=l.next();!m.done;m=l.next())d(m.value).yM(h,k)})};b.all=function(g){var h=gvjs_cb(g),k=h.next();return k.done?d([]):new b(function(l,m){function n(r){return function(t){p[r]=t;q--;0==q&&l(p)}}var p=[],q=0;do p.push(void 0),q++,d(k.value).yM(n(p.length-
1),m),k=h.next();while(!k.done)})};return b});function gvjs_rb(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
gvjs_nb("WeakMap",function(a){function b(k){this.Sb=(h+=Math.random()+1).toString();if(k){k=gvjs_cb(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l===gvjs_Ya&&null!==k||l===gvjs_a}function e(k){if(!gvjs_rb(k,g)){var l=new c;gvjs_hb(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(n){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!gvjs_rb(k,g))throw Error("WeakMap key fail: "+k);k[g][this.Sb]=l;return this};b.prototype.get=function(k){return d(k)&&gvjs_rb(k,g)?k[g][this.Sb]:void 0};b.prototype.has=function(k){return d(k)&&
gvjs_rb(k,g)&&gvjs_rb(k[g],this.Sb)};b.prototype.delete=function(k){return d(k)&&gvjs_rb(k,g)&&gvjs_rb(k[g],this.Sb)?delete k[g][this.Sb]:!1};return b});gvjs_nb("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)gvjs_rb(b,d)&&c.push(b[d]);return c}});gvjs_nb("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
gvjs_nb("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});var gvjs_eaa=typeof Object.assign==gvjs_a?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)gvjs_rb(d,e)&&(a[e]=d[e])}return a};gvjs_nb("Object.assign",function(a){return a||gvjs_eaa});
gvjs_nb("Array.prototype.entries",function(a){return a?a:function(){return gvjs_qb(this,function(b,c){return[b,c]})}});gvjs_nb("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)gvjs_rb(b,d)&&c.push([d,b[d]]);return c}});
gvjs_nb(gvjs_ra,function(a){function b(){var h={};return h.te=h.next=h.head=h}function c(h,k){var l=h.zc;return gvjs_mb(function(){if(l){for(;l.head!=h.zc;)l=l.te;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l==gvjs_Ya||l==gvjs_a?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h.qa[l];if(m&&gvjs_rb(h.qa,l))for(h=0;h<m.length;h++){var n=m[h];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:h,$c:n}}return{id:l,
list:m,index:-1,$c:void 0}}function e(h){this.qa={};this.zc=b();this.size=0;if(h){h=gvjs_cb(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!=gvjs_a||!a.prototype.entries||typeof Object.seal!=gvjs_a)return!1;try{var h=Object.seal({x:4}),k=new a(gvjs_cb([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=
m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(n){return!1}}())return a;gvjs_lb();var f=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.qa[l.id]=[]);l.$c?l.$c.value=k:(l.$c={next:this.zc,te:this.zc.te,head:this.zc,key:h,value:k},l.list.push(l.$c),this.zc.te.next=l.$c,this.zc.te=l.$c,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.$c&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.qa[h.id],h.$c.te.next=
h.$c.next,h.$c.next.te=h.$c.te,h.$c.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.qa={};this.zc=this.zc.te=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).$c};e.prototype.get=function(h){return(h=d(this,h).$c)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,
k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});gvjs_nb("Array.prototype.values",function(a){return a?a:function(){return gvjs_qb(this,function(b,c){return c})}});gvjs_nb("Math.log10",function(a){return a?a:function(b){return Math.log(b)/Math.LN10}});gvjs_nb("Number.isFinite",function(a){return a?a:function(b){return typeof b!==gvjs_c?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});
gvjs_nb("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});gvjs_nb("Math.cbrt",function(a){return a?a:function(b){if(0===b)return b;b=Number(b);var c=Math.pow(Math.abs(b),1/3);return 0>b?-c:c}});gvjs_nb("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
gvjs_nb("Set",function(a){function b(c){this.ta=new Map;if(c){c=gvjs_cb(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.ta.size}if(function(){if(!a||typeof a!=gvjs_a||!a.prototype.entries||typeof Object.seal!=gvjs_a)return!1;try{var c=Object.seal({x:4}),d=new a(gvjs_cb([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=
f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;gvjs_lb();b.prototype.add=function(c){c=0===c?0:c;this.ta.set(c,c);this.size=this.ta.size;return this};b.prototype.delete=function(c){c=this.ta.delete(c);this.size=this.ta.size;return c};b.prototype.clear=function(){this.ta.clear();this.size=0};b.prototype.has=function(c){return this.ta.has(c)};b.prototype.entries=function(){return this.ta.entries()};b.prototype.values=function(){return this.ta.values()};b.prototype.keys=
b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.ta.forEach(function(f){return c.call(d,f,f,e)})};return b});var gvjs_sb=gvjs_sb||{},gvjs_f=this||self;function gvjs_g(a,b,c){a=a.split(".");c=c||gvjs_f;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b}function gvjs_tb(){}
function gvjs_ub(a){var b=typeof a;if(b==gvjs_Ya)if(a){if(a instanceof Array)return gvjs_Ja;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return gvjs_Ya;if("[object Array]"==c||typeof a.length==gvjs_c&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return gvjs_Ja;if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return gvjs_a}else return gvjs_Xa;
else if(b==gvjs_a&&"undefined"==typeof a.call)return gvjs_Ya;return b}function gvjs_h(a){return gvjs_ub(a)==gvjs_Ja}function gvjs_vb(a){var b=gvjs_ub(a);return b==gvjs_Ja||b==gvjs_Ya&&typeof a.length==gvjs_c}function gvjs_wb(a){return gvjs_i(a)&&typeof a.getFullYear==gvjs_a}function gvjs_j(a){return gvjs_ub(a)==gvjs_a}function gvjs_i(a){var b=typeof a;return b==gvjs_Ya&&null!=a||b==gvjs_a}var gvjs_xb="closure_uid_"+(1E9*Math.random()>>>0);
function gvjs_faa(a,b,c){return a.call.apply(a.bind,arguments)}function gvjs_gaa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function gvjs_k(a,b,c){gvjs_k=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?gvjs_faa:gvjs_gaa;return gvjs_k.apply(null,arguments)}function gvjs_yb(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var gvjs_zb=Date.now||function(){return+new Date};
function gvjs_l(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var google=google||window.google||{};var gvjs_Ab;var gvjs_Bb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a===gvjs_d)return typeof b!==gvjs_d||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},gvjs_haa=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if(typeof a===gvjs_d)return typeof b!==gvjs_d||1!=b.length?-1:a.lastIndexOf(b,
c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},gvjs_m=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_d?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function gvjs_Cb(a,b){for(var c=typeof a===gvjs_d?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)}
var gvjs_Db=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=typeof a===gvjs_d?a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},gvjs_n=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=typeof a===gvjs_d?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},gvjs_Eb=Array.prototype.reduce?function(a,
b,c,d){d&&(b=gvjs_k(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;gvjs_m(a,function(f,g){e=b.call(d,e,f,g,a)});return e},gvjs_iaa=Array.prototype.reduceRight?function(a,b,c){return Array.prototype.reduceRight.call(a,b,c)}:function(a,b,c){var d=c;gvjs_Cb(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},gvjs_Fb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_d?a.split(""):a,f=0;f<d;f++)if(f in
e&&b.call(c,e[f],f,a))return!0;return!1},gvjs_Gb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===gvjs_d?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};function gvjs_Hb(a,b){return 0<=gvjs_Bb(a,b)}function gvjs_Ib(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function gvjs_Jb(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c};function gvjs_Kb(a,b){return 0==a.lastIndexOf(b,0)}function gvjs_Lb(a){var b=a.length-1;return 0<=b&&a.indexOf("%",b)==b}function gvjs_Mb(a){return/^[\s\xa0]*$/.test(a)}var gvjs_Nb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function gvjs_Ob(a,b){return-1!=a.indexOf(b)}
function gvjs_Pb(a,b){var c=0;a=gvjs_Nb(String(a)).split(".");b=gvjs_Nb(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=gvjs_Qb(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||gvjs_Qb(0==f[2].length,0==g[2].length)||gvjs_Qb(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c}
function gvjs_Qb(a,b){return a<b?-1:a>b?1:0};var gvjs_Rb;a:{var gvjs_Sb=gvjs_f.navigator;if(gvjs_Sb){var gvjs_Tb=gvjs_Sb.userAgent;if(gvjs_Tb){gvjs_Rb=gvjs_Tb;break a}}gvjs_Rb=""}function gvjs_Ub(a){return gvjs_Ob(gvjs_Rb,a)};function gvjs_o(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function gvjs_Vb(a,b){for(var c in a)if(a[c]==b)return!0;return!1}function gvjs_p(a){var b={},c;for(c in a)b[c]=a[c];return b};function gvjs_Wb(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function gvjs_Xb(a,b){this.Bfa=a===gvjs_Yb&&b||"";this.gja=gvjs_Zb}gvjs_Xb.prototype.Ro=!0;gvjs_Xb.prototype.Yk=function(){return this.Bfa};function gvjs__b(a){return new gvjs_Xb(gvjs_Yb,a)}var gvjs_Zb={},gvjs_Yb={},gvjs_jaa=gvjs__b("");function gvjs_0b(){this.Dda=""}gvjs_0b.prototype.Ro=!0;gvjs_0b.prototype.Yk=function(){return this.Dda.toString()};gvjs_0b.prototype.Zl=function(a){this.Dda=a;return this};(new gvjs_0b).Zl("");function gvjs_1b(){this.a1="";this.Pia=gvjs_2b}gvjs_1b.prototype.Ro=!0;var gvjs_2b={};gvjs_1b.prototype.Yk=function(){return this.a1};gvjs_1b.prototype.Zl=function(a){this.a1=a;return this};var gvjs_3b=(new gvjs_1b).Zl("");function gvjs_4b(){this.$0="";this.Oia=gvjs_5b}gvjs_4b.prototype.Ro=!0;var gvjs_5b={};gvjs_4b.prototype.Yk=function(){return this.$0};gvjs_4b.prototype.Zl=function(a){this.$0=a;return this};var gvjs_6b=(new gvjs_4b).Zl("");function gvjs_7b(){this.Z0="";this.Nia=gvjs_8b;this.f8=null}gvjs_7b.prototype.hZ=!0;gvjs_7b.prototype.nn=gvjs_e(2);gvjs_7b.prototype.Ro=!0;gvjs_7b.prototype.Yk=function(){return this.Z0.toString()};function gvjs_9b(a){if(a instanceof gvjs_7b&&a.constructor===gvjs_7b&&a.Nia===gvjs_8b)return a.Z0;gvjs_ub(a);return"type_error:SafeHtml"}var gvjs_8b={};function gvjs_$b(a,b){return(new gvjs_7b).Zl(a,b)}gvjs_7b.prototype.Zl=function(a,b){this.Z0=a;this.f8=b;return this};gvjs_$b("<!DOCTYPE html>",0);
var gvjs_ac=gvjs_$b("",0),gvjs_bc=gvjs_$b(gvjs_fa,0);var gvjs_kaa=gvjs_Wb(function(){var a=document.createElement(gvjs_Ra),b=document.createElement(gvjs_Ra);b.appendChild(document.createElement(gvjs_Ra));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=gvjs_9b(gvjs_ac);return!b.parentElement});var gvjs_cc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};function gvjs_dc(a,b){a=String(a);var c=a.indexOf(".");-1==c&&(c=a.length);return gvjs_cc("0",Math.max(0,b-c))+a}function gvjs_ec(a){return null==a?"":String(a)}var gvjs_fc=2147483648*Math.random()|0;function gvjs_gc(a){var b=Number(a);return 0==b&&gvjs_Mb(a)?NaN:b};function gvjs_hc(){return gvjs_Ub("iPhone")&&!gvjs_Ub("iPod")&&!gvjs_Ub("iPad")}function gvjs_ic(){return gvjs_hc()||gvjs_Ub("iPad")||gvjs_Ub("iPod")};function gvjs_jc(a){gvjs_jc[" "](a);return a}gvjs_jc[" "]=gvjs_tb;function gvjs_laa(a,b){var c=gvjs_maa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var gvjs_kc=gvjs_Ub("Opera"),gvjs_q=gvjs_Ub("Trident")||gvjs_Ub("MSIE"),gvjs_lc=gvjs_Ub(gvjs_ka),gvjs_naa=gvjs_lc||gvjs_q,gvjs_mc=gvjs_Ub("Gecko")&&!(gvjs_Ob(gvjs_Rb.toLowerCase(),"webkit")&&!gvjs_Ub(gvjs_ka))&&!(gvjs_Ub("Trident")||gvjs_Ub("MSIE"))&&!gvjs_Ub(gvjs_ka),gvjs_nc=gvjs_Ob(gvjs_Rb.toLowerCase(),"webkit")&&!gvjs_Ub(gvjs_ka),gvjs_oaa=gvjs_nc&&gvjs_Ub("Mobile"),gvjs_oc=gvjs_Ub("Macintosh"),gvjs_pc=gvjs_Ub("Windows"),gvjs_qc=gvjs_Ub("Linux")||gvjs_Ub("CrOS"),gvjs_rc=gvjs_f.navigator||null;
gvjs_rc&&gvjs_Ob(gvjs_rc.appVersion||"","X11");var gvjs_paa=gvjs_Ub("Android"),gvjs_qaa=gvjs_hc(),gvjs_raa=gvjs_Ub("iPad"),gvjs_saa=gvjs_Ub("iPod"),gvjs_taa=gvjs_ic();gvjs_Ob(gvjs_Rb.toLowerCase(),"kaios");function gvjs_sc(){var a=gvjs_f.document;return a?a.documentMode:void 0}var gvjs_tc;
a:{var gvjs_uc="",gvjs_vc=function(){var a=gvjs_Rb;if(gvjs_mc)return/rv:([^\);]+)(\)|;)/.exec(a);if(gvjs_lc)return/Edge\/([\d\.]+)/.exec(a);if(gvjs_q)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gvjs_nc)return/WebKit\/(\S+)/.exec(a);if(gvjs_kc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gvjs_vc&&(gvjs_uc=gvjs_vc?gvjs_vc[1]:"");if(gvjs_q){var gvjs_wc=gvjs_sc();if(null!=gvjs_wc&&gvjs_wc>parseFloat(gvjs_uc)){gvjs_tc=String(gvjs_wc);break a}}gvjs_tc=gvjs_uc}var gvjs_xc=gvjs_tc,gvjs_maa={};
function gvjs_yc(a){return gvjs_laa(a,function(){return 0<=gvjs_Pb(gvjs_xc,a)})}function gvjs_zc(a){return Number(gvjs_uaa)>=a}var gvjs_Ac;gvjs_Ac=gvjs_f.document&&gvjs_q?gvjs_sc():void 0;var gvjs_uaa=gvjs_Ac;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){}var gvjs_vaa=!gvjs_q||gvjs_zc(9),gvjs_waa=!gvjs_mc&&!gvjs_q||gvjs_q&&gvjs_zc(9)||gvjs_mc&&gvjs_yc("1.9.1"),gvjs_Bc=gvjs_q&&!gvjs_yc("9"),gvjs_xaa=gvjs_q||gvjs_kc||gvjs_nc;function gvjs_Cc(a,b,c){return Math.min(Math.max(a,b),c)};function gvjs_Dc(a){return a?new gvjs_Ec(gvjs_Fc(a)):gvjs_Ab||(gvjs_Ab=new gvjs_Ec)}function gvjs_Gc(a,b){gvjs_o(b,function(c,d){c&&typeof c==gvjs_Ya&&c.Ro&&(c=c.Yk());d==gvjs_2a?a.style.cssText=c:d==gvjs_Ma?a.className=c:"for"==d?a.htmlFor=c:gvjs_Hc.hasOwnProperty(d)?a.setAttribute(gvjs_Hc[d],c):gvjs_Kb(d,"aria-")||gvjs_Kb(d,"data-")?a.setAttribute(d,c):a[d]=c})}
var gvjs_Hc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:gvjs_Va,maxlength:"maxLength",nonce:"nonce",role:gvjs_0a,rowspan:"rowSpan",type:gvjs_7a,usemap:"useMap",valign:"vAlign",width:gvjs_8a};function gvjs_Ic(a,b,c,d){function e(g){g&&b.appendChild(typeof g===gvjs_d?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];gvjs_vb(f)&&!gvjs_Jc(f)?gvjs_m(gvjs_yaa(f)?gvjs_Ib(f):f,e):e(f)}}
function gvjs_Kc(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function gvjs_Lc(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case gvjs_oa:case gvjs_na:case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case gvjs_wa:case "PARAM":case gvjs_ya:case gvjs_za:case gvjs_Aa:case "TRACK":case "WBR":return!1}return!0}function gvjs_Mc(a,b){gvjs_Ic(gvjs_Fc(a),a,arguments,1)}
function gvjs_Nc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function gvjs_Oc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function gvjs_Pc(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)}function gvjs_Qc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function gvjs_Rc(a){return gvjs_waa&&void 0!=a.children?a.children:gvjs_Db(a.childNodes,function(b){return 1==b.nodeType})}
function gvjs_Sc(a){return void 0!==a.firstElementChild?a.firstElementChild:gvjs_Tc(a.firstChild,!0)}function gvjs_Uc(a){return void 0!==a.nextElementSibling?a.nextElementSibling:gvjs_Tc(a.nextSibling,!0)}function gvjs_Tc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function gvjs_Jc(a){return gvjs_i(a)&&0<a.nodeType}function gvjs_Vc(a){return gvjs_i(a)&&1==a.nodeType}
function gvjs_Wc(a){var b;if(gvjs_xaa&&!(gvjs_q&&gvjs_yc("9")&&!gvjs_yc("10")&&gvjs_f.SVGElement&&a instanceof gvjs_f.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return gvjs_Vc(b)?b:null}function gvjs_Xc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function gvjs_Fc(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function gvjs_Yc(a){return a.contentDocument||a.contentWindow.document}function gvjs_Zc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else gvjs_Nc(a),a.appendChild(gvjs_Fc(a).createTextNode(String(b)))}
var gvjs_zaa={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},gvjs__c={IMG:" ",BR:"\n"};function gvjs_0c(a){if(gvjs_Bc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];gvjs_1c(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");gvjs_Bc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function gvjs_1c(a,b,c){if(!(a.nodeName in gvjs_zaa))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in gvjs__c)b.push(gvjs__c[a.nodeName]);else for(a=a.firstChild;a;)gvjs_1c(a,b,c),a=a.nextSibling}function gvjs_yaa(a){if(a&&typeof a.length==gvjs_c){if(gvjs_i(a))return typeof a.item==gvjs_a||typeof a.item==gvjs_d;if(gvjs_j(a))return typeof a.item==gvjs_a}return!1}
function gvjs_2c(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function gvjs_Ec(a){this.hd=a||gvjs_f.document||document}gvjs_=gvjs_Ec.prototype;gvjs_.xa=gvjs_Dc;gvjs_.ic=gvjs_e(3);gvjs_.j=gvjs_e(4);gvjs_.getElementsByTagName=function(a,b){return(b||this.hd).getElementsByTagName(String(a))};gvjs_.xq=gvjs_e(5);gvjs_.ld=gvjs_e(7);gvjs_.DO=gvjs_e(9);gvjs_.vr=gvjs_Gc;gvjs_.J=gvjs_e(10);
gvjs_.createElement=function(a){return gvjs_Kc(this.hd,a)};gvjs_.createTextNode=function(a){return this.hd.createTextNode(String(a))};gvjs_.pW=gvjs_e(11);gvjs_.Lo=gvjs_e(12);gvjs_.qy=gvjs_e(13);gvjs_.appendChild=function(a,b){a.appendChild(b)};gvjs_.append=gvjs_Mc;gvjs_.canHaveChildren=gvjs_Lc;gvjs_.Ac=gvjs_Nc;gvjs_.wZ=gvjs_Oc;gvjs_.zra=gvjs_Pc;gvjs_.removeNode=gvjs_Qc;gvjs_.Ue=gvjs_Rc;gvjs_.E9=gvjs_Sc;gvjs_.H9=gvjs_Uc;gvjs_.So=gvjs_Jc;gvjs_.DZ=gvjs_Vc;gvjs_.yO=gvjs_Wc;gvjs_.contains=gvjs_Xc;
gvjs_.woa=gvjs_Fc;gvjs_.G9=gvjs_Yc;gvjs_.t2=gvjs_Zc;gvjs_.Jq=gvjs_e(15);gvjs_.yoa=gvjs_0c;gvjs_.w9=gvjs_2c;var gvjs_3c={V4:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},Dha:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},gvjs_4c=gvjs_3c;gvjs_4c=gvjs_3c;function gvjs_Aaa(a,b){var c=["0"];b=gvjs_5c[b];if(!b)return a;b=b[0]&7;if(0<b){c.push(".");for(var d=0;d<b;d++)c.push("0")}return a.replace(/0.00/g,c.join(""))}
var gvjs_5c={AED:[2,"dh","\u062f.\u0625."],ALL:[0,"Lek","Lek"],AUD:[2,"$","AU$"],BDT:[2,"\u09f3","Tk"],BGN:[2,"lev","lev"],BRL:[2,"R$","R$"],CAD:[2,"$","C$"],CDF:[2,"FrCD","CDF"],CHF:[2,"CHF","CHF"],CLP:[0,"$","CL$"],CNY:[2,"\u00a5","RMB\u00a5"],COP:[32,"$","COL$"],CRC:[0,"\u20a1","CR\u20a1"],CZK:[50,"K\u010d","K\u010d"],DKK:[50,"kr.","kr."],DOP:[2,"RD$","RD$"],EGP:[2,"\u00a3","LE"],ETB:[2,"Birr","Birr"],EUR:[2,"\u20ac","\u20ac"],GBP:[2,"\u00a3","GB\u00a3"],HKD:[2,"$","HK$"],HRK:[2,"kn","kn"],HUF:[34,
"Ft","Ft"],IDR:[0,"Rp","Rp"],ILS:[34,"\u20aa","IL\u20aa"],INR:[2,"\u20b9","Rs"],IRR:[0,"Rial","IRR"],ISK:[0,"kr","kr"],JMD:[2,"$","JA$"],JPY:[0,"\u00a5","JP\u00a5"],KRW:[0,"\u20a9","KR\u20a9"],LKR:[2,"Rs","SLRs"],LTL:[2,"Lt","Lt"],MNT:[0,"\u20ae","MN\u20ae"],MVR:[2,"Rf","MVR"],MXN:[2,"$","Mex$"],MYR:[2,"RM","RM"],NOK:[50,"kr","NOkr"],PAB:[2,"B/.","B/."],PEN:[2,"S/.","S/."],PHP:[2,"\u20b1","PHP"],PKR:[0,"Rs","PKRs."],PLN:[50,"z\u0142","z\u0142"],RON:[2,"RON","RON"],RSD:[0,"din","RSD"],RUB:[50,"\u20bd",
"RUB"],SAR:[2,"Rial","Rial"],SEK:[50,"kr","kr"],SGD:[2,"$","S$"],THB:[2,"\u0e3f","THB"],TRY:[2,"\u20ba","TRY"],TWD:[2,"NT$","NT$"],TZS:[0,"TSh","TSh"],UAH:[2,"\u0433\u0440\u043d.","UAH"],USD:[2,"$","US$"],UYU:[2,"$","$U"],VND:[48,"\u20ab","VN\u20ab"],YER:[0,"Rial","Rial"],ZAR:[2,"R","ZAR"]};var gvjs_6c={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ca,gvjs_xa,gvjs_va,gvjs_ja],STANDALONEMONTHS:[gvjs_qa,gvjs_la,gvjs_sa,gvjs_ga,gvjs_ta,"June","July",gvjs_ha,gvjs_Ca,gvjs_xa,gvjs_va,gvjs_ja],SHORTMONTHS:["Jan","Feb","Mar","Apr",gvjs_ta,"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],STANDALONESHORTMONTHS:["Jan","Feb","Mar",
"Apr",gvjs_ta,"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],WEEKDAYS:[gvjs_Da,gvjs_ua,gvjs_Ga,gvjs_Ha,gvjs_Ea,gvjs_ma,gvjs_Ba],STANDALONEWEEKDAYS:[gvjs_Da,gvjs_ua,gvjs_Ga,gvjs_Ha,gvjs_Ea,gvjs_ma,gvjs_Ba],SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],
AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:[gvjs_9a,gvjs_9a,gvjs_$a,gvjs_$a],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},gvjs_7c=gvjs_6c;gvjs_7c=gvjs_6c;function gvjs_8c(){}
function gvjs_9c(a){if(typeof a==gvjs_c){var b=new gvjs_8c;b.f3=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",gvjs_dc(c,2));c=d.join("")}b.M3=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=gvjs_$c(a);b.HT=[c,c];b.Ow={kBa:a,i5:a};b.uA=[];return b}b=new gvjs_8c;b.M3=a.id;b.f3=-a.std_offset;b.HT=a.names;b.Ow=a.names_ext;b.uA=a.transitions;
return b}function gvjs_$c(a){var b=["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(gvjs_dc(Math.floor(a/60)%100,2),":",gvjs_dc(a%60,2));return b.join("")}gvjs_=gvjs_8c.prototype;gvjs_.getTimeZoneData=function(){return{id:this.M3,std_offset:-this.f3,names:gvjs_Ib(this.HT),names_ext:gvjs_p(this.Ow),transitions:gvjs_Ib(this.uA)}};
gvjs_.getDaylightAdjustment=function(a){a=Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes())/36E5;for(var b=0;b<this.uA.length&&a>=this.uA[b];)b+=2;return 0==b?0:this.uA[b-1]};gvjs_.getGMTString=function(a){return gvjs_$c(this.getOffset(a))};gvjs_.getLongName=function(a){return this.HT[this.isDaylightTime(a)?3:1]};gvjs_.getOffset=function(a){return this.f3-this.getDaylightAdjustment(a)};
gvjs_.getRFCTimeZoneString=function(a){a=-this.getOffset(a);var b=[0>a?"-":"+"];a=Math.abs(a);b.push(gvjs_dc(Math.floor(a/60)%100,2),gvjs_dc(a%60,2));return b.join("")};gvjs_.getShortName=function(a){return this.HT[this.isDaylightTime(a)?2:0]};gvjs_.getTimeZoneId=function(){return this.M3};gvjs_.isDaylightTime=function(a){return 0<this.getDaylightAdjustment(a)};function gvjs_ad(a,b){switch(b){case 1:return 0!=a%4||0==a%100&&0!=a%400?28:29;case 5:case 8:case 10:case 3:return 30}return 31}function gvjs_bd(a,b,c,d,e){a=new Date(a,b,c);e=e||0;return a.valueOf()+864E5*(((void 0!==d?d:3)-e+7)%7-((a.getDay()+6)%7-e+7)%7)}
function gvjs_cd(a,b,c){typeof a===gvjs_c?(this.date=gvjs_dd(a,b||0,c||1),gvjs_ed(this,c||1)):gvjs_i(a)?(this.date=gvjs_dd(a.getFullYear(),a.getMonth(),a.getDate()),gvjs_ed(this,a.getDate())):(this.date=new Date(gvjs_zb()),a=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),gvjs_ed(this,a))}function gvjs_dd(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b}gvjs_=gvjs_cd.prototype;gvjs_.RB=gvjs_7c.FIRSTDAYOFWEEK;
gvjs_.SB=gvjs_7c.FIRSTWEEKCUTOFFDAY;gvjs_.clone=function(){var a=new gvjs_cd(this.date);a.RB=this.RB;a.SB=this.SB;return a};gvjs_.getFullYear=function(){return this.date.getFullYear()};gvjs_.getYear=function(){return this.getFullYear()};gvjs_.getMonth=function(){return this.date.getMonth()};gvjs_.getDate=function(){return this.date.getDate()};gvjs_.getTime=function(){return this.date.getTime()};gvjs_.getDay=function(){return this.date.getDay()};gvjs_.getUTCFullYear=function(){return this.date.getUTCFullYear()};
gvjs_.getUTCMonth=function(){return this.date.getUTCMonth()};gvjs_.getUTCDate=function(){return this.date.getUTCDate()};gvjs_.getUTCDay=function(){return this.date.getDay()};gvjs_.getUTCHours=function(){return this.date.getUTCHours()};gvjs_.getUTCMinutes=function(){return this.date.getUTCMinutes()};gvjs_.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};gvjs_.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};gvjs_.setFullYear=function(a){this.date.setFullYear(a)};
gvjs_.setYear=function(a){this.setFullYear(a)};gvjs_.setMonth=function(a){this.date.setMonth(a)};gvjs_.setDate=function(a){this.date.setDate(a)};gvjs_.setTime=function(a){this.date.setTime(a)};gvjs_.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};gvjs_.setUTCMonth=function(a){this.date.setUTCMonth(a)};gvjs_.setUTCDate=function(a){this.date.setUTCDate(a)};
gvjs_.add=function(a){if(a.Ej||a.months){var b=this.getMonth()+a.months+12*a.Ej,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);var d=Math.min(gvjs_ad(c,b),this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),this.setDate(a.getDate()),gvjs_ed(this,a.getDate()))};
gvjs_.pA=function(a){return[this.getFullYear(),gvjs_dc(this.getMonth()+1,2),gvjs_dc(this.getDate(),2)].join(a?"-":"")+""};gvjs_.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};gvjs_.toString=function(){return this.pA()};function gvjs_ed(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))}gvjs_.valueOf=function(){return this.date.valueOf()};function gvjs_fd(a){this.lR=[];this.Ne=gvjs_7c;typeof a==gvjs_c?this.bM(a):this.Zr(a)}var gvjs_gd=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEahKHcLQdmsvVwzZ]+/];function gvjs_hd(a){return a.getHours?a.getHours():0}
gvjs_fd.prototype.Zr=function(a){for(gvjs_Baa&&(a=a.replace(/\u200f/g,""));a;){for(var b=a,c=0;c<gvjs_gd.length;++c){var d=a.match(gvjs_gd[c]);if(d){var e=d[0];a=a.substring(e.length);0==c&&("''"==e?e="'":(e=e.substring(1,"'"==d[1]?e.length-1:e.length),e=e.replace(/''/g,"'")));this.lR.push({text:e,type:c});break}}if(b===a)throw Error("Malformed pattern part: "+a);}};
gvjs_fd.prototype.format=function(a,b){if(!a)throw Error("The date to format must be non-null.");var c=b?6E4*(a.getTimezoneOffset()-b.getOffset(a)):0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=6E4*(d.getTimezoneOffset()-a.getTimezoneOffset()),d=new Date(d.getTime()+e),c+=0<c?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(var f=0;f<this.lR.length;++f){var g=this.lR[f].text;1==this.lR[f].type?c.push(gvjs_Caa(this,g,a,d,e,b)):c.push(g)}return c.join("")};
gvjs_fd.prototype.bM=function(a){if(4>a)var b=this.Ne.DATEFORMATS[a];else if(8>a)b=this.Ne.TIMEFORMATS[a-4];else if(12>a)b=this.Ne.DATETIMEFORMATS[a-8],b=b.replace("{1}",this.Ne.DATEFORMATS[a-8]),b=b.replace("{0}",this.Ne.TIMEFORMATS[a-8]);else{this.bM(10);return}this.Zr(b)};function gvjs_id(a,b){b=String(b);a=a.Ne||gvjs_7c;if(void 0!==a.sja){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.sja+e-48):b.charAt(d))}b=c.join("")}return b}var gvjs_Baa=!1;
function gvjs_jd(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("The date to format has no time (probably a goog.date.Date). Use Date or goog.date.DateTime, or use a pattern without time fields.");}
function gvjs_Caa(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=g?a.Ne.ERANAMES[c]:a.Ne.ERAS[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==g&&(c%=100),gvjs_id(a,gvjs_dc(c,g));case "Y":return c=(new Date(gvjs_bd(d.getFullYear(),d.getMonth(),d.getDate(),a.Ne.FIRSTWEEKCUTOFFDAY,a.Ne.FIRSTDAYOFWEEK))).getFullYear(),0>c&&(c=-c),2==g&&(c%=100),gvjs_id(a,gvjs_dc(c,g));case "M":a:switch(c=d.getMonth(),g){case 5:g=a.Ne.NARROWMONTHS[c];break a;case 4:g=a.Ne.MONTHS[c];
break a;case 3:g=a.Ne.SHORTMONTHS[c];break a;default:g=gvjs_id(a,gvjs_dc(c+1,g))}return g;case "k":return gvjs_jd(e),gvjs_id(a,gvjs_dc(gvjs_hd(e)||24,g));case "S":return gvjs_id(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).substr(2)+(3<g?gvjs_dc(0,g-3):""));case "E":return c=d.getDay(),4<=g?a.Ne.WEEKDAYS[c]:a.Ne.SHORTWEEKDAYS[c];case "a":return gvjs_jd(e),g=gvjs_hd(e),a.Ne.AMPMS[12<=g&&24>g?1:0];case "h":return gvjs_jd(e),gvjs_id(a,gvjs_dc(gvjs_hd(e)%12||12,g));case "K":return gvjs_jd(e),gvjs_id(a,
gvjs_dc(gvjs_hd(e)%12,g));case "H":return gvjs_jd(e),gvjs_id(a,gvjs_dc(gvjs_hd(e),g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.Ne.STANDALONENARROWWEEKDAYS[c];break a;case 4:g=a.Ne.STANDALONEWEEKDAYS[c];break a;case 3:g=a.Ne.STANDALONESHORTWEEKDAYS[c];break a;default:g=gvjs_id(a,gvjs_dc(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.Ne.STANDALONENARROWMONTHS[c];break a;case 4:g=a.Ne.STANDALONEMONTHS[c];break a;case 3:g=a.Ne.STANDALONESHORTMONTHS[c];break a;default:g=gvjs_id(a,gvjs_dc(c+
1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),4>g?a.Ne.SHORTQUARTERS[c]:a.Ne.QUARTERS[c];case "d":return gvjs_id(a,gvjs_dc(d.getDate(),g));case "m":return gvjs_jd(e),gvjs_id(a,gvjs_dc(e.getMinutes(),g));case "s":return gvjs_jd(e),gvjs_id(a,gvjs_dc(e.getSeconds(),g));case "v":return g=f||gvjs_9c(c.getTimezoneOffset()),g.getTimeZoneId();case "V":return a=f||gvjs_9c(c.getTimezoneOffset()),2>=g?g=a.getTimeZoneId():(g=a,g=g.isDaylightTime(c)?void 0!==g.Ow.Mha?g.Ow.Mha:g.Ow.DST_GENERIC_LOCATION:
void 0!==g.Ow.i5?g.Ow.i5:g.Ow.STD_GENERIC_LOCATION),g;case "w":return c=gvjs_bd(e.getFullYear(),e.getMonth(),e.getDate(),a.Ne.FIRSTWEEKCUTOFFDAY,a.Ne.FIRSTDAYOFWEEK),gvjs_id(a,gvjs_dc(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||gvjs_9c(c.getTimezoneOffset()),4>g?a.getShortName(c):a.getLongName(c);case "Z":return b=f||gvjs_9c(c.getTimezoneOffset()),4>g?b.getRFCTimeZoneString(c):gvjs_id(a,b.getGMTString(c));default:return""}};var gvjs_kd={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM y",YEAR_MONTH_FULL:"MMMM y",MBa:"MM/y",MONTH_DAY_ABBR:"MMM d",MONTH_DAY_FULL:"MMMM dd",MONTH_DAY_SHORT:"M/d",MONTH_DAY_MEDIUM:"MMMM d",MONTH_DAY_YEAR_MEDIUM:"MMM d, y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, MMM d",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, MMM d, y",DAY_ABBR:"d",zAa:"MMM d, h:mm a zzzz"},gvjs_ld=gvjs_kd;gvjs_ld=gvjs_kd;var gvjs_md={DECIMAL_SEP:".",GROUP_SEP:",",PERCENT:"%",xU:"0",Iia:"+",b5:"-",X4:"E",d5:"\u2030",pU:"\u221e",xia:"NaN",DECIMAL_PATTERN:"#,##0.###",Tia:"#E0",sU:"#,##0%",Eha:"\u00a4#,##0.00",Iha:"USD"},gvjs_nd=gvjs_md,gvjs_od=gvjs_md;gvjs_od=gvjs_nd=gvjs_md;function gvjs_pd(a,b,c,d){var e;if(e=b){a:if(b&&3===b.length){for(e=0;3>e;e++){var f=b[e];if("A">f||"Z"<f&&"a">f||"z"<f){e=!1;break a}}e=!0}else e=!1;e=!e}if(e)throw new TypeError("Currency must be valid ISO code");this.Dra=b?b.toUpperCase():null;this.Ola=c||0;this.wua=d||null;this.bJ=40;this.ap=1;this.vm=0;this.Tq=3;this.AQ=this.Ht=0;this.K2=this.Aga=!1;this.KJ=this.Dz="";this.fw=gvjs_qd(this).b5;this.rD="";this.Uf=1;this.mz=!1;this.By=[];this.MT=this.U7=!1;this.uG=0;this.mM=null;typeof a==gvjs_c?
this.bM(a):this.Zr(a)}var gvjs_rd=!1;function gvjs_qd(a){return a.wua||(gvjs_rd?gvjs_od:gvjs_nd)}function gvjs_sd(a){return a.Dra||gvjs_qd(a).Iha}gvjs_=gvjs_pd.prototype;gvjs_.setMinimumFractionDigits=function(a){if(0<this.vm&&0<a)throw Error(gvjs_ia);this.Ht=a;return this};gvjs_.setMaximumFractionDigits=function(a){if(308<a)throw Error("Unsupported maximum fraction digits: "+a);this.Tq=a;return this};gvjs_.setSignificantDigits=function(a){if(0<this.Ht&&0<=a)throw Error(gvjs_ia);this.vm=a;return this};
gvjs_.getSignificantDigits=function(){return this.vm};gvjs_.setShowTrailingZeros=function(a){this.K2=a;return this};gvjs_.setBaseFormatting=function(a){this.mM=a;return this};gvjs_.getBaseFormatting=function(){return this.mM};
gvjs_.Zr=function(a){this.fd=a.replace(/ /g,"\u00a0");var b=[0];this.Dz=gvjs_td(this,a,b);for(var c=b[0],d=-1,e=0,f=0,g=0,h=-1,k=a.length,l=!0;b[0]<k&&l;b[0]++)switch(a.charAt(b[0])){case "#":0<f?g++:e++;0<=h&&0>d&&h++;break;case "0":if(0<g)throw Error('Unexpected "0" in pattern "'+a+'"');f++;0<=h&&0>d&&h++;break;case ",":0<h&&this.By.push(h);h=0;break;case ".":if(0<=d)throw Error('Multiple decimal separators in pattern "'+a+'"');d=e+f+g;break;case "E":if(this.MT)throw Error('Multiple exponential symbols in pattern "'+
a+'"');this.MT=!0;this.AQ=0;b[0]+1<k&&"+"==a.charAt(b[0]+1)&&(b[0]++,this.Aga=!0);for(;b[0]+1<k&&"0"==a.charAt(b[0]+1);)b[0]++,this.AQ++;if(1>e+f||1>this.AQ)throw Error('Malformed exponential pattern "'+a+'"');l=!1;break;default:b[0]--,l=!1}0==f&&0<e&&0<=d&&(f=d,0==f&&f++,g=e-f,e=f-1,f=1);if(0>d&&0<g||0<=d&&(d<e||d>e+f)||0==h)throw Error('Malformed pattern "'+a+'"');g=e+f+g;this.Tq=0<=d?g-d:0;0<=d&&(this.Ht=e+f-d,0>this.Ht&&(this.Ht=0));this.ap=(0<=d?d:g)-e;this.MT&&(this.bJ=e+this.ap,0==this.Tq&&
0==this.ap&&(this.ap=1));this.By.push(Math.max(0,h));this.U7=0==d||d==g;c=b[0]-c;this.KJ=gvjs_td(this,a,b);b[0]<a.length&&";"==a.charAt(b[0])?(b[0]++,1!=this.Uf&&(this.mz=!0),this.fw=gvjs_td(this,a,b),b[0]+=c,this.rD=gvjs_td(this,a,b)):(this.fw+=this.Dz,this.rD+=this.KJ)};
gvjs_.bM=function(a){switch(a){case 1:this.Zr(gvjs_qd(this).DECIMAL_PATTERN);break;case 2:this.Zr(gvjs_qd(this).Tia);break;case 3:this.Zr(gvjs_qd(this).sU);break;case 4:this.Zr(gvjs_Aaa(gvjs_qd(this).Eha,gvjs_sd(this)));break;case 5:gvjs_ud(this,1);break;case 6:gvjs_ud(this,2);break;default:throw Error("Unsupported pattern type.");}};function gvjs_ud(a,b){a.uG=b;a.Zr(gvjs_qd(a).DECIMAL_PATTERN);a.setMinimumFractionDigits(0);a.setMaximumFractionDigits(2);a.setSignificantDigits(2)}
gvjs_.parse=function(a,b){b=b||[0];if(0!=this.uG)throw Error("Parsing of compact numbers is unimplemented");a=a.replace(/ |\u202f/g,"\u00a0");var c=a.indexOf(this.Dz,b[0])==b[0],d=a.indexOf(this.fw,b[0])==b[0];c&&d&&(this.Dz.length>this.fw.length?d=!1:this.Dz.length<this.fw.length&&(c=!1));c?b[0]+=this.Dz.length:d&&(b[0]+=this.fw.length);if(a.indexOf(gvjs_qd(this).pU,b[0])==b[0]){b[0]+=gvjs_qd(this).pU.length;var e=Infinity}else{e=a;var f=!1,g=!1,h=!1,k=-1,l=1,m=gvjs_qd(this).DECIMAL_SEP,n=gvjs_qd(this).GROUP_SEP,
p=gvjs_qd(this).X4;if(0!=this.uG)throw Error("Parsing of compact style numbers is not implemented");n=n.replace(/\u202f/g,"\u00a0");for(var q="";b[0]<e.length;b[0]++){var r=e.charAt(b[0]),t=gvjs_vd(this,r);if(0<=t&&9>=t)q+=t,h=!0;else if(r==m.charAt(0)){if(f||g)break;q+=".";f=!0}else if(r==n.charAt(0)&&("\u00a0"!=n.charAt(0)||b[0]+1<e.length&&0<=gvjs_vd(this,e.charAt(b[0]+1)))){if(f||g)break}else if(r==p.charAt(0)){if(g)break;q+="E";g=!0;k=b[0]}else if("+"==r||"-"==r){if(h&&k!=b[0]-1)break;q+=r}else if(1==
this.Uf&&r==gvjs_qd(this).PERCENT.charAt(0)){if(1!=l)break;l=100;if(h){b[0]++;break}}else if(1==this.Uf&&r==gvjs_qd(this).d5.charAt(0)){if(1!=l)break;l=1E3;if(h){b[0]++;break}}else break}1!=this.Uf&&(l=this.Uf);e=parseFloat(q)/l}if(c){if(a.indexOf(this.KJ,b[0])!=b[0])return NaN;b[0]+=this.KJ.length}else if(d){if(a.indexOf(this.rD,b[0])!=b[0])return NaN;b[0]+=this.rD.length}return d?-e:e};
gvjs_.format=function(a){if(isNaN(a))return gvjs_qd(this).xia;var b=[];var c=null===this.mM?a:this.mM;if(0==this.uG)c=gvjs_wd;else{c=Math.abs(c);var d=gvjs_xd(this,1>=c?0:gvjs_yd(c)).divisorBase;c=gvjs_xd(this,d+gvjs_yd(gvjs_zd(this,gvjs_Ad(c,-d)).paa))}a=gvjs_Ad(a,-c.divisorBase);b.push(c.prefix);d=0>a||0==a&&0>1/a;b.push(d?this.fw:this.Dz);if(isFinite(a))if(a=a*(d?-1:1)*this.Uf,this.MT)if(0==a)gvjs_Bd(this,a,this.ap,b),gvjs_Cd(this,0,b);else{var e=Math.floor(Math.log(a)/Math.log(10)+2E-15);a=gvjs_Ad(a,
-e);var f=this.ap;1<this.bJ&&this.bJ>this.ap?(f=e%this.bJ,0>f&&(f=this.bJ+f),a=gvjs_Ad(a,f),e-=f,f=1):1>this.ap?(e++,a=gvjs_Ad(a,-1)):(e-=this.ap-1,a=gvjs_Ad(a,this.ap-1));gvjs_Bd(this,a,f,b);gvjs_Cd(this,e,b)}else gvjs_Bd(this,a,this.ap,b);else b.push(gvjs_qd(this).pU);b.push(d?this.rD:this.KJ);b.push(c.suffix);return b.join("")};
function gvjs_zd(a,b){var c=gvjs_Ad(b,a.Tq);0<a.vm&&(c=gvjs_Dd(c,a.vm,a.Tq));c=Math.round(c);isFinite(c)?(b=Math.floor(gvjs_Ad(c,-a.Tq)),a=Math.floor(c-gvjs_Ad(b,a.Tq))):a=0;return{paa:b,Una:a}}
function gvjs_Bd(a,b,c,d){if(a.Ht>a.Tq)throw Error("Min value must be less than max value");d||(d=[]);b=gvjs_zd(a,b);var e=b.paa,f=b.Una,g=0==e?0:gvjs_yd(e)+1,h=0<a.Ht||0<f||a.K2&&g<a.vm;b=a.Ht;h&&(b=a.K2&&0<a.vm?a.vm-g:a.Ht);var k="";for(g=e;1E20<g;)k="0"+k,g=Math.round(gvjs_Ad(g,-1));k=g+k;var l=gvjs_qd(a).DECIMAL_SEP;g=gvjs_qd(a).xU.charCodeAt(0);var m=k.length,n=0;if(0<e||0<c){for(e=m;e<c;e++)d.push(String.fromCharCode(g));if(2<=a.By.length)for(c=1;c<a.By.length;c++)n+=a.By[c];c=m-n;if(0<c){e=
a.By;n=m=0;for(var p,q=gvjs_qd(a).GROUP_SEP,r=k.length,t=0;t<r;t++)if(d.push(String.fromCharCode(g+1*Number(k.charAt(t)))),1<r-t)if(p=e[n],t<c){var u=c-t;(1===p||0<p&&1===u%p)&&d.push(q)}else n<e.length&&(t===c?n+=1:p===t-c-m+1&&(d.push(q),m+=p,n+=1))}else{c=k;k=a.By;e=gvjs_qd(a).GROUP_SEP;p=c.length;q=[];for(m=k.length-1;0<=m&&0<p;m--){n=k[m];for(r=0;r<n&&0<=p-r-1;r++)q.push(String.fromCharCode(g+1*Number(c.charAt(p-r-1))));p-=n;0<p&&q.push(e)}d.push.apply(d,q.reverse())}}else h||d.push(String.fromCharCode(g));
(a.U7||h)&&d.push(l);f=String(f);h=f.split("e+");2==h.length&&(f=String(gvjs_Dd(parseFloat(h[0]),a.vm,1)),f=f.replace(".",""),f+=gvjs_cc("0",parseInt(h[1],10)-f.length+1));a.Tq+1>f.length&&(f="1"+gvjs_cc("0",a.Tq-f.length)+f);for(a=f.length;"0"==f.charAt(a-1)&&a>b+1;)a--;for(e=1;e<a;e++)d.push(String.fromCharCode(g+1*Number(f.charAt(e))))}
function gvjs_Cd(a,b,c){c.push(gvjs_qd(a).X4);0>b?(b=-b,c.push(gvjs_qd(a).b5)):a.Aga&&c.push(gvjs_qd(a).Iia);b=""+b;for(var d=gvjs_qd(a).xU,e=b.length;e<a.AQ;e++)c.push(d);c.push(b)}function gvjs_vd(a,b){b=b.charCodeAt(0);if(48<=b&&58>b)return b-48;a=gvjs_qd(a).xU.charCodeAt(0);return a<=b&&b<a+10?b-a:-1}
function gvjs_td(a,b,c){for(var d="",e=!1,f=b.length;c[0]<f;c[0]++){var g=b.charAt(c[0]);if("'"==g)c[0]+1<f&&"'"==b.charAt(c[0]+1)?(c[0]++,d+="'"):e=!e;else if(e)d+=g;else switch(g){case "#":case "0":case ",":case ".":case ";":return d;case "\u00a4":if(c[0]+1<f&&"\u00a4"==b.charAt(c[0]+1))c[0]++,d+=gvjs_sd(a);else switch(a.Ola){case 0:g=gvjs_sd(a);d+=g in gvjs_5c?gvjs_5c[g][1]:g;break;case 2:g=gvjs_sd(a);var h=gvjs_5c[g];d+=h?g==h[1]?g:g+" "+h[1]:g;break;case 1:g=gvjs_sd(a),d+=g in gvjs_5c?gvjs_5c[g][2]:
g}break;case "%":if(!a.mz&&1!=a.Uf)throw Error(gvjs_Fa);if(a.mz&&100!=a.Uf)throw Error(gvjs_pa);a.Uf=100;a.mz=!1;d+=gvjs_qd(a).PERCENT;break;case "\u2030":if(!a.mz&&1!=a.Uf)throw Error(gvjs_Fa);if(a.mz&&1E3!=a.Uf)throw Error(gvjs_pa);a.Uf=1E3;a.mz=!1;d+=gvjs_qd(a).d5;break;default:d+=g}}return d}var gvjs_wd={prefix:"",suffix:"",divisorBase:0};
function gvjs_xd(a,b){a=1==a.uG?gvjs_4c.V4:gvjs_4c.Dha;null==a&&(a=gvjs_4c.V4);if(3>b)return gvjs_wd;b=Math.min(14,b);var c=a[gvjs_Ad(1,b)];for(--b;!c&&3<=b;)c=a[gvjs_Ad(1,b)],b--;if(!c)return gvjs_wd;a=c.other;return a&&"0"!=a?(a=/([^0]*)(0+)(.*)/.exec(a))?{prefix:a[1],suffix:a[3],divisorBase:b+1-(a[2].length-1)}:gvjs_wd:gvjs_wd}function gvjs_yd(a){if(!isFinite(a))return 0<a?a:0;for(var b=0;1<=(a/=10);)b++;return b}
function gvjs_Ad(a,b){if(!a||!isFinite(a)||0==b)return a;a=String(a).split("e");return parseFloat(a[0]+"e"+(parseInt(a[1]||0,10)+b))}function gvjs_Ed(a,b){return a&&isFinite(a)?gvjs_Ad(Math.round(gvjs_Ad(a,b)),-b):a}function gvjs_Dd(a,b,c){if(!a)return a;b=b-gvjs_yd(a)-1;return b<-c?gvjs_Ed(a,-c):gvjs_Ed(a,b)}
gvjs_pd.prototype.isCurrencyCodeBeforeValue=function(){var a=this.fd.indexOf("\u00a4"),b=this.fd.indexOf("#"),c=this.fd.indexOf("0"),d=Number.MAX_VALUE;0<=b&&b<d&&(d=b);0<=c&&c<d&&(d=c);return a<d};var gvjs_Fd={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:gvjs_aa,blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:gvjs_ba,green:"#008000",greenyellow:"#adff2f",grey:gvjs_ba,honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:gvjs_ca,whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function gvjs_Gd(a){var b={};a=String(a);var c="#"==a.charAt(0)?a:"#"+a;if(gvjs_Hd.test(c))return b.hex=gvjs_Id(c),b.type="hex",b;c=gvjs_Jd(a);if(c.length)return b.hex=gvjs_Kd(c),b.type="rgb",b;if(gvjs_Fd&&(c=gvjs_Fd[a.toLowerCase()]))return b.hex=c,b.type="named",b;throw Error(a+" is not a valid color string");}var gvjs_Daa=/#(.)(.)(.)/;
function gvjs_Id(a){if(!gvjs_Hd.test(a))throw Error("'"+a+"' is not a valid hex color");4==a.length&&(a=a.replace(gvjs_Daa,"#$1$1$2$2$3$3"));return a.toLowerCase()}function gvjs_Ld(a){a=gvjs_Id(a);a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]}function gvjs_Md(a,b,c){a=Number(a);b=Number(b);c=Number(c);if(a!=(a&255)||b!=(b&255)||c!=(c&255))throw Error('"('+a+","+b+","+c+'") is not a valid RGB color');b=a<<16|b<<8|c;return 16>a?"#"+(16777216|b).toString(16).substr(1):"#"+b.toString(16)}
function gvjs_Kd(a){return gvjs_Md(a[0],a[1],a[2])}var gvjs_Hd=/^#(?:[0-9a-f]{3}){1,2}$/i,gvjs_Eaa=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function gvjs_Jd(a){var b=a.match(gvjs_Eaa);if(b){a=Number(b[1]);var c=Number(b[2]);b=Number(b[3]);if(0<=a&&255>=a&&0<=c&&255>=c&&0<=b&&255>=b)return[a,c,b]}return[]}function gvjs_Nd(a,b,c){c=gvjs_Cc(c,0,1);return[Math.round(b[0]+c*(a[0]-b[0])),Math.round(b[1]+c*(a[1]-b[1])),Math.round(b[2]+c*(a[2]-b[2]))]};function gvjs_Od(a,b){if(null==a||""===a||a==gvjs_5a||a==gvjs_b)var c=gvjs_b;else{if(gvjs_i(a))return a.color||"";try{c=gvjs_Gd(a).hex}catch(d){if(!b)throw Error("Invalid color: "+a);c=a}}return c};function gvjs_Pd(a,b){return(new gvjs_Qd(b)).le(a)}function gvjs_Qd(a){this.IR=a}gvjs_Qd.prototype.le=function(a){var b=[];gvjs_Rd(this,a,b);return b.join("")};
function gvjs_Rd(a,b,c){if(null==b)c.push(gvjs_Xa);else{if(typeof b==gvjs_Ya){if(gvjs_h(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],gvjs_Rd(a,a.IR?a.IR.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],typeof e!=gvjs_a&&(c.push(f),gvjs_Sd(d,c),c.push(":"),gvjs_Rd(a,a.IR?a.IR.call(b,d,e):e,c),f=","));c.push("}");
return}}switch(typeof b){case gvjs_d:gvjs_Sd(b,c);break;case gvjs_c:c.push(isFinite(b)&&!isNaN(b)?String(b):gvjs_Xa);break;case gvjs_La:c.push(String(b));break;case gvjs_a:c.push(gvjs_Xa);break;default:throw Error("Unknown type: "+typeof b);}}}var gvjs_Td={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},gvjs_Faa=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function gvjs_Sd(a,b){b.push('"',a.replace(gvjs_Faa,function(c){var d=gvjs_Td[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),gvjs_Td[c]=d);return d}),'"')};var gvjs_Ud=JSON.parse,gvjs_Vd=gvjs_f.JSON&&gvjs_f.JSON.stringify||gvjs_Pd;var gvjs_Wd="StopIteration"in gvjs_f?gvjs_f.StopIteration:{message:"StopIteration",stack:""};function gvjs_Xd(a){return gvjs_ub(a)!=gvjs_Ya||gvjs_wb(a)?null:a}function gvjs_Yd(a,b){a=gvjs_Xd(a)||{};if(2==arguments.length){var c=arguments[1];if(!gvjs_Xd(c))return a;for(var d in c)if(gvjs_h(c[d]))a[d]=gvjs_Ib(c[d]);else if(gvjs_Xd(a[d]))a[d]=gvjs_Yd(a[d],c[d]);else if(gvjs_Xd(c[d]))a[d]=gvjs_Yd({},c[d]);else if(null==a[d]||null!=c[d])a[d]=c[d]}else if(2<arguments.length)for(c=1,d=arguments.length;c<d;c++)a=gvjs_Yd(a,arguments[c]);return a};var gvjs_Zd;function gvjs__d(a,b,c,d){this.He=a||[{}];this.RI=d||gvjs_Jb(1,this.He.length);this.nM=b||null;this.EZ=null!=c?c:!1}gvjs_=gvjs__d.prototype;gvjs_.view=function(a){a=gvjs_0d(this,a);return new gvjs__d(gvjs_Ib(this.He),a,this.EZ,gvjs_Ib(this.RI))};function gvjs_0d(a,b){typeof b===gvjs_d&&(b=[b]);return null!=a.nM?gvjs_1d(a.nM,b):b}
function gvjs_1d(a,b){a=typeof a===gvjs_d?[a]:a;var c=typeof b===gvjs_d?[b]:b;if(0===a.length)return c;if(0===c.length)return a;var d=[];gvjs_m(a,function(e){var f=gvjs_Mb(e);gvjs_m(c,function(g){var h=gvjs_Mb(g);f||h?f?h||d.push(g):d.push(e):d.push(e+"."+g)})});return d}function gvjs_2d(a,b,c,d){typeof b===gvjs_d&&(b=[b]);for(var e=0;e<b.length;++e){var f=gvjs_3d(a,b[e],c,d);if(null!=f)return f}return null}
function gvjs_3d(a,b,c,d){if(d)b=a[b];else a:{b=b.split(".");a=a||gvjs_f;for(d=0;d<b.length;d++){var e=b[d];if(null!=a[e])a=a[e];else{b=null;break a}}b=a}return null!=b&&typeof c===gvjs_a?c(b):b}gvjs_.Ja=function(a,b){var c=[];null!=b&&c.push(b);a=gvjs_0d(this,a);for(b=this.He.length-1;0<=b;b--)for(var d=a.length-1;0<=d;d--){var e=gvjs_3d(this.He[b],a[d],void 0,this.EZ);null!=e&&c.unshift(e)}return c};
function gvjs_Gaa(a,b,c){var d={};a=a.Ja(b,c);gvjs_Cb(a,function(e){typeof e===gvjs_Ya&&gvjs_Yd(d,e)});return d}gvjs_.ea=function(a,b,c){a=gvjs_0d(this,a);for(var d=0;d<this.He.length;d++){var e=gvjs_2d(this.He[d],a,c,this.EZ);if(null!=e)return e}e=null!=b&&c?c(b):b;return null!=e?e:null};gvjs_.nb=function(a,b,c){a=gvjs_Gaa(this,a,b);c&&(a=c(a));return a||{}};
function gvjs_4d(a,b,c,d,e,f){function g(h){return b(h,f)}a=a.ea(d,e,g);null==a&&(a=g(c),null==a&&(a=c));if(null==a)throw Error("Unexpected null value for "+d);return a}function gvjs_5d(a,b,c,d){a=a.ea(c,null,function(e){return b(e,d)});return null==a?null:a}function gvjs_6d(a,b){a=null!=a&&typeof a!==gvjs_Ya?String(a):null;return b?Array.isArray(b)?gvjs_Hb(b,a)?a:null:gvjs_Vb(b,a)?a:null:a}function gvjs_r(a,b,c,d){return gvjs_4d(a,gvjs_6d,"",b,c,d)}
gvjs_.ob=function(a,b){return gvjs_5d(this,gvjs_6d,a,b)};function gvjs_7d(a,b){if(null==a)return null;typeof a===gvjs_d&&(a=[a]);return Array.isArray(a)?gvjs_Db(gvjs_n(a,function(c){return gvjs_6d(c,b)}),function(c){return null!=c}):null}gvjs_.AC=function(a,b){return gvjs_5d(this,gvjs_7d,a,b)};function gvjs_8d(a){if(null==a)return null;if(typeof a===gvjs_La)return a;a=String(a);return"1"===a||a.toLowerCase()===gvjs_6a?!0:"0"===a||a.toLowerCase()===gvjs_Sa?!1:null}
function gvjs_s(a,b,c){return gvjs_4d(a,gvjs_8d,!1,b,c)}gvjs_.Gq=function(a){return gvjs_5d(this,gvjs_8d,a)};function gvjs_9d(a){if(null==a)return null;if(typeof a===gvjs_c)return a;a=gvjs_gc(String(a));return isNaN(a)?null:a}function gvjs_t(a,b,c){return gvjs_4d(a,gvjs_9d,0,b,c)}gvjs_.Ca=function(a){return gvjs_5d(this,gvjs_9d,a)};function gvjs_$d(a){return null==a?null:typeof a===gvjs_c||typeof a===gvjs_d||typeof a===gvjs_La?a:null}gvjs_.kt=function(a){return gvjs_5d(this,gvjs_$d,a)};
function gvjs_ae(a){return null==a?null:Array.isArray(a)?gvjs_Db(gvjs_n(a,gvjs_9d),function(b){return null!=b}):null}gvjs_.mI=function(a){return gvjs_5d(this,gvjs_ae,a)};function gvjs_be(a){a=gvjs_9d(a);return null!=a&&0<=a?a:null}function gvjs_ce(a,b,c){return gvjs_4d(a,gvjs_be,0,b,c)}gvjs_.zC=function(a){return gvjs_5d(this,gvjs_be,a)};function gvjs_de(a){a=gvjs_9d(a);return null!=a?gvjs_Cc(a,0,1):null}gvjs_.nra=function(a){return gvjs_5d(this,gvjs_de,a)};
function gvjs_ee(a,b){if(null==a)return null;if(""===a)return gvjs_b;if(typeof a===gvjs_Ya)return a.color||a.lighter||a.darker?a:null;a=gvjs_6d(a);if(Array.isArray(b)&&gvjs_Hb(b,a))return a;try{return gvjs_Od(a)}catch(c){return null}}gvjs_.Py=function(a,b){return gvjs_5d(this,gvjs_ee,a,b)};function gvjs_fe(a,b){b=null!=b?b:1;var c=gvjs_9d(a);null==c&&(a=gvjs_6d(a),null!=a&&gvjs_Lb(a)&&(c=a.slice(0,-1),c=b*Number(c)/100));null!=c&&(c=0===b?0:b*gvjs_Cc(c/b,0,1));return c}
gvjs_.$k=function(a,b){return gvjs_5d(this,gvjs_fe,a,b)};gvjs_Zd={string:gvjs__d.prototype.ob,number:gvjs__d.prototype.Ca,"boolean":gvjs__d.prototype.Gq,numberOrString:[gvjs_c,gvjs_d],primitive:gvjs__d.prototype.kt,ratio:gvjs__d.prototype.nra,nonNegative:gvjs__d.prototype.zC,absOrPercentage:gvjs__d.prototype.$k,arrayOfNumber:gvjs__d.prototype.mI,arrayOfString:gvjs__d.prototype.AC,color:gvjs__d.prototype.Py,object:gvjs__d.prototype.nb};gvjs_fd.prototype.format=gvjs_fd.prototype.format;gvjs_fd.Format={FULL_DATE:0,LONG_DATE:1,MEDIUM_DATE:2,SHORT_DATE:3,FULL_TIME:4,LONG_TIME:5,MEDIUM_TIME:6,SHORT_TIME:7,FULL_DATETIME:8,LONG_DATETIME:9,MEDIUM_DATETIME:10,SHORT_DATETIME:11};var gvjs_ge=gvjs_ld;gvjs_pd.Format={DECIMAL:1,SCIENTIFIC:2,PERCENT:3,CURRENCY:4,COMPACT_SHORT:5,COMPACT_LONG:6};gvjs_pd.prototype.format=gvjs_pd.prototype.format;gvjs_pd.prototype.setMinimumFractionDigits=gvjs_pd.prototype.setMinimumFractionDigits;
gvjs_pd.prototype.setMaximumFractionDigits=gvjs_pd.prototype.setMaximumFractionDigits;gvjs_pd.prototype.setSignificantDigits=gvjs_pd.prototype.setSignificantDigits;gvjs_pd.setEnforceAsciiDigits=function(a){gvjs_rd=a};gvjs_pd.isEnforceAsciiDigits=function(){return gvjs_rd};var gvjs_he=gvjs_nd;gvjs_8c.createTimeZone=gvjs_9c;function gvjs_ie(){}gvjs_ie.prototype.ac=function(a){return this.hO(a)};function gvjs_je(a){this.init(a)}gvjs_l(gvjs_je,gvjs_ie);gvjs_je.prototype.init=function(a){a=new gvjs__d([a||{},{formatType:gvjs_1a,valueType:gvjs_Qa}]);this.fd=a.ea(gvjs_Za);this.Nb=null;this.Sna=a.ob("formatType",gvjs_Haa);this.Iya=a.ob("valueType",gvjs_ke);this.gla=gvjs_s(a,"clearMinutes",!1);this.Sfa=null;a=a.Ca("timeZone");null!=a&&(this.Sfa=gvjs_8c.createTimeZone(60*-a))};
var gvjs_le=gvjs_fd.Format,gvjs_Haa={Pza:gvjs_Ta,nAa:"long",tAa:gvjs_Wa,SHORT:gvjs_1a},gvjs_ke={Gha:gvjs_Pa,Hha:gvjs_Qa,vBa:"time"};
function gvjs_Iaa(a,b){switch(a){case gvjs_Pa:switch(b){case gvjs_Ta:return gvjs_fd.Format.FULL_DATE;case "long":return gvjs_fd.Format.LONG_DATE;case gvjs_Wa:return gvjs_fd.Format.MEDIUM_DATE;case gvjs_1a:return gvjs_fd.Format.SHORT_DATE}case gvjs_Qa:switch(b){case gvjs_Ta:return gvjs_fd.Format.FULL_DATETIME;case "long":return gvjs_fd.Format.LONG_DATETIME;case gvjs_Wa:return gvjs_fd.Format.MEDIUM_DATETIME;case gvjs_1a:return gvjs_fd.Format.SHORT_DATETIME}case "time":switch(b){case gvjs_Ta:return gvjs_fd.Format.FULL_TIME;
case "long":return gvjs_fd.Format.LONG_TIME;case gvjs_Wa:return gvjs_fd.Format.MEDIUM_TIME;case gvjs_1a:return gvjs_fd.Format.SHORT_TIME}default:return gvjs_fd.Format.FULL_DATETIME}}gvjs_je.prototype.um=gvjs_e(16);gvjs_je.prototype.format=function(a,b){var c=gvjs_6d(a.Y(b),gvjs_ke);if(c==gvjs_Pa||c==gvjs_Qa){c=this.fN(c);for(var d=a.ca(),e=0;e<d;e++){var f=a.getValue(e,b);f=gvjs_me(this,c,f);gvjs_j(a.qp)&&a.qp(e,b,f)}}};
gvjs_je.prototype.hO=function(a){this.Nb||(this.Nb=this.fN(this.Iya));return gvjs_me(this,this.Nb,a)};gvjs_je.prototype.fN=function(a){var b=this.fd;null==b&&(b=gvjs_Iaa(a,this.Sna));return new gvjs_fd(b)};function gvjs_me(a,b,c){if(null===c)return"";var d=a.Sfa;null==d&&(d=gvjs_8c.createTimeZone(c.getTimezoneOffset()));c=new Date(c.getTime());a.gla&&c.setMinutes(0);return b.format(c,d)};function gvjs_ne(a){var b=new gvjs__d([a||{},{decimalSymbol:gvjs_oe,groupingSymbol:gvjs_pe,fractionDigits:2,significantDigits:null,negativeParens:!1,prefix:"",suffix:"",scaleFactor:1}]);this.iy=gvjs_ce(b,"fractionDigits");a&&typeof a.fractionDigits===gvjs_c&&isNaN(a.fractionDigits)&&(this.iy=NaN);this.vm=b.zC("significantDigits");this.cma=gvjs_r(b,"decimalSymbol");this.xY=gvjs_r(b,"groupingSymbol");this.rda=gvjs_r(b,gvjs__a);this.Ffa=gvjs_r(b,gvjs_3a);this.hca=b.Py("negativeColor");this.ica=gvjs_s(b,
"negativeParens");(this.fd=b.ob(gvjs_Za))&&this.fd.toLowerCase()in gvjs_qe&&(this.fd=gvjs_qe[this.fd.toLowerCase()]);this.gK=gvjs_t(b,"scaleFactor");if(0>=this.gK)throw Error("Scale factor must be a positive number.");this.Nb=null}gvjs_l(gvjs_ne,gvjs_ie);
var gvjs_qe={decimal:gvjs_pd.Format.DECIMAL,scientific:gvjs_pd.Format.SCIENTIFIC,percent:gvjs_pd.Format.PERCENT,currency:gvjs_pd.Format.CURRENCY,"short":gvjs_pd.Format.COMPACT_SHORT,"long":gvjs_pd.Format.COMPACT_LONG},gvjs_re=!1,gvjs_oe=gvjs_he.DECIMAL_SEP,gvjs_pe=gvjs_he.GROUP_SEP,gvjs_se=gvjs_he.DECIMAL_PATTERN;
gvjs_ne.prototype.format=function(a,b){if(a.Y(b)==gvjs_c)for(var c=0;c<a.ca();c++){var d=a.getValue(c,b);if(null!=d){var e=this.ac(d);gvjs_j(a.qp)&&a.qp(c,b,e);gvjs_j(a.setProperty)&&!gvjs_Mb(gvjs_ec(this.hca))&&0>d&&a.setProperty(c,b,gvjs_2a,gvjs_Oa+this.hca+";")}}};
gvjs_ne.prototype.hO=function(a){var b=a/this.gK;if(null!==this.fd){a=gvjs_pd.isEnforceAsciiDigits();gvjs_pd.setEnforceAsciiDigits(!gvjs_re);var c=new gvjs_pd(this.fd);this.fd!=gvjs_pd.Format.COMPACT_SHORT&&this.fd!=gvjs_pd.Format.COMPACT_LONG||c.setSignificantDigits(3);this.Nb=c;null!=this.vm&&(c.setSignificantDigits(this.vm),c.setMaximumFractionDigits(this.vm));b=c.format(b);b=this.rda+b+this.Ffa;gvjs_pd.setEnforceAsciiDigits(a)}else{if(isNaN(this.iy))return String(a);this.ica&&(b=Math.abs(b));
c=b;0==this.iy&&(c=Math.round(c));b=[];0>c&&(c=-c,b.push("-"));var d=Math.pow(10,this.iy),e=Math.round(c*d);c=String(Math.floor(e/d));d=String(e%d);if(3<c.length&&this.xY)for(e=c.length%3,0<e&&(b.push(c.substring(0,e),this.xY),c=c.substring(e));3<c.length;)b.push(c.substring(0,3),this.xY),c=c.substring(3);b.push(c);0<this.iy&&(b.push(this.cma),d.length<this.iy&&(d=gvjs_ea+d),b.push(d.substring(d.length-this.iy)));b=b.join("");b=this.rda+b+this.Ffa;this.ica&&0>a&&(b="("+b+")")}return b};
gvjs_ne.prototype.parse=function(a){if(this.Nb&&this.Nb.parse){var b=gvjs_pd.isEnforceAsciiDigits();gvjs_pd.setEnforceAsciiDigits(!gvjs_re);a=this.Nb.parse(a);gvjs_pd.setEnforceAsciiDigits(b);return a}throw Error("Cannot parse without parser.");};function gvjs_te(a){this.m=a||{}}gvjs_te.prototype.format=function(a,b){if(a.Y(b)==gvjs_c)for(var c=this.m.base||0,d=0;d<a.ca();d++){var e=a.getValue(d,b);e=e<c?"google-visualization-formatters-arrow-dr":e>c?"google-visualization-formatters-arrow-ug":"google-visualization-formatters-arrow-empty";gvjs_j(a.setProperty)&&a.setProperty(d,b,gvjs_Na,e)}};function gvjs_ue(a){this.m=a||{}}var gvjs_Jaa={red:"r",blue:"b",green:"g"};function gvjs_ve(a,b,c){0<b&&c.push('<span class="google-charts-bar-'+(a||"w")+'" style="width:'+b+'px;"></span>')}
gvjs_ue.prototype.format=function(a,b){if(a.Y(b)==gvjs_c){var c=this.m,d=c.min,e=c.max,f=null;if(null==d||null==e)f=a.mn(b),null==e&&(e=f.max),null==d&&(d=Math.min(0,f.min));d>=e&&(f=f||a.mn(b),e=f.max,d=f.min);d==e&&(0==d?e=1:0<d?d=0:e=0);f=e-d;var g=c.base||0;g=Math.max(d,Math.min(e,g));var h=c.width||100,k=c.showValue;null==k&&(k=!0);for(var l=Math.round((g-d)/f*h),m=h-l,n=0;n<a.ca();n++){var p=a.getValue(n,b),q=[];p=Math.max(d,Math.min(e,p));var r=Math.ceil((p-d)/f*h);q.push('<span class="google-visualization-formatters-bars">');
gvjs_ve("s",1,q);var t=gvjs_we(c.colorPositive,"b"),u=gvjs_we(c.colorNegative,"r"),v=c.drawZeroLine?1:0;0<l?p<g?(gvjs_ve("w",r,q),gvjs_ve(u,l-r,q),0<v&&gvjs_ve("z",v,q),gvjs_ve("w",m,q)):(gvjs_ve("w",l,q),0<v&&gvjs_ve("z",v,q),gvjs_ve(t,r-l,q),gvjs_ve("w",h-r,q)):(gvjs_ve(t,r,q),gvjs_ve("w",h-r,q));gvjs_ve("s",1,q);p=a.getProperty(n,b,gvjs_Ia);null==p&&gvjs_j(a.setProperty)&&(p=a.Na(n,b),a.setProperty(n,b,gvjs_Ia,p));k&&(q.push("\u00a0"),q.push(p));q.push("</span>\u00a0");gvjs_j(a.qp)&&a.qp(n,b,q.join(""))}}};
function gvjs_we(a,b){a=(a||"").toLowerCase();return gvjs_Jaa[a]||b};function gvjs_xe(a,b,c,d){gvjs_wb(a)&&(a=a.getTime());gvjs_wb(b)&&(b=b.getTime());gvjs_h(a)&&(a=gvjs_ye(a));gvjs_h(b)&&(b=gvjs_ye(b));this.HX=a;this.R3=b;this.Dk=c;this.lx=d}gvjs_xe.prototype.contains=function(a){var b=this.HX,c=this.R3;if(null==a)return null==b&&null==c;gvjs_wb(a)?a=a.getTime():gvjs_h(a)&&(a=gvjs_ye(a));return(null==b||a>=b)&&(null==c||a<c)};gvjs_xe.prototype.he=function(){return this.Dk};gvjs_xe.prototype.getBackgroundColor=function(){return this.lx};
function gvjs_ze(a,b,c,d,e){gvjs_xe.call(this,a,b,c,"");this.f1=b-a;0>=this.f1&&(this.f1=1);this.Vna=gvjs_Ld(gvjs_Gd(d).hex);this.Sxa=gvjs_Ld(gvjs_Gd(e).hex)}gvjs_l(gvjs_ze,gvjs_xe);gvjs_ze.prototype.getBackgroundColor=function(a){if(typeof a!==gvjs_c)return"";a=gvjs_Nd(this.Vna,this.Sxa,1-(a-this.HX)/this.f1);return gvjs_Md(a[0],a[1],a[2])};function gvjs_Ae(){this.vR=[]}gvjs_Ae.prototype.addRange=function(a,b,c,d){this.vR.push(new gvjs_xe(a,b,c,d))};
gvjs_Ae.prototype.Bja=function(a,b,c,d,e){this.vR.push(new gvjs_ze(a,b,c,d,e))};gvjs_Ae.prototype.format=function(a,b){var c=a.Y(b);if(c==gvjs_c||c==gvjs_d||c==gvjs_Pa||c==gvjs_Qa||c==gvjs_4a)for(c=0;c<a.ca();c++){for(var d=a.getValue(c,b),e="",f=0;f<this.vR.length;f++){var g=this.vR[f];if("undefined"!==typeof d&&g.contains(d)){f=g.he();d=g.getBackgroundColor(d);f&&(e+=gvjs_Oa+f+";");d&&(e+=gvjs_Ka+d+";");break}}gvjs_j(a.setProperty)&&a.setProperty(c,b,gvjs_2a,e)}};
function gvjs_ye(a){return 36E5*a[0]+6E4*a[1]+1E3*a[2]+(4==a.length?a[3]:0)};function gvjs_Be(a){this.fd=a||""}function gvjs_Kaa(a,b,c,d,e,f,g){return 0<f&&"\\"==g[f-1]?d:b.Na(a,c[parseInt(e,10)])}gvjs_Be.prototype.format=function(a,b,c,d){var e=b[0];null!=c&&gvjs_ub(c)==gvjs_c&&(e=c);c=d||null;for(d=0;d<a.ca();d++){var f=this.fd.replace(/{(\d+)}/g,gvjs_yb(gvjs_Kaa,d,a,b));f=f.replace(/\\(.)/g,"$1");c&&gvjs_j(a.setProperty)?a.setProperty(d,e,c,f):gvjs_j(a.qp)&&a.qp(d,e,f)}};gvjs_g(gvjs_Ua,gvjs_ne,void 0);gvjs_ne.prototype.format=gvjs_ne.prototype.format;gvjs_ne.prototype.formatValue=gvjs_ne.prototype.ac;gvjs_g("google.visualization.NumberFormat.useNativeCharactersIfAvailable",function(a){gvjs_re=a},void 0);gvjs_g("google.visualization.NumberFormat.DECIMAL_SEP",gvjs_oe,void 0);gvjs_g("google.visualization.NumberFormat.GROUP_SEP",gvjs_pe,void 0);gvjs_g("google.visualization.NumberFormat.DECIMAL_PATTERN",gvjs_se,void 0);
gvjs_g("google.visualization.ColorFormat",gvjs_Ae,void 0);gvjs_Ae.prototype.format=gvjs_Ae.prototype.format;gvjs_Ae.prototype.addRange=gvjs_Ae.prototype.addRange;gvjs_Ae.prototype.addGradientRange=gvjs_Ae.prototype.Bja;gvjs_g("google.visualization.BarFormat",gvjs_ue,void 0);gvjs_ue.prototype.format=gvjs_ue.prototype.format;gvjs_g("google.visualization.ArrowFormat",gvjs_te,void 0);gvjs_te.prototype.format=gvjs_te.prototype.format;gvjs_g("google.visualization.PatternFormat",gvjs_Be,void 0);
gvjs_Be.prototype.format=gvjs_Be.prototype.format;gvjs_g("google.visualization.DateFormat",gvjs_je,void 0);gvjs_je.prototype.format=gvjs_je.prototype.format;gvjs_je.prototype.formatValue=gvjs_je.prototype.ac;gvjs_g(gvjs_Ua,gvjs_ne,void 0);gvjs_ne.prototype.format=gvjs_ne.prototype.format;gvjs_g("google.visualization.TableColorFormat",gvjs_Ae,void 0);gvjs_g("google.visualization.TableBarFormat",gvjs_ue,void 0);gvjs_ue.prototype.format=gvjs_ue.prototype.format;
gvjs_g("google.visualization.TableArrowFormat",gvjs_te,void 0);gvjs_te.prototype.format=gvjs_te.prototype.format;gvjs_g("google.visualization.TablePatternFormat",gvjs_Be,void 0);gvjs_Be.prototype.format=gvjs_Be.prototype.format;gvjs_g("google.visualization.TableDateFormat",gvjs_je,void 0);
